export "bridge-01d-cm"

{` Bridges bridge for xca:RmloopCGm (line 658), blind file 01-groups.ny.
   The equivalence is defined directly with the underlying map the blind
   statement prescribes (l ↦ transport along ap U l, U = underlying type),
   so the compatibility clause holds by refl. It is an equivalence onto the
   permutations generated by s because
   - every loop of BC'_m is merely a power of g0 = Ω(J)(loop), J the factor
     S¹ → BC'_m of the zero image (connected fibers, our
     zero_image_factor_connected_fibers, and every loop of S¹ is a power,
     our circle_power_winding);
   - U ∘ J is (−).fst.fst ∘ R_m, so ap U g0 = ua s (our
     pointed_circle_loop_rec_beta);
   - ap U is injective (the projection to FinSet_m has set fibers, and the
     inclusions FinSet_m ⊂ Set ⊂ U are subtypes). `}

def BridgeIdFam (A B : Type) (g : A → B) (b : B) (z : A) : Type ≔ Id B b (g z)

def bridge_pathover_id_fam (A B : Type) (g : A → B) (b : B) (x : A)
  : (y : A) (r : Id A x y) (u : Id B b (g x)) (v : Id B b (g y)) → Id (BridgeIdFam A B g b) r u v →
    Id (Id B b (g y)) (concat B b (g x) (g y) u (refl g r)) v
  ≔ y r ↦ J A x (y r ↦ (u : Id B b (g x)) (v : Id B b (g y)) → Id (BridgeIdFam A B g b) r u v →
        Id (Id B b (g y)) (concat B b (g x) (g y) u (refl g r)) v)
      (u v w ↦ concat (Id B b (g x)) (concat B b (g x) (g x) u (refl (g x))) u v (concat_p1 B b (g x) u) w)
      y r

def bridge_conj_solve (Z : Type) (a c : Z) (p : Id Z a c) (r : Id Z c c) (q : Id Z a a)
  (e : Id (Id Z a c) (concat Z a c c p r) (concat Z a a c q p))
  : Id (Id Z a a) q (pointed_loop_conjugate Z a c p r)
  ≔ inverse (Id Z a a) (pointed_loop_conjugate Z a c p r) q
      (calc
        concat Z a c a p (concat Z c c a r (inverse Z a c p))
        = concat Z a c a (concat Z a c c p r) (inverse Z a c p)
          by inverse (Id Z a a) (concat Z a c a (concat Z a c c p r) (inverse Z a c p)) (concat Z a c a p (concat Z c c a r (inverse Z a c p)))
            (concat_assoc Z a c c a p r (inverse Z a c p))
        = concat Z a c a (concat Z a a c q p) (inverse Z a c p)
          by refl ((t ↦ concat Z a c a t (inverse Z a c p)) : Id Z a c → Id Z a a) e
        = concat Z a a a q (concat Z a c a p (inverse Z a c p)) by concat_assoc Z a a c a q p (inverse Z a c p)
        = concat Z a a a q (refl a) by refl (concat Z a a a q) (concat_inverse_right Z a c p)
        = q by concat_p1 Z a a q ∎)

def bridge_st_transport (A B : Type) (f : A → B) (X : B) (a : A) (q : Id B X (f a))
  : (Y : B) (p : Id B X Y) →
    Id (SetTrunc (BookFiber A B f Y)) (transport B (W ↦ SetTrunc (BookFiber A B f W)) X Y p (set_trunc (BookFiber A B f X) (a, q)))
      (set_trunc (BookFiber A B f Y) (a, concat B Y X (f a) (inverse B X Y p) q))
  ≔ Y p ↦ J B X (Y p ↦ Id (SetTrunc (BookFiber A B f Y))
        (transport B (W ↦ SetTrunc (BookFiber A B f W)) X Y p (set_trunc (BookFiber A B f X) (a, q)))
        (set_trunc (BookFiber A B f Y) (a, concat B Y X (f a) (inverse B X Y p) q)))
      (concat (SetTrunc (BookFiber A B f X))
        (transport B (W ↦ SetTrunc (BookFiber A B f W)) X X (refl X) (set_trunc (BookFiber A B f X) (a, q)))
        (set_trunc (BookFiber A B f X) (a, q))
        (set_trunc (BookFiber A B f X) (a, concat B X X (f a) (inverse B X X (refl X)) q))
        (transport_refl B (W ↦ SetTrunc (BookFiber A B f W)) X (set_trunc (BookFiber A B f X) (a, q)))
        (refl ((t ↦ set_trunc (BookFiber A B f X) (a, t)) : Id B X (f a) → SetTrunc (BookFiber A B f X))
          (inverse (Id B X (f a)) (concat B X X (f a) (inverse B X X (refl X)) q) q
            (concat (Id B X (f a)) (concat B X X (f a) (inverse B X X (refl X)) q) (concat B X X (f a) (refl X) q) q
              (refl ((t ↦ concat B X X (f a) t q) : Id B X X → Id B X (f a)) (inverse_refl B X))
              (concat_1p B X (f a) q)))))
      Y p

def bridge_rl_J (C : CircleSignature) (n : Nat) (z : C .carrier) : BlindBCGprimeCarrier C n
  ≔ (blind_Rm_finset C n z, set_trunc (BlindRmFiber C n (blind_Rm_finset C n z)) (z, refl (blind_Rm_finset C n z)))


def bridge_rl_Jpt (C : CircleSignature) (n : Nat)
  : Id (BlindBCGprimeCarrier C n) (blind_BCGprime C n .point) (bridge_rl_J C n (C .base))
  ≔ let F ≔ FiniteSetsAt (suc. n) in
    let f ≔ blind_Rm_finset C n in let b ≔ blind_bn_finset (suc. n) in
    let β ≔ blind_Rm_finset_base C n in
    let P : F → Type ≔ W ↦ SetTrunc (BlindRmFiber C n W) in
    (β, pathover_of_eq F P b (f (C .base)) β (set_trunc (BlindRmFiber C n b) (C .base, β))
      (set_trunc (BlindRmFiber C n (f (C .base))) (C .base, refl (f (C .base))))
      (concat (P (f (C .base))) (transport F P b (f (C .base)) β (set_trunc (BlindRmFiber C n b) (C .base, β)))
        (set_trunc (BlindRmFiber C n (f (C .base))) (C .base, concat F (f (C .base)) b (f (C .base)) (inverse F b (f (C .base)) β) β))
        (set_trunc (BlindRmFiber C n (f (C .base))) (C .base, refl (f (C .base))))
        (bridge_st_transport (C .carrier) F f b (C .base) β (f (C .base)) β)
        (refl ((t ↦ set_trunc (BlindRmFiber C n (f (C .base))) (C .base, t)) : Id F (f (C .base)) (f (C .base)) → P (f (C .base)))
          (concat_inverse_left F b (f (C .base)) β))))

def bridge_rl_Jp (C : CircleSignature) (n : Nat) : BookPointedMap (circle_pointed C) (blind_BCGprime C n)
  ≔ (bridge_rl_J C n, bridge_rl_Jpt C n)

def bridge_rl_Up (C : CircleSignature) (n : Nat) : BookPointedMap (blind_BCGprime C n) (Type, Fin (suc. n))
  ≔ (u ↦ u .fst .fst .fst, refl (Fin (suc. n)))

def bridge_rl_Vp (n : Nat) : BookPointedMap (FiniteSetsAt (suc. n), blind_bn_finset (suc. n)) (Type, Fin (suc. n))
  ≔ (u ↦ u .fst .fst, refl (Fin (suc. n)))

def bridge_rl_kb (C : CircleSignature) (n : Nat) : BookPointedMap (circle_pointed C) (FiniteSetsAt (suc. n), blind_bn_finset (suc. n))
  ≔ (blind_Rm_finset C n, blind_Rm_finset_base C n)

def bridge_rl_compose (C : CircleSignature) (n : Nat)
  : Id (BookPointedMap (circle_pointed C) (Type, Fin (suc. n)))
      (book_pointed_compose (circle_pointed C) (blind_BCGprime C n) (Type, Fin (suc. n)) (bridge_rl_Jp C n) (bridge_rl_Up C n))
      (book_pointed_compose (circle_pointed C) (FiniteSetsAt (suc. n), blind_bn_finset (suc. n)) (Type, Fin (suc. n))
        (bridge_rl_kb C n) (bridge_rl_Vp n))
  ≔ refl (book_pointed_compose (circle_pointed C) (blind_BCGprime C n) (Type, Fin (suc. n)) (bridge_rl_Jp C n) (bridge_rl_Up C n))

def bridge_rl_g0 (C : CircleSignature) (n : Nat) : Loop (blind_BCGprime C n)
  ≔ loops_map (circle_pointed C) (blind_BCGprime C n) (bridge_rl_Jp C n) (C .loop)

def bridge_rl_set_loop_fst (S : SetTypes) (e : Equiv (S .fst) (S .fst))
  : Id (Id Type (S .fst) (S .fst)) (refl ((u ↦ u .fst) : SetTypes → Type) (blind_set_loop S e)) (ua (S .fst) (S .fst) e)
  ≔ equiv_counit (Id SetTypes S S) (Id Type (S .fst) (S .fst)) (subtype_path_equiv Type isSet isset_isprop S S) (ua (S .fst) (S .fst) e)

def bridge_rl_g0_U (C : CircleSignature) (n : Nat)
  : Id (Id Type (Fin (suc. n)) (Fin (suc. n)))
      (loops_map (blind_BCGprime C n) (Type, Fin (suc. n)) (bridge_rl_Up C n) (bridge_rl_g0 C n))
      (ua (Fin (suc. n)) (Fin (suc. n)) (finite_fin_successor n))
  ≔ let T : Pointed ≔ (Type, Fin (suc. n)) in let X ≔ circle_pointed C in
    let Fp : Pointed ≔ (FiniteSetsAt (suc. n), blind_bn_finset (suc. n)) in
    let FT ≔ Fin (suc. n) in let L ≔ Id Type FT FT in
    let bl ≔ blind_finset_loop (suc. n) (finite_fin_successor n) in
    let S ≔ blind_bn_set (suc. n) in
    calc
      loops_map (blind_BCGprime C n) T (bridge_rl_Up C n) (bridge_rl_g0 C n)
      = loops_map X T (book_pointed_compose X (blind_BCGprime C n) T (bridge_rl_Jp C n) (bridge_rl_Up C n)) (C .loop)
        by inverse L (loops_map X T (book_pointed_compose X (blind_BCGprime C n) T (bridge_rl_Jp C n) (bridge_rl_Up C n)) (C .loop))
          (loops_map (blind_BCGprime C n) T (bridge_rl_Up C n) (bridge_rl_g0 C n))
          (loops_map_compose_pointwise X (blind_BCGprime C n) T (bridge_rl_Jp C n) (bridge_rl_Up C n) (C .loop))
      = loops_map Fp T (bridge_rl_Vp n) (loops_map X Fp (bridge_rl_kb C n) (C .loop))
        by loops_map_compose_pointwise X Fp T (bridge_rl_kb C n) (bridge_rl_Vp n) (C .loop)
      = loops_map Fp T (bridge_rl_Vp n) bl
        by refl (loops_map Fp T (bridge_rl_Vp n)) (pointed_circle_loop_rec_beta C (FiniteSetsAt (suc. n)) (blind_bn_finset (suc. n)) bl)
      = refl ((u ↦ u .fst .fst) : FiniteSetsAt (suc. n) → Type) bl
        by loop_conjugate_at_refl Type FT (refl ((u ↦ u .fst .fst) : FiniteSetsAt (suc. n) → Type) bl)
      = refl ((u ↦ u .fst) : SetTypes → Type) (blind_set_loop S (finite_fin_successor n))
        by refl (refl ((u ↦ u .fst) : SetTypes → Type))
          (equiv_counit (Id (FiniteSetsAt (suc. n)) (blind_bn_finset (suc. n)) (blind_bn_finset (suc. n))) (Id SetTypes S S)
            (bridge_fsa_path_equiv (suc. n) (blind_bn_finset (suc. n)) (blind_bn_finset (suc. n))) (blind_set_loop S (finite_fin_successor n)))
      = ua FT FT (finite_fin_successor n) by bridge_rl_set_loop_fst S (finite_fin_successor n) ∎

{` Every loop of BC'_m is merely a power of g0. `}
def bridge_rl_powers (C : CircleSignature) (n : Nat) (q : Loop (blind_BCGprime C n))
  : Mere (Σ Int (k ↦ Id (Loop (blind_BCGprime C n)) q (loop_power (BlindBCGprimeCarrier C n) (blind_BCGprime C n .point) (bridge_rl_g0 C n) k)))
  ≔ let Z ≔ BlindBCGprimeCarrier C n in let pt ≔ blind_BCGprime C n .point in
    let J ≔ bridge_rl_J C n in let Jpt ≔ bridge_rl_Jpt C n in
    let X ≔ circle_pointed C in let Bz ≔ C .base in
    let Fb ≔ BookFiber (C .carrier) Z J pt in
    let T ≔ Σ Int (k ↦ Id (Loop (blind_BCGprime C n)) q (loop_power Z pt (bridge_rl_g0 C n) k)) in
    let u1 : Fb ≔ (Bz, Jpt) in
    let u2 : Fb ≔ (Bz, concat Z pt pt (J Bz) q Jpt) in
    mere_rec (Id Fb u1 u2) (Mere T) (mere_isprop T)
      (w ↦
        let l ≔ w .fst in
        let e1 : Id (Id Z pt (J Bz)) (concat Z pt (J Bz) (J Bz) Jpt (refl J l)) (concat Z pt pt (J Bz) q Jpt)
          ≔ bridge_pathover_id_fam (C .carrier) Z J pt Bz Bz l Jpt (concat Z pt pt (J Bz) q Jpt) (w .snd) in
        let e2 : Id (Loop (blind_BCGprime C n)) q (loops_map X (blind_BCGprime C n) (bridge_rl_Jp C n) l)
          ≔ bridge_conj_solve Z pt (J Bz) Jpt (refl J l) q e1 in
        let k ≔ circle_winding C l in
        mere T (k,
          calc
            q = loops_map X (blind_BCGprime C n) (bridge_rl_Jp C n) l by e2
            = loops_map X (blind_BCGprime C n) (bridge_rl_Jp C n) (loop_power (C .carrier) Bz (C .loop) k)
              by refl (loops_map X (blind_BCGprime C n) (bridge_rl_Jp C n))
                (inverse (Id (C .carrier) Bz Bz) (loop_power (C .carrier) Bz (C .loop) k) l (circle_power_winding C l))
            = loop_power Z pt (bridge_rl_g0 C n) k
              by loops_map_power X (blind_BCGprime C n) (bridge_rl_Jp C n) (C .loop) k ∎))
      (zero_image_factor_connected_fibers (C .carrier) (FiniteSetsAt (suc. n)) (blind_Rm_finset C n) pt .snd u1 u2)

{` The map on loops and its properties. `}
def bridge_rl_Phi (C : CircleSignature) (n : Nat) (l : Loop (blind_BCGprime C n)) : Id Type (Fin (suc. n)) (Fin (suc. n))
  ≔ refl ((u ↦ u .fst .fst .fst) : BlindBCGprimeCarrier C n → Type) l

def bridge_rl_Phi_loops (C : CircleSignature) (n : Nat) (l : Loop (blind_BCGprime C n))
  : Id (Id Type (Fin (suc. n)) (Fin (suc. n))) (bridge_rl_Phi C n l)
      (loops_map (blind_BCGprime C n) (Type, Fin (suc. n)) (bridge_rl_Up C n) l)
  ≔ inverse (Id Type (Fin (suc. n)) (Fin (suc. n))) (loops_map (blind_BCGprime C n) (Type, Fin (suc. n)) (bridge_rl_Up C n) l)
      (bridge_rl_Phi C n l) (loop_conjugate_at_refl Type (Fin (suc. n)) (bridge_rl_Phi C n l))

def bridge_rl_power_trr (n : Nat) (k : Int) (x : Fin (suc. n))
  : Id (Fin (suc. n))
      (transport Type (Y ↦ Y) (Fin (suc. n)) (Fin (suc. n)) (loop_power Type (Fin (suc. n)) (ua (Fin (suc. n)) (Fin (suc. n)) (finite_fin_successor n)) k) x)
      (permutation_power (Fin (suc. n)) (finite_fin_successor n) k x)
  ≔ let FT ≔ Fin (suc. n) in let s ≔ finite_fin_successor n in
    let e : Int → FT ≔ j ↦ permutation_power FT s j x in
    concat FT (transport Type (Y ↦ Y) FT FT (loop_power Type FT (ua FT FT s) k) x) (e (int_add int_zero k)) (e k)
      (transport_power_at Type (Y ↦ Y) FT (ua FT FT s) e
        (j ↦ inverse FT (permutation_power FT s (int_succ j) x) (s .map (permutation_power FT s j x)) (permutation_power_succ FT s j x))
        int_zero k)
      (refl e (int_add_zero_left k))

def bridge_rl_Phi_power (C : CircleSignature) (n : Nat) (l : Loop (blind_BCGprime C n)) (k : Int)
  (h : Id (Loop (blind_BCGprime C n)) l (loop_power (BlindBCGprimeCarrier C n) (blind_BCGprime C n .point) (bridge_rl_g0 C n) k))
  (x : Fin (suc. n))
  : Id (Fin (suc. n)) (transport Type (Y ↦ Y) (Fin (suc. n)) (Fin (suc. n)) (bridge_rl_Phi C n l) x)
      (permutation_power (Fin (suc. n)) (finite_fin_successor n) k x)
  ≔ let FT ≔ Fin (suc. n) in let L ≔ Id Type FT FT in
    let T : Pointed ≔ (Type, FT) in
    let Psi ≔ loops_map (blind_BCGprime C n) T (bridge_rl_Up C n) in
    let r : Id L (bridge_rl_Phi C n l) (loop_power Type FT (ua FT FT (finite_fin_successor n)) k)
      ≔ calc
        bridge_rl_Phi C n l = Psi l by bridge_rl_Phi_loops C n l
        = Psi (loop_power (BlindBCGprimeCarrier C n) (blind_BCGprime C n .point) (bridge_rl_g0 C n) k) by refl Psi h
        = loop_power Type FT (Psi (bridge_rl_g0 C n)) k by loops_map_power (blind_BCGprime C n) T (bridge_rl_Up C n) (bridge_rl_g0 C n) k
        = loop_power Type FT (ua FT FT (finite_fin_successor n)) k
          by refl ((p ↦ loop_power Type FT p k) : L → L) (bridge_rl_g0_U C n) ∎ in
    concat FT (transport Type (Y ↦ Y) FT FT (bridge_rl_Phi C n l) x)
      (transport Type (Y ↦ Y) FT FT (loop_power Type FT (ua FT FT (finite_fin_successor n)) k) x)
      (permutation_power FT (finite_fin_successor n) k x)
      (refl ((p ↦ transport Type (Y ↦ Y) FT FT p x) : L → FT) r)
      (bridge_rl_power_trr n k x)

def bridge_rl_Phi_injective (C : CircleSignature) (n : Nat) (l l' : Loop (blind_BCGprime C n))
  (h : Id (Id Type (Fin (suc. n)) (Fin (suc. n))) (bridge_rl_Phi C n l) (bridge_rl_Phi C n l'))
  : Id (Loop (blind_BCGprime C n)) l l'
  ≔ let F ≔ FiniteSetsAt (suc. n) in let b ≔ blind_bn_finset (suc. n) in
    let S ≔ blind_bn_set (suc. n) in
    let pt ≔ blind_BCGprime C n .point in
    let P : F → Type ≔ W ↦ SetTrunc (BlindRmFiber C n W) in
    let Q : Id F b b → Type ≔ p ↦ Id P p (pt .snd) (pt .snd) in
    let hS : Id (Id SetTypes S S) (l .fst .fst) (l' .fst .fst)
      ≔ equivalence_injective (Id SetTypes S S) (Id Type (S .fst) (S .fst)) (subtype_path_equiv Type isSet isset_isprop S S)
          (l .fst .fst) (l' .fst .fst) h in
    let hF : Id (Id F b b) (l .fst) (l' .fst)
      ≔ equivalence_injective (Id F b b) (Id SetTypes S S) (bridge_fsa_path_equiv (suc. n) b b) (l .fst) (l' .fst) hS in
    refl ((w ↦ (w .fst, w .snd)) : Σ (Id F b b) Q → Loop (blind_BCGprime C n))
      (subtype_equal (Id F b b) Q
        (p ↦ hlevel_one_to_prop (Q p)
          (pathover_hlevel (suc. zero.) F P (W ↦ set_to_hlevel_two (P W) (set_trunc_set (BlindRmFiber C n W))) b b p (pt .snd) (pt .snd)))
        (l .fst, l .snd) (l' .fst, l' .snd) hF)

def BridgeRlGen (n : Nat) : Type
  ≔ Σ (Equiv (Fin (suc. n)) (Fin (suc. n))) (σ ↦ Mere (Σ Int (k ↦ Id (Fin (suc. n) → Fin (suc. n)) (σ .map)
      (permutation_power (Fin (suc. n)) (finite_fin_successor n) k))))

def bridge_rl_gen_set (n : Nat) : isSet (BridgeRlGen n)
  ≔ let FT ≔ Fin (suc. n) in
    sigma_set (Equiv FT FT) (σ ↦ Mere (Σ Int (k ↦ Id (FT → FT) (σ .map) (permutation_power FT (finite_fin_successor n) k))))
      (equivalences_set FT FT (fin_set (suc. n)))
      (σ ↦ prop_is_set (Mere (Σ Int (k ↦ Id (FT → FT) (σ .map) (permutation_power FT (finite_fin_successor n) k))))
        (mere_isprop (Σ Int (k ↦ Id (FT → FT) (σ .map) (permutation_power FT (finite_fin_successor n) k)))))

def bridge_rl_e (C : CircleSignature) (n : Nat) (l : Loop (blind_BCGprime C n)) : BridgeRlGen n
  ≔ let FT ≔ Fin (suc. n) in
    let σ ≔ transport_equiv FT FT (bridge_rl_Phi C n l) in
    let M ≔ Σ Int (k ↦ Id (FT → FT) (σ .map) (permutation_power FT (finite_fin_successor n) k)) in
    (σ, mere_rec (Σ Int (k ↦ Id (Loop (blind_BCGprime C n)) l (loop_power (BlindBCGprimeCarrier C n) (blind_BCGprime C n .point) (bridge_rl_g0 C n) k)))
          (Mere M) (mere_isprop M)
          (w ↦ mere M (w .fst, funext FT (_ ↦ FT) (σ .map) (permutation_power FT (finite_fin_successor n) (w .fst))
            (x ↦ bridge_rl_Phi_power C n l (w .fst) (w .snd) x)))
          (bridge_rl_powers C n l))

def bridge_rl_e_injective (C : CircleSignature) (n : Nat)
  : PathReflecting (Loop (blind_BCGprime C n)) (BridgeRlGen n) (bridge_rl_e C n)
  ≔ l l' h ↦
    let FT ≔ Fin (suc. n) in
    bridge_rl_Phi_injective C n l l'
      (equivalence_injective (Id Type FT FT) (Equiv FT FT) (transport_univalence_equiv FT FT)
        (bridge_rl_Phi C n l) (bridge_rl_Phi C n l')
        (refl ((y ↦ y .fst) : BridgeRlGen n → Equiv FT FT) h))

def bridge_rl_e_surjective (C : CircleSignature) (n : Nat)
  : Surjective (Loop (blind_BCGprime C n)) (BridgeRlGen n) (bridge_rl_e C n)
  ≔ y ↦
    let FT ≔ Fin (suc. n) in let s ≔ finite_fin_successor n in
    let Mf : Equiv FT FT → Type ≔ σ ↦ Mere (Σ Int (k ↦ Id (FT → FT) (σ .map) (permutation_power FT s k))) in
    let L ≔ Loop (blind_BCGprime C n) in
    let Fb ≔ BookFiber L (BridgeRlGen n) (bridge_rl_e C n) y in
    mere_rec (Σ Int (k ↦ Id (FT → FT) (y .fst .map) (permutation_power FT s k))) (Mere Fb) (mere_isprop Fb)
      (w ↦
        let g ≔ loop_power (BlindBCGprimeCarrier C n) (blind_BCGprime C n .point) (bridge_rl_g0 C n) (w .fst) in
        mere Fb (g,
          subtype_equal (Equiv FT FT) Mf (σ ↦ mere_isprop (Σ Int (k ↦ Id (FT → FT) (σ .map) (permutation_power FT s k))))
            y (bridge_rl_e C n g)
            (equiv_path FT FT (y .fst) (bridge_rl_e C n g .fst)
              (funext FT (_ ↦ FT) (y .fst .map) (bridge_rl_e C n g .fst .map)
                (x ↦ concat FT (y .fst .map x) (permutation_power FT s (w .fst) x) (bridge_rl_e C n g .fst .map x)
                  (happly FT (_ ↦ FT) (y .fst .map) (permutation_power FT s (w .fst)) (w .snd) x)
                  (inverse FT (bridge_rl_e C n g .fst .map x) (permutation_power FT s (w .fst) x)
                    (bridge_rl_Phi_power C n g (w .fst) (refl g) x)))))))
      (y .snd)

def bridge_xca_RmloopCGm : blind_xca_RmloopCGm
  ≔ C n ↦
    (embedding_surjection_equiv native_truncation (Loop (blind_BCGprime C n)) (BridgeRlGen n) (bridge_rl_e C n)
       (book_fiber_prop_of_injective (Loop (blind_BCGprime C n)) (BridgeRlGen n) (bridge_rl_gen_set n) (bridge_rl_e C n)
         (bridge_rl_e_injective C n))
       (bridge_rl_e_surjective C n),
     l ↦ refl (bridge_rl_e C n l .fst .map))
