{` Blind statements for chapter 10 (fingp.tex): the examples of the introduction (fingp.tex:16, :27). `}
export "04-sylow"
export "../../../src/581-symmetric-group-inclusions"
export "../../../src/405-integer-group"
export "../../../src/435-circle-group-homomorphisms"

{` The underlying set of an orbit O : X/G. `}
def BlindOrbitSet (G : Group) (X : GSet G) (O : Orbits G X) : Type ≔ gset_underlying G (gsubset_gset G X (O .fst))

{` Example (fingp.tex:16). If X(sh_G) has 13 elements and every orbit is finite of cardinality dividing 8,
   then X has a fixed point. `}
def blind_example_thirteen : Type
  ≔ (G : Group) (X : GSet G) → BlindHasCard (gset_underlying G X) 13
    → ((O : Orbits G X) → Σ (IsFinite (BlindOrbitSet G X O)) (h ↦ NatDivides (cardinality (BlindOrbitSet G X O) h) 8))
    → Mere (BlindFixedPoints G X)

{` Example (fingp.tex:16), the parenthetical: if USym G has 8 elements, the orbits of a finite G-set are
   finite of cardinalities dividing 8. `}
def blind_example_thirteen_orbits_divide : Type
  ≔ (G : Group) → BlindHasOrder G 8 → (X : GSet G) → IsFinite (gset_underlying G X)
    → (O : Orbits G X) → Σ (IsFinite (BlindOrbitSet G X O)) (h ↦ NatDivides (cardinality (BlindOrbitSet G X O) h) 8)

{` Subgroups of G of order k. `}
def BlindSubgroupsOfOrder (G : Group) (k : Nat) : Type ≔ Σ (Subgroups G) (S ↦ BlindHasOrder (subgroup_group G S) k)

{` The image of a subgroup S of G under f : Hom(G, G'). `}
def blind_subgroup_image (G G' : Group) (f : GroupHom G G') (S : Subgroups G) : Subgroups G'
  ≔ image_subgroup (subgroup_group G S) G' (group_hom_compose (subgroup_group G S) G G' (subgroup_inclusion G S) f)

{` The subgroup generated by g: the image of the homomorphism Z → G sending the generator to g. `}
def blind_generated_subgroup (G : Group) (g : USym G) : Subgroups G
  ≔ image_subgroup integer_group G (equiv_inverse_map (GroupHom integer_group G) (USym G) (circle_group_hom_ev constructed_circle G) g)

{` Example (fingp.tex:27), Σ_3: there is a unique subgroup of order 3, and it is normal. `}
def blind_sigma3_unique_order3 : Type ≔ BookIsContr (BlindSubgroupsOfOrder (symmetric_group 3) 3)

def blind_sigma3_order3_normal : Type
  ≔ (S : BlindSubgroupsOfOrder (symmetric_group 3) 3) → IsNormalSubgroup (symmetric_group 3) (S .fst)

{` Σ_4: there are 1 or 4 subgroups of order 3, all conjugate; the subgroup of order 3 of Σ_3, viewed in Σ_4
   (along Σ_3 → Σ_4, S ↦ S ⊔ 1), is not normal; hence there are exactly 4. `}
def blind_sigma4_order3_one_or_four : Type
  ≔ Sum (BlindHasCard (BlindSubgroupsOfOrder (symmetric_group 4) 3) 1)
        (BlindHasCard (BlindSubgroupsOfOrder (symmetric_group 4) 3) 4)

def blind_sigma4_order3_conjugate : Type
  ≔ (S T : BlindSubgroupsOfOrder (symmetric_group 4) 3) → BlindConjugate (symmetric_group 4) (S .fst) (T .fst)

def blind_sigma4_image_not_normal : Type
  ≔ (S : BlindSubgroupsOfOrder (symmetric_group 3) 3)
    → Not (IsNormalSubgroup (symmetric_group 4)
             (blind_subgroup_image (symmetric_group 3) (symmetric_group 4) (symmetric_group_inclusion 3) (S .fst)))

def blind_sigma4_order3_count : Type ≔ BlindHasCard (BlindSubgroupsOfOrder (symmetric_group 4) 3) 4

{` Σ_n has n(n-1)(n-2)/6 subgroups of order 3 for n > 2 (n = m + 3). As printed this is false for n ≥ 6:
   it only counts the subgroups generated by a 3-cycle (Σ_6 has 20 of those and 20 generated by a product of
   two disjoint 3-cycles). `}
def blind_sigman_order3_count : Type
  ≔ (m : Nat) → Σ Nat (k ↦ Product (Id Nat (mul 6 k) (mul (mul (add m 3) (add m 2)) (add m 1)))
                                   (BlindHasCard (BlindSubgroupsOfOrder (symmetric_group (add m 3)) 3) k))

{` Corrected: the formula holds for 3 ≤ n ≤ 5, and Σ_6 has 40 subgroups of order 3. `}
def blind_sigman_order3_count_corrected : Type
  ≔ Product
      ((m : Nat) → Le m 2 → Σ Nat (k ↦ Product (Id Nat (mul 6 k) (mul (mul (add m 3) (add m 2)) (add m 1)))
                                     (BlindHasCard (BlindSubgroupsOfOrder (symmetric_group (add m 3)) 3) k)))
      (BlindHasCard (BlindSubgroupsOfOrder (symmetric_group 6) 3) 40)

{` For 2 < n ≤ 5 all subgroups of order 3 of Σ_n are conjugate; for n > 5 they are not. `}
def blind_sigman_order3_conjugate_small : Type
  ≔ (m : Nat) → Le m 2 → (S T : BlindSubgroupsOfOrder (symmetric_group (add m 3)) 3)
    → BlindConjugate (symmetric_group (add m 3)) (S .fst) (T .fst)

def blind_sigman_order3_not_all_conjugate : Type
  ≔ (m : Nat) → Not ((S T : BlindSubgroupsOfOrder (symmetric_group (add m 6)) 3)
                       → BlindConjugate (symmetric_group (add m 6)) (S .fst) (T .fst))

{` 3^2 = 9 divides n! for n > 5. `}
def blind_nine_divides_factorial : Type ≔ (m : Nat) → NatDivides 9 (factorial (add m 6))

{` The 3-cycle (0 1 2) of Fin 6 (the book's cyclic permutation of {1,2,3}; elements numbered as in def:finiteset, 0 = inr star). `}
def blind_f6_c012 : Fin 6 → Fin 6 ≔ [
  | inr. u ↦ inl. (inr. u)
  | inl. (inr. u) ↦ inl. (inl. (inr. u))
  | inl. (inl. (inr. u)) ↦ inr. u
  | inl. (inl. (inl. (inr. u))) ↦ inl. (inl. (inl. (inr. u)))
  | inl. (inl. (inl. (inl. (inr. u)))) ↦ inl. (inl. (inl. (inl. (inr. u))))
  | inl. (inl. (inl. (inl. (inl. (inr. u))))) ↦ inl. (inl. (inl. (inl. (inl. (inr. u)))))
  | inl. (inl. (inl. (inl. (inl. (inl. (e)))))) ↦ match e [] ]

def blind_f6_c012_cube (x : Fin 6) : Id (Fin 6) (blind_f6_c012 (blind_f6_c012 (blind_f6_c012 x))) x
  ≔ match x [
  | inr. u ↦ refl (inr. u : Fin 6)
  | inl. (inr. u) ↦ refl (inl. (inr. u) : Fin 6)
  | inl. (inl. (inr. u)) ↦ refl (inl. (inl. (inr. u)) : Fin 6)
  | inl. (inl. (inl. (inr. u))) ↦ refl (inl. (inl. (inl. (inr. u))) : Fin 6)
  | inl. (inl. (inl. (inl. (inr. u)))) ↦ refl (inl. (inl. (inl. (inl. (inr. u)))) : Fin 6)
  | inl. (inl. (inl. (inl. (inl. (inr. u))))) ↦ refl (inl. (inl. (inl. (inl. (inl. (inr. u))))) : Fin 6)
  | inl. (inl. (inl. (inl. (inl. (inl. (e)))))) ↦ match e [] ]

def blind_f6_c012_equiv : Equiv (Fin 6) (Fin 6)
  ≔ quasi_inverse_equiv (Fin 6) (Fin 6) blind_f6_c012 (x ↦ blind_f6_c012 (blind_f6_c012 x)) blind_f6_c012_cube blind_f6_c012_cube

{` The 3-cycle (3 4 5) of Fin 6 (the book's cyclic permutation of {4,5,6}). `}
def blind_f6_c345 : Fin 6 → Fin 6 ≔ [
  | inr. u ↦ inr. u
  | inl. (inr. u) ↦ inl. (inr. u)
  | inl. (inl. (inr. u)) ↦ inl. (inl. (inr. u))
  | inl. (inl. (inl. (inr. u))) ↦ inl. (inl. (inl. (inl. (inr. u))))
  | inl. (inl. (inl. (inl. (inr. u)))) ↦ inl. (inl. (inl. (inl. (inl. (inr. u)))))
  | inl. (inl. (inl. (inl. (inl. (inr. u))))) ↦ inl. (inl. (inl. (inr. u)))
  | inl. (inl. (inl. (inl. (inl. (inl. (e)))))) ↦ match e [] ]

def blind_f6_c345_cube (x : Fin 6) : Id (Fin 6) (blind_f6_c345 (blind_f6_c345 (blind_f6_c345 x))) x
  ≔ match x [
  | inr. u ↦ refl (inr. u : Fin 6)
  | inl. (inr. u) ↦ refl (inl. (inr. u) : Fin 6)
  | inl. (inl. (inr. u)) ↦ refl (inl. (inl. (inr. u)) : Fin 6)
  | inl. (inl. (inl. (inr. u))) ↦ refl (inl. (inl. (inl. (inr. u))) : Fin 6)
  | inl. (inl. (inl. (inl. (inr. u)))) ↦ refl (inl. (inl. (inl. (inl. (inr. u)))) : Fin 6)
  | inl. (inl. (inl. (inl. (inl. (inr. u))))) ↦ refl (inl. (inl. (inl. (inl. (inl. (inr. u))))) : Fin 6)
  | inl. (inl. (inl. (inl. (inl. (inl. (e)))))) ↦ match e [] ]

def blind_f6_c345_equiv : Equiv (Fin 6) (Fin 6)
  ≔ quasi_inverse_equiv (Fin 6) (Fin 6) blind_f6_c345 (x ↦ blind_f6_c345 (blind_f6_c345 x)) blind_f6_c345_cube blind_f6_c345_cube
def blind_sigma6_c012 : USym (symmetric_group 6) ≔ permutation_symmetry (standard_set 6) blind_f6_c012_equiv

def blind_sigma6_c345 : USym (symmetric_group 6) ≔ permutation_symmetry (standard_set 6) blind_f6_c345_equiv

{` The cyclic permutations of {1,2,3} and of {4,5,6} as subgroups of Σ_6, and the subgroup generated by the
   product (1 2 3)(4 5 6). `}
def blind_sigma6_h123 : Subgroups (symmetric_group 6) ≔ blind_generated_subgroup (symmetric_group 6) blind_sigma6_c012

def blind_sigma6_h456 : Subgroups (symmetric_group 6) ≔ blind_generated_subgroup (symmetric_group 6) blind_sigma6_c345

def blind_sigma6_hdouble : Subgroups (symmetric_group 6)
  ≔ blind_generated_subgroup (symmetric_group 6) (usym_mul (symmetric_group 6) blind_sigma6_c012 blind_sigma6_c345)

{` Litmus: these are subgroups of order 3. `}
def blind_sigma6_h123_order : Type ≔ BlindHasOrder (subgroup_group (symmetric_group 6) blind_sigma6_h123) 3

{` "The subgroup of cyclic permutations of {1,2,3} will not be conjugate to the subgroup of cyclic
   permutations of {4,5,6}" (literal; false: they are conjugate by (1 4)(2 5)(3 6)). `}
def blind_sigma6_h123_h456_not_conjugate : Type
  ≔ Not (BlindConjugate (symmetric_group 6) blind_sigma6_h123 blind_sigma6_h456)

{` Corrected: they are conjugate, but ⟨(1 2 3)⟩ is not conjugate to ⟨(1 2 3)(4 5 6)⟩. `}
def blind_sigma6_h123_h456_not_conjugate_corrected : Type
  ≔ Product (BlindConjugate (symmetric_group 6) blind_sigma6_h123 blind_sigma6_h456)
            (Not (BlindConjugate (symmetric_group 6) blind_sigma6_h123 blind_sigma6_hdouble))

{` Together the two cyclic subgroups give a subgroup K of order 9 (containing both). `}
def blind_sigma6_order9_join : Type
  ≔ Mere (Σ (BlindSubgroupsOfOrder (symmetric_group 6) 9) (K ↦
       Product (BlindSubgroupLe (symmetric_group 6) blind_sigma6_h123 (K .fst))
               (BlindSubgroupLe (symmetric_group 6) blind_sigma6_h456 (K .fst))))

{` There are 10 subgroups of order 9 in Σ_6 ... `}
def blind_sigma6_order9_count : Type ≔ BlindHasCard (BlindSubgroupsOfOrder (symmetric_group 6) 9) 10

{` Subsets of {1,...,6} with 3 elements. `}
def BlindTripleSubsets : Type ≔ Σ (Fin 6 → Bool) (A ↦ BlindHasCard (Σ (Fin 6) (x ↦ Id Bool (A x) true.)) 3)

{` ... "one for each subset of {1,2,3,4,5,6} of cardinality 3" (literal; false: there are 20 such subsets). `}
def blind_sigma6_order9_per_triple : Type
  ≔ Mere (Equiv BlindTripleSubsets (BlindSubgroupsOfOrder (symmetric_group 6) 9))

{` Corrected: one for each splitting of {1,...,6} into two 3-element subsets, i.e. for each 3-element subset
   containing the first element. `}
def blind_sigma6_order9_per_triple_corrected : Type
  ≔ Mere (Equiv (Σ BlindTripleSubsets (A ↦ Id Bool (A .fst (inr. star.)) true.))
                (BlindSubgroupsOfOrder (symmetric_group 6) 9))
