export "bridge-05b-sigma-small"

{` Bridges for the example at fingp.tex:27, third paragraph (Σ_6).
   The blind subgroup generated by g is the image of Z → G, 1 ↦ g; for
   g^(b+1) = e it is our cyclic subgroup ⟨g⟩ (module 1011): the hom Z → G
   factors through C_(b+1) → G, so the image is contained in ⟨g⟩, and g lies
   in the image. The blind 3-cycles (1 2 3), (4 5 6) and their product are
   our a, b, d of module 1016 (same permutations of Fin 6), so the blind
   ⟨(1 2 3)⟩, ⟨(4 5 6)⟩, ⟨(1 2 3)(4 5 6)⟩ are ours. `}

{` Members of an image subgroup are the values of the homomorphism. `}
def bridge_image_value_path (H G' : Group) (f : GroupHom H G') (z : USym H)
  : Id (USym G') (usym_hom H G' f z)
      (usym_hom (image_group H G' f) G' (image_inclusion H G' f) (usym_hom H (image_group H G' f) (image_projection H G' f) z))
  ≔ concat (USym G') (usym_hom H G' f z)
      (usym_hom H G' (group_hom_compose H (image_group H G' f) G' (image_projection H G' f) (image_inclusion H G' f)) z)
      (usym_hom (image_group H G' f) G' (image_inclusion H G' f) (usym_hom H (image_group H G' f) (image_projection H G' f) z))
      (refl ((k ↦ usym_hom H G' k z) : GroupHom H G' → USym G') (image_factorization_path H G' f))
      (happly (USym H) (_ ↦ USym G')
        (usym_hom H G' (group_hom_compose H (image_group H G' f) G' (image_projection H G' f) (image_inclusion H G' f)))
        (x ↦ usym_hom (image_group H G' f) G' (image_inclusion H G' f) (usym_hom H (image_group H G' f) (image_projection H G' f) x))
        (usym_hom_compose H (image_group H G' f) G' (image_projection H G' f) (image_inclusion H G' f)) z)

def bridge_image_member_of_value (H G' : Group) (f : GroupHom H G') (z : USym H)
  : SubgroupHasMember G' (image_subgroup H G' f) (usym_hom H G' f z)
  ≔ let S ≔ image_subgroup H G' f in
    let I ≔ image_group H G' f in
    mono_preserves_symmetries G' S (subgroup_to_mono G' S) (refl (subgroup_to_mono G' S)) (usym_hom H G' f z) .snd
      (mere (Σ (USym I) (h ↦ Id (USym G') (usym_hom H G' f z) (usym_hom I G' (image_inclusion H G' f) h)))
        (usym_hom H I (image_projection H G' f) z, bridge_image_value_path H G' f z))

def bridge_image_member_value (H G' : Group) (f : GroupHom H G') (t : USym G')
  (r : SubgroupHasMember G' (image_subgroup H G' f) t)
  : Mere (Σ (USym H) (z ↦ Id (USym G') t (usym_hom H G' f z)))
  ≔ let S ≔ image_subgroup H G' f in
    let I ≔ image_group H G' f in
    let p ≔ image_projection H G' f in
    let i ≔ image_inclusion H G' f in
    let R ≔ Σ (USym H) (z ↦ Id (USym G') t (usym_hom H G' f z)) in
    mere_rec (Σ (USym I) (h ↦ Id (USym G') t (usym_hom I G' i h))) (Mere R) (mere_isprop R)
      (u ↦ mere_rec (BookFiber (USym H) (USym I) (usym_hom H I p) (u .fst)) (Mere R) (mere_isprop R)
        (v ↦ mere R (v .fst,
          concat (USym G') t (usym_hom I G' i (u .fst)) (usym_hom H G' f (v .fst)) (u .snd)
            (concat (USym G') (usym_hom I G' i (u .fst)) (usym_hom I G' i (usym_hom H I p (v .fst))) (usym_hom H G' f (v .fst))
              (refl (usym_hom I G' i) (v .snd))
              (inverse (USym G') (usym_hom H G' f (v .fst)) (usym_hom I G' i (usym_hom H I p (v .fst)))
                (bridge_image_value_path H G' f (v .fst))))))
        (gepi_connected_fibers_usym_surjective H I p (image_projection_connected_fibers H G' f) (u .fst)))
      (mono_preserves_symmetries G' S (subgroup_to_mono G' S) (refl (subgroup_to_mono G' S)) t .fst r)

{` The blind generated subgroup of g with g^(b+1) = e is our ⟨g⟩. `}
def bridge_generated_subgroup_cyclic (b : Nat) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  (hyp : (k : Nat) → BookLt zero. k → BookLt k (suc. b) → Id (USym G) (usym_power G g k) (usym_unit G) → Empty)
  : Id (Subgroups G) (blind_generated_subgroup G g) (cyclic_subgroup_of_element b G g h hyp)
  ≔ let Z ≔ integer_group in
    let C ≔ cyclic_group (suc. b) in
    let ev ≔ circle_group_hom_ev constructed_circle G in
    let evC ≔ circle_group_hom_ev constructed_circle C in
    let f ≔ equiv_inverse_map (GroupHom Z G) (USym G) ev g in
    let gen ≔ cyclic_group_generator b in
    let r ≔ equiv_inverse_map (GroupHom Z C) (USym C) evC gen in
    let c ≔ cyclic_hom_of_element b G g h in
    let fc : Id (GroupHom Z G) f (group_hom_compose Z C G r c)
      ≔ equivalence_injective (GroupHom Z G) (USym G) ev f (group_hom_compose Z C G r c)
          (calc
            ev .map f = g by equiv_counit (GroupHom Z G) (USym G) ev g
            = usym_hom C G c gen by inverse (USym G) (usym_hom C G c gen) g (cyclic_hom_generator b G g h)
            = usym_hom C G c (evC .map r)
              by refl (usym_hom C G c) (inverse (USym C) (evC .map r) gen (equiv_counit (GroupHom Z C) (USym C) evC gen))
            = ev .map (group_hom_compose Z C G r c)
              by inverse (USym G) (ev .map (group_hom_compose Z C G r c)) (usym_hom C G c (evC .map r))
                   (circle_group_hom_ev_natural constructed_circle C G c r) ∎) in
    let m ≔ cyclic_mono_of_element b G g h hyp in
    let O ≔ cyclic_subgroup_of_element b G g h hyp in
    let I ≔ blind_generated_subgroup G g in
    let member_c : (x : USym C) → SubgroupHasMember G O (usym_hom C G c x)
      ≔ x ↦ mono_preserves_symmetries G O m (inverse (GroupMonos G) (subgroup_to_mono G O) m (mono_subgroup_roundtrip G m))
               (usym_hom C G c x) .snd
               (mere (Σ (USym C) (y ↦ Id (USym G) (usym_hom C G c x) (usym_hom C G c y))) (x, refl (usym_hom C G c x))) in
    let fz_member : (z : USym Z) → SubgroupHasMember G O (usym_hom Z G f z)
      ≔ z ↦ transport (USym G) (SubgroupHasMember G O) (usym_hom C G c (usym_hom Z C r z)) (usym_hom Z G f z)
               (inverse (USym G) (usym_hom Z G f z) (usym_hom C G c (usym_hom Z C r z))
                 (concat (USym G) (usym_hom Z G f z) (usym_hom Z G (group_hom_compose Z C G r c) z)
                   (usym_hom C G c (usym_hom Z C r z))
                   (refl ((k ↦ usym_hom Z G k z) : GroupHom Z G → USym G) fc)
                   (happly (USym Z) (_ ↦ USym G) (usym_hom Z G (group_hom_compose Z C G r c))
                     (x ↦ usym_hom C G c (usym_hom Z C r x)) (usym_hom_compose Z C G r c) z)))
               (member_c (usym_hom Z C r z)) in
    let le1 : SubgroupLe G I O
      ≔ t rt ↦ mere_rec (Σ (USym Z) (z ↦ Id (USym G) t (usym_hom Z G f z))) (SubgroupHasMember G O t)
            (subgroup_has_member_prop G O t)
            (u ↦ transport (USym G) (SubgroupHasMember G O) (usym_hom Z G f (u .fst)) t
                   (inverse (USym G) t (usym_hom Z G f (u .fst)) (u .snd)) (fz_member (u .fst)))
            (bridge_image_member_value Z G f t rt) in
    let gI : SubgroupHasMember G I g
      ≔ transport (USym G) (SubgroupHasMember G I) (ev .map f) g (equiv_counit (GroupHom Z G) (USym G) ev g)
          (bridge_image_member_of_value Z G f (circle_group_loop constructed_circle)) in
    let le2 : SubgroupLe G O I
      ≔ t rt ↦ mere_rec (Σ Nat (k ↦ Product (BookLt k (suc. b)) (Id (USym G) t (usym_power G g k))))
            (SubgroupHasMember G I t) (subgroup_has_member_prop G I t)
            (u ↦ transport (USym G) (SubgroupHasMember G I) (usym_power G g (u .fst)) t
                   (inverse (USym G) t (usym_power G g (u .fst)) (u .snd .snd))
                   (subgroup_has_member_power G I g gI (u .fst)))
            (cyclic_subgroup_member_power b G g h hyp t rt) in
    subgroup_le_antisym G I O le1 le2

{` The blind permutations are ours. `}
def bridge_fin6_c012 : (x : Fin 6) → Id (Fin 6) (blind_f6_c012 x) (fin6_a x)
  ≔ decision_bool_reflect ((x : Fin 6) → Id (Fin 6) (blind_f6_c012 x) (fin6_a x))
      (fin_forall_decidable 6 (x ↦ Id (Fin 6) (blind_f6_c012 x) (fin6_a x))
        (x ↦ fin_decidable_equality 6 (blind_f6_c012 x) (fin6_a x)))
      (refl (true. : Bool))

def bridge_fin6_c345 : (x : Fin 6) → Id (Fin 6) (blind_f6_c345 x) (fin6_b x)
  ≔ decision_bool_reflect ((x : Fin 6) → Id (Fin 6) (blind_f6_c345 x) (fin6_b x))
      (fin_forall_decidable 6 (x ↦ Id (Fin 6) (blind_f6_c345 x) (fin6_b x))
        (x ↦ fin_decidable_equality 6 (blind_f6_c345 x) (fin6_b x)))
      (refl (true. : Bool))

def bridge_fin6_double : (x : Fin 6) → Id (Fin 6) (blind_f6_c012 (blind_f6_c345 x)) (fin6_d x)
  ≔ decision_bool_reflect ((x : Fin 6) → Id (Fin 6) (blind_f6_c012 (blind_f6_c345 x)) (fin6_d x))
      (fin_forall_decidable 6 (x ↦ Id (Fin 6) (blind_f6_c012 (blind_f6_c345 x)) (fin6_d x))
        (x ↦ fin_decidable_equality 6 (blind_f6_c012 (blind_f6_c345 x)) (fin6_d x)))
      (refl (true. : Bool))

def bridge_sigma6_c012 : Id (USym (symmetric_group 6)) blind_sigma6_c012 sigma6_a
  ≔ permutation_symmetries_ext sigma6_set blind_sigma6_c012 sigma6_a bridge_fin6_c012

def bridge_sigma6_c345 : Id (USym (symmetric_group 6)) blind_sigma6_c345 sigma6_b
  ≔ permutation_symmetries_ext sigma6_set blind_sigma6_c345 sigma6_b bridge_fin6_c345

def bridge_sigma6_double
  : Id (USym (symmetric_group 6)) (usym_mul (symmetric_group 6) blind_sigma6_c012 blind_sigma6_c345) sigma6_d
  ≔ permutation_symmetries_ext sigma6_set (usym_mul (symmetric_group 6) blind_sigma6_c012 blind_sigma6_c345) sigma6_d
      (x ↦ concat (Fin 6) (permutation_action sigma6_set (usym_mul (symmetric_group 6) blind_sigma6_c012 blind_sigma6_c345) x)
             (blind_f6_c012 (blind_f6_c345 x)) (fin6_d x)
             (permutation_action_mul sigma6_set blind_sigma6_c012 blind_sigma6_c345 x)
             (bridge_fin6_double x))

def bridge_generated_path (g g' : USym (symmetric_group 6)) (e : Id (USym (symmetric_group 6)) g g')
  : Id (Subgroups (symmetric_group 6)) (blind_generated_subgroup (symmetric_group 6) g) (blind_generated_subgroup (symmetric_group 6) g')
  ≔ refl (blind_generated_subgroup (symmetric_group 6)) e

def bridge_sigma6_h123 : Id (Subgroups (symmetric_group 6)) blind_sigma6_h123 sigma6_a_subgroup
  ≔ concat (Subgroups (symmetric_group 6)) blind_sigma6_h123 (blind_generated_subgroup (symmetric_group 6) sigma6_a) sigma6_a_subgroup
      (bridge_generated_path blind_sigma6_c012 sigma6_a bridge_sigma6_c012)
      (bridge_generated_subgroup_cyclic (suc. (suc. zero.)) (symmetric_group 6) sigma6_a (sigma6_cube fin6_a fin6_a_cube)
        (sigma6_cyclic_hyp fin6_a fin6_a_cube fin6_zero (refl (false. : Bool))))

def bridge_sigma6_h456 : Id (Subgroups (symmetric_group 6)) blind_sigma6_h456 sigma6_b_subgroup
  ≔ concat (Subgroups (symmetric_group 6)) blind_sigma6_h456 (blind_generated_subgroup (symmetric_group 6) sigma6_b) sigma6_b_subgroup
      (bridge_generated_path blind_sigma6_c345 sigma6_b bridge_sigma6_c345)
      (bridge_generated_subgroup_cyclic (suc. (suc. zero.)) (symmetric_group 6) sigma6_b (sigma6_cube fin6_b fin6_b_cube)
        (sigma6_cyclic_hyp fin6_b fin6_b_cube fin6_three (refl (false. : Bool))))

def bridge_sigma6_hdouble : Id (Subgroups (symmetric_group 6)) blind_sigma6_hdouble sigma6_d_subgroup
  ≔ concat (Subgroups (symmetric_group 6)) blind_sigma6_hdouble (blind_generated_subgroup (symmetric_group 6) sigma6_d) sigma6_d_subgroup
      (bridge_generated_path (usym_mul (symmetric_group 6) blind_sigma6_c012 blind_sigma6_c345) sigma6_d bridge_sigma6_double)
      (bridge_generated_subgroup_cyclic (suc. (suc. zero.)) (symmetric_group 6) sigma6_d (sigma6_cube fin6_d fin6_d_cube)
        (sigma6_cyclic_hyp fin6_d fin6_d_cube fin6_zero (refl (false. : Bool))))

{` Litmus: ⟨(1 2 3)⟩ has order 3. `}
def bridge_sigma6_h123_order : blind_sigma6_h123_order
  ≔ let G ≔ symmetric_group 6 in
    let hA ≔ cyclic_prime_subgroup_finite (suc. (suc. zero.)) nat_prime_three G sigma6_a (sigma6_cube fin6_a fin6_a_cube)
      (sigma6_ne fin6_a fin6_a_cube fin6_zero (refl (false. : Bool))) in
    transport (Subgroups G) (S ↦ BlindHasOrder (subgroup_group G S) 3) sigma6_a_subgroup blind_sigma6_h123
      (inverse (Subgroups G) blind_sigma6_h123 sigma6_a_subgroup bridge_sigma6_h123)
      (hA, cyclic_prime_subgroup_card (suc. (suc. zero.)) nat_prime_three G sigma6_a (sigma6_cube fin6_a fin6_a_cube)
             (sigma6_ne fin6_a fin6_a_cube fin6_zero (refl (false. : Bool))) hA)

{` ⟨(0 1 2)⟩ is not conjugate to ⟨(0 1 2)(3 4 5)⟩: a conjugate g a g⁻¹ ≠ e
   of a = (0 1 2) fixes g(3), and no element ≠ e of ⟨d⟩ has a fixed point. `}
def bridge_perm_inv_left (g : USym (symmetric_group 6)) (y : Fin 6)
  : Id (Fin 6) (permutation_action sigma6_set (usym_inv (symmetric_group 6) g) (permutation_action sigma6_set g y)) y
  ≔ let G ≔ symmetric_group 6 in let S ≔ sigma6_set in
    calc
      permutation_action S (usym_inv G g) (permutation_action S g y)
      = permutation_action S (usym_mul G (usym_inv G g) g) y
        by inverse (Fin 6) (permutation_action S (usym_mul G (usym_inv G g) g) y)
             (permutation_action S (usym_inv G g) (permutation_action S g y)) (permutation_action_mul S (usym_inv G g) g y)
      = permutation_action S (usym_unit G) y
        by refl ((s ↦ permutation_action S s y) : USym G → Fin 6)
             (concat_inverse_right (BG G .carrier) (shape G) (shape G) g)
      = y by permutation_action_unit S y ∎

def bridge_sigma6_a_not_conj_d (g : USym (symmetric_group 6))
  (e : Id (Subgroups (symmetric_group 6)) (subgroup_conjugate (symmetric_group 6) g sigma6_a_subgroup) sigma6_d_subgroup) : Empty
  ≔ let G ≔ symmetric_group 6 in let S ≔ sigma6_set in
    let A ≔ sigma6_a_subgroup in let X ≔ A .gset in let x ≔ A .point in let Y ≔ gset_underlying G X in
    let a ≔ sigma6_a in let gi ≔ usym_inv G g in
    let t ≔ usym_mul G g (usym_mul G a gi) in
    let T ≔ subgroup_conjugate G g A in
    let act : (z : Fin 6) → Id (Fin 6) (permutation_action S t z)
                (permutation_action S g (permutation_action S a (permutation_action S gi z)))
      ≔ z ↦ concat (Fin 6) (permutation_action S t z) (permutation_action S g (permutation_action S (usym_mul G a gi) z))
               (permutation_action S g (permutation_action S a (permutation_action S gi z)))
               (permutation_action_mul S g (usym_mul G a gi) z)
               (refl (permutation_action S g) (permutation_action_mul S a gi z)) in
    let r : SymSubgroupMember G T t
      ≔ calc
          gset_usym_act G X t (gset_usym_act G X g x)
          = gset_usym_act G X g (gset_usym_act G X (usym_mul G a gi) (gset_usym_act G X g x))
            by gset_act_mul G X g (usym_mul G a gi) (gset_usym_act G X g x)
          = gset_usym_act G X g (gset_usym_act G X a (gset_usym_act G X gi (gset_usym_act G X g x)))
            by refl (gset_usym_act G X g) (gset_act_mul G X a gi (gset_usym_act G X g x))
          = gset_usym_act G X g (gset_usym_act G X a x)
            by refl (u ↦ gset_usym_act G X g (gset_usym_act G X a u)) (gset_act_inv_left G X g x)
          = gset_usym_act G X g x
            by refl (gset_usym_act G X g) (sigma6_cyclic_generator_member fin6_a fin6_a_cube fin6_zero (refl (false. : Bool))) ∎ in
    let ne : Not (Id (USym G) t (usym_unit G))
      ≔ q ↦
        let y ≔ fin6_zero in
        let gy : Id (Fin 6) (permutation_action S g (fin6_a y)) (permutation_action S g y)
          ≔ calc
              permutation_action S g (fin6_a y)
              = permutation_action S g (permutation_action S a (permutation_action S gi (permutation_action S g y)))
                by refl (u ↦ permutation_action S g (fin6_a u)) (inverse (Fin 6) (permutation_action S gi (permutation_action S g y)) y
                     (bridge_perm_inv_left g y))
              = permutation_action S t (permutation_action S g y)
                by inverse (Fin 6) (permutation_action S t (permutation_action S g y))
                     (permutation_action S g (permutation_action S a (permutation_action S gi (permutation_action S g y))))
                     (act (permutation_action S g y))
              = permutation_action S (usym_unit G) (permutation_action S g y)
                by refl ((s ↦ permutation_action S s (permutation_action S g y)) : USym G → Fin 6) q
              = permutation_action S g y by permutation_action_unit S (permutation_action S g y) ∎ in
        let ay : Id (Fin 6) (fin6_a y) y
          ≔ concat (Fin 6) (fin6_a y) (permutation_action S gi (permutation_action S g (fin6_a y))) y
              (inverse (Fin 6) (permutation_action S gi (permutation_action S g (fin6_a y))) (fin6_a y) (bridge_perm_inv_left g (fin6_a y)))
              (concat (Fin 6) (permutation_action S gi (permutation_action S g (fin6_a y))) (permutation_action S gi (permutation_action S g y)) y
                (refl (permutation_action S gi) gy) (bridge_perm_inv_left g y)) in
        nat_decision_false_reflect (Id (Fin 6) (fin6_a y) y) (fin_decidable_equality 6 (fin6_a y) y) (refl (false. : Bool)) ay in
    let fx : Id (Fin 6) (permutation_action S t (permutation_action S g fin6_three)) (permutation_action S g fin6_three)
      ≔ concat (Fin 6) (permutation_action S t (permutation_action S g fin6_three))
          (permutation_action S g (permutation_action S a (permutation_action S gi (permutation_action S g fin6_three))))
          (permutation_action S g fin6_three)
          (act (permutation_action S g fin6_three))
          (refl (u ↦ permutation_action S g (fin6_a u)) (bridge_perm_inv_left g fin6_three)) in
    sigma6_d_subgroup_not_point_fixing T t r ne (permutation_action S g fin6_three) fx e

def bridge_sigma6_h123_h456_not_conjugate_corrected : blind_sigma6_h123_h456_not_conjugate_corrected
  ≔ let G ≔ symmetric_group 6 in
    (transport (Subgroups G) (S ↦ BlindConjugate G S blind_sigma6_h456) sigma6_a_subgroup blind_sigma6_h123
       (inverse (Subgroups G) blind_sigma6_h123 sigma6_a_subgroup bridge_sigma6_h123)
       (transport (Subgroups G) (S ↦ BlindConjugate G sigma6_a_subgroup S) sigma6_b_subgroup blind_sigma6_h456
         (inverse (Subgroups G) blind_sigma6_h456 sigma6_b_subgroup bridge_sigma6_h456)
         (bridge_conjugate_from G sigma6_a_subgroup sigma6_b_subgroup
           (mere (Σ (USym G) (g ↦ Id (Subgroups G) (subgroup_conjugate G g sigma6_a_subgroup) sigma6_b_subgroup))
             (sigma6_g, sigma6_cyclic_subgroups_conjugate)))),
     c ↦ mere_rec (Σ (USym G) (g ↦ Id (Subgroups G) (subgroup_conjugate G g sigma6_a_subgroup) sigma6_d_subgroup)) Empty empty_prop
       (u ↦ bridge_sigma6_a_not_conj_d (u .fst) (u .snd))
       (bridge_conjugate_to G sigma6_a_subgroup sigma6_d_subgroup
         (transport (Subgroups G) (S ↦ BlindConjugate G sigma6_a_subgroup S) blind_sigma6_hdouble sigma6_d_subgroup bridge_sigma6_hdouble
           (transport (Subgroups G) (S ↦ BlindConjugate G S blind_sigma6_hdouble) blind_sigma6_h123 sigma6_a_subgroup bridge_sigma6_h123 c))))

{` The literal sentence ("⟨(1 2 3)⟩ is not conjugate to ⟨(4 5 6)⟩") is refuted. `}
def bridge_sigma6_h123_h456_not_conjugate_refuted (h : blind_sigma6_h123_h456_not_conjugate) : Empty
  ≔ h (bridge_sigma6_h123_h456_not_conjugate_corrected .fst)
