export "1010-usym-powers"
export "508-stabilizer-subgroups"

{` Chapter 10 (fingp.tex), supporting material for thm:cauchys: homomorphisms
   out of the cyclic group C_n = cyclic_group n, n = b+1 (BC_n ≡ (Cyc_n, pt_n),
   module 404), and cyclic subgroups generated by symmetries of finite order.

   Generators. The book's chapter 3 uses sigma_n ≔ (s⁻¹, !) (cyc_generator b,
   module 180) in prop:ump-cycn-into-groupoids; ex:cyclicgroups says that all
   symmetries of C_n are obtained from 1, i.e. from (s, !). We call the latter
   cyclic_group_generator b ≔ sigma_n⁻¹; it evaluates to 1 at 0, and it is the
   symmetry cycle_group_generator (principal_cycle n) of module 417 (see
   cyclic_group_generator_component, stated for the unfolded term because
   module 417 is not imported here).

   Homomorphisms. For g : USym G with g^n = e, cyclic_hom_of_element is the
   pointed map BC_n →* BG obtained from the universal property of Cyc_n
   (module 182) applied to (sh_G, g⁻¹, !); its pointing path is the centre of
   the contractible lift data at pt_n, and the coherence of the lift gives
   Ω(f)(sigma_n) = g⁻¹, hence f(generator) = g and f(generator^k) = g^k.
   Evaluation at 0 (cyc_loop_equiv, module 180) identifies USym C_n with Z/n. `}

def cyclic_group_generator (b : Nat) : USym (cyclic_group (suc. b))
  ≔ usym_inv (cyclic_group (suc. b)) (cyc_generator b)

{` Multiplying by the generator adds 1 to the value at 0. `}
def cyclic_eval_mul_generator (b : Nat) (t : USym (cyclic_group (suc. b)))
  : Id (Remainder (suc. b)) (cyc_loop_equiv b .map (usym_mul (cyclic_group (suc. b)) (cyclic_group_generator b) t))
      (modular_successor b (cyc_loop_equiv b .map t))
  ≔ let C ≔ CycleComponent (suc. b) in let pt ≔ principal_component_point (suc. b) in
    let s ≔ cyc_generator b in
    let t' ≔ concat C pt pt pt t (inverse C pt pt s) in
    let E ≔ ((x ↦ cyc_loop_equiv b .map x) : Id C pt pt → Remainder (suc. b)) in
    calc
      E t' = modular_successor b (modular_predecessor b (E t'))
        by inverse (Remainder (suc. b)) (modular_successor b (modular_predecessor b (E t'))) (E t')
          (modular_successor_predecessor b (E t'))
      = modular_successor b (E (concat C pt pt pt t' s))
        by refl (modular_successor b)
          (inverse (Remainder (suc. b)) (E (concat C pt pt pt t' s)) (modular_predecessor b (E t')) (cyc_loop_right b t'))
      = modular_successor b (E t)
        by refl ((x ↦ modular_successor b (E x)) : Id C pt pt → Remainder (suc. b)) (concat_cancel_final_inverse C pt t s) ∎

def cyclic_group_generator_eval (b : Nat)
  : Id (Remainder (suc. b)) (cyc_loop_equiv b .map (cyclic_group_generator b))
      (modular_successor b (remainder_at b zero. star.))
  ≔ let C ≔ CycleComponent (suc. b) in let pt ≔ principal_component_point (suc. b) in
    let E ≔ ((x ↦ cyc_loop_equiv b .map x) : Id C pt pt → Remainder (suc. b)) in
    calc
      E (cyclic_group_generator b)
      = E (usym_mul (cyclic_group (suc. b)) (cyclic_group_generator b) (usym_unit (cyclic_group (suc. b))))
        by refl E (inverse (Id C pt pt) (concat C pt pt pt (refl pt) (cyclic_group_generator b)) (cyclic_group_generator b)
          (concat_1p C pt pt (cyclic_group_generator b)))
      = modular_successor b (E (refl pt)) by cyclic_eval_mul_generator b (usym_unit (cyclic_group (suc. b)))
      = modular_successor b (remainder_at b zero. star.) by refl (modular_successor b) (cyc_loop_refl b) ∎

{` The symmetry (s, !) of module 417 (cycle_group_generator (principal_cycle n),
   which unfolds to the term below) is the generator. `}
def cyclic_group_generator_component (b : Nat)
  : Id (USym (cyclic_group (suc. b)))
      (component_path Cycles (principal_cycle (suc. b)) (component_point Cycles (principal_cycle (suc. b)))
        (component_point Cycles (principal_cycle (suc. b))) (cycle_generating_loop (principal_cycle (suc. b))))
      (cyclic_group_generator b)
  ≔ let c ≔ principal_cycle (suc. b) in
    let t ≔ component_path Cycles c (component_point Cycles c) (component_point Cycles c) (cycle_generating_loop c) in
    equivalence_injective (USym (cyclic_group (suc. b))) (Remainder (suc. b)) (cyc_loop_equiv b) t (cyclic_group_generator b)
      (concat (Remainder (suc. b)) (cyc_loop_equiv b .map t) (modular_successor b (remainder_at b zero. star.))
        (cyc_loop_equiv b .map (cyclic_group_generator b))
        (cycle_generating_loop_action c (remainder_at b zero. star.))
        (inverse (Remainder (suc. b)) (cyc_loop_equiv b .map (cyclic_group_generator b))
          (modular_successor b (remainder_at b zero. star.)) (cyclic_group_generator_eval b)))

{` The generator^k evaluates to s^k(0) = k (k < n). `}
def cyclic_generator_power_eval (b k : Nat)
  : Id (Remainder (suc. b))
      (cyc_loop_equiv b .map (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k))
      (iterate (Remainder (suc. b)) (modular_successor b) k (remainder_at b zero. star.))
  ≔ match k [
  | zero. ↦ cyc_loop_refl b
  | suc. k ↦ concat (Remainder (suc. b))
      (cyc_loop_equiv b .map (usym_mul (cyclic_group (suc. b)) (cyclic_group_generator b)
        (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k)))
      (modular_successor b (cyc_loop_equiv b .map (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k)))
      (modular_successor b (iterate (Remainder (suc. b)) (modular_successor b) k (remainder_at b zero. star.)))
      (cyclic_eval_mul_generator b (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k))
      (refl (modular_successor b) (cyclic_generator_power_eval b k)) ]

def cyclic_generator_power_eval_below (b k : Nat) (hk : Le k b)
  : Id (Remainder (suc. b))
      (cyc_loop_equiv b .map (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k)) (remainder_at b k hk)
  ≔ concat (Remainder (suc. b))
      (cyc_loop_equiv b .map (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k))
      (iterate (Remainder (suc. b)) (modular_successor b) k (remainder_at b zero. star.)) (remainder_at b k hk)
      (cyclic_generator_power_eval b k) (modular_successor_iterate b k hk)

{` Every symmetry of C_n is generator^k for some k < n (namely its value at 0). `}
def cyclic_symmetry_power_index (b : Nat) (t : USym (cyclic_group (suc. b)))
  : Σ Nat (k ↦ Product (BookLt k (suc. b))
      (Id (USym (cyclic_group (suc. b))) (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k) t))
  ≔ let r ≔ cyc_loop_equiv b .map t in
    let hk ≔ lt_from_book (r .fst) (suc. b) (r .snd) in
    let gk ≔ usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) (r .fst) in
    (r .fst, (r .snd,
      equivalence_injective (USym (cyclic_group (suc. b))) (Remainder (suc. b)) (cyc_loop_equiv b) gk t
        (concat (Remainder (suc. b)) (cyc_loop_equiv b .map gk) (remainder_at b (r .fst) hk) r
          (cyclic_generator_power_eval_below b (r .fst) hk)
          (remainder_equal (suc. b) (remainder_at b (r .fst) hk) r (refl (r .fst))))))

{` generator^n = e, and generator^k ≠ e for 0 < k < n: n is its order. `}
def cyclic_group_generator_order (b : Nat)
  : Id (USym (cyclic_group (suc. b))) (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) (suc. b))
      (usym_unit (cyclic_group (suc. b)))
  ≔ let G ≔ cyclic_group (suc. b) in let s ≔ cyc_generator b in
    calc
      usym_power G (usym_inv G s) (suc. b) = usym_inv G (usym_power G s (suc. b)) by usym_power_inv G s (suc. b)
      = usym_inv G (usym_unit G)
        by refl (usym_inv G) (inverse (USym G) (usym_unit G) (usym_power G s (suc. b)) (cyc_generator_order b))
      = usym_unit G by inverse_refl (CycleComponent (suc. b)) (principal_component_point (suc. b)) ∎

def cyclic_group_generator_powers_nontrivial (b k : Nat) (hk0 : BookLt zero. k) (hk : BookLt k (suc. b))
  : Id (USym (cyclic_group (suc. b))) (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k)
      (usym_unit (cyclic_group (suc. b))) → Empty
  ≔ e ↦
    let G ≔ cyclic_group (suc. b) in
    let hb ≔ lt_from_book k (suc. b) hk in
    let k0 : Id Nat k zero. ≔ calc
        k = cyc_loop_equiv b .map (usym_power G (cyclic_group_generator b) k) .fst
          by inverse Nat (cyc_loop_equiv b .map (usym_power G (cyclic_group_generator b) k) .fst) k
            (cyclic_generator_power_eval_below b k hb .fst)
        = cyc_loop_equiv b .map (usym_unit G) .fst
          by refl ((t ↦ cyc_loop_equiv b .map t .fst) : USym G → Nat) e
        = zero. by cyc_loop_refl b .fst ∎ in
    hk0 .snd .fst (concat Nat (hk0 .fst) k zero. (hk0 .snd .snd) k0)

def cyclic_group_generator_least_period (b : Nat)
  : IsMinimum (UsymPositivePeriod (cyclic_group (suc. b)) (cyclic_group_generator b)) (suc. b)
  ≔ usym_minimum_of_nontrivial_below (cyclic_group (suc. b)) (cyclic_group_generator b) (suc. b)
      (lt_to_book zero. (suc. b) star.) (cyclic_group_generator_order b) (cyclic_group_generator_powers_nontrivial b)

{` The index k < n with t = generator^k is unique. `}
def cyclic_symmetry_power_unique (b : Nat) (t : USym (cyclic_group (suc. b))) (k : Nat) (hk : BookLt k (suc. b))
  (e : Id (USym (cyclic_group (suc. b))) (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k) t)
  : Id Nat k (cyclic_symmetry_power_index b t .fst)
  ≔ let G ≔ cyclic_group (suc. b) in let w ≔ cyclic_symmetry_power_index b t in
    usym_power_injective_below G (cyclic_group_generator b) (suc. b) (cyclic_group_generator_powers_nontrivial b)
      k (w .fst) hk (w .snd .fst)
      (concat (USym G) (usym_power G (cyclic_group_generator b) k) t (usym_power G (cyclic_group_generator b) (w .fst))
        e (inverse (USym G) (usym_power G (cyclic_group_generator b) (w .fst)) t (w .snd .snd)))

{` The homomorphism C_n → G sending the generator to g, for g^n = e. `}
def cyclic_hom_data (b : Nat) (G : Group) (g : USym G) (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  : CycSymmetryData b (BG G .carrier)
  ≔ (shape G, (usym_inv G g,
      inverse (USym G) (usym_power G (usym_inv G g) (suc. b)) (usym_unit G)
        (calc
          usym_power G (usym_inv G g) (suc. b) = usym_inv G (usym_power G g (suc. b)) by usym_power_inv G g (suc. b)
          = usym_inv G (usym_unit G) by refl (usym_inv G) h
          = usym_unit G by inverse_refl (BG G .carrier) (shape G) ∎)))

def cyclic_hom_function (b : Nat) (G : Group) (g : USym G) (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  : CycleComponent (suc. b) → BG G .carrier
  ≔ cyc_extension b (BG G .carrier) (bg_groupoid G) (cyclic_hom_data b G g h)

def cyclic_hom_point (b : Nat) (G : Group) (g : USym G) (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  : Id (BG G .carrier) (shape G) (cyclic_hom_function b G g h (principal_component_point (suc. b)))
  ≔ cyc_lift_contractible b (BG G .carrier) (bg_groupoid G) (shape G) (usym_inv G g) (cyclic_hom_data b G g h .snd .snd)
      (principal_component_point (suc. b)) .center .snd .fst (refl (principal_component_point (suc. b)))

def cyclic_hom_of_element (b : Nat) (G : Group) (g : USym G) (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  : GroupHom (cyclic_group (suc. b)) G
  ≔ mkhom (cyclic_group (suc. b)) G (cyclic_hom_function b G g h, cyclic_hom_point b G g h)

{` Ω f (sigma_n) = g⁻¹, from the coherence of the lift (cyc_lift_coherence). `}
def cyclic_hom_sigma (b : Nat) (G : Group) (g : USym G) (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  : Id (USym G) (usym_hom (cyclic_group (suc. b)) G (cyclic_hom_of_element b G g h) (cyc_generator b)) (usym_inv G g)
  ≔ let A ≔ BG G .carrier in let a ≔ shape G in
    let F ≔ cyclic_hom_function b G g h in let pt ≔ principal_component_point (suc. b) in
    let P ≔ cyclic_hom_point b G g h in let s ≔ usym_inv G g in
    let l ≔ refl F (cyc_generator b) in
    calc
      concat A a (F pt) a P (concat A (F pt) (F pt) a l (inverse A a (F pt) P))
      = concat A a (F pt) a (concat A a (F pt) (F pt) P l) (inverse A a (F pt) P)
        by inverse (Id A a a) (concat A a (F pt) a (concat A a (F pt) (F pt) P l) (inverse A a (F pt) P))
          (concat A a (F pt) a P (concat A (F pt) (F pt) a l (inverse A a (F pt) P)))
          (concat_assoc A a (F pt) (F pt) a P l (inverse A a (F pt) P))
      = concat A a (F pt) a (concat A a a (F pt) s P) (inverse A a (F pt) P)
        by refl ((r ↦ concat A a (F pt) a r (inverse A a (F pt) P)) : Id A a (F pt) → Id A a a)
          (cyc_lift_coherence b A (bg_groupoid G) (cyclic_hom_data b G g h))
      = concat A a a a s (concat A a (F pt) a P (inverse A a (F pt) P))
        by concat_assoc A a a (F pt) a s P (inverse A a (F pt) P)
      = concat A a a a s (refl a) by refl (concat A a a a s) (concat_inverse_right A a (F pt) P)
      = s by concat_p1 A a a s ∎

def cyclic_hom_generator (b : Nat) (G : Group) (g : USym G) (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  : Id (USym G) (usym_hom (cyclic_group (suc. b)) G (cyclic_hom_of_element b G g h) (cyclic_group_generator b)) g
  ≔ let C ≔ cyclic_group (suc. b) in let f ≔ cyclic_hom_of_element b G g h in
    calc
      usym_hom C G f (usym_inv C (cyc_generator b)) = usym_inv G (usym_hom C G f (cyc_generator b))
        by usym_hom_inv C G f (cyc_generator b)
      = usym_inv G (usym_inv G g) by refl (usym_inv G) (cyclic_hom_sigma b G g h)
      = g by inverse_inverse (BG G .carrier) (shape G) (shape G) g ∎

def cyclic_hom_generator_power (b : Nat) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G)) (k : Nat)
  : Id (USym G) (usym_hom (cyclic_group (suc. b)) G (cyclic_hom_of_element b G g h)
      (usym_power (cyclic_group (suc. b)) (cyclic_group_generator b) k)) (usym_power G g k)
  ≔ let C ≔ cyclic_group (suc. b) in let f ≔ cyclic_hom_of_element b G g h in
    concat (USym G) (usym_hom C G f (usym_power C (cyclic_group_generator b) k))
      (usym_power G (usym_hom C G f (cyclic_group_generator b)) k) (usym_power G g k)
      (usym_hom_power C G f (cyclic_group_generator b) k)
      (refl ((x ↦ usym_power G x k) : USym G → USym G) (cyclic_hom_generator b G g h))

{` If g^k ≠ e for 0 < k < n, the homomorphism is a monomorphism (USym of it
   is injective, hence an embedding since USym G is a set). `}
def cyclic_hom_injective (b : Nat) (G : Group) (g : USym G) (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  (hyp : (k : Nat) → BookLt zero. k → BookLt k (suc. b) → Id (USym G) (usym_power G g k) (usym_unit G) → Empty)
  : PathReflecting (USym (cyclic_group (suc. b))) (USym G) (usym_hom (cyclic_group (suc. b)) G (cyclic_hom_of_element b G g h))
  ≔ t t' e ↦
    let C ≔ cyclic_group (suc. b) in let f ≔ cyclic_hom_of_element b G g h in
    let w ≔ cyclic_symmetry_power_index b t in let w' ≔ cyclic_symmetry_power_index b t' in
    let gen ≔ cyclic_group_generator b in
    let same : Id (USym G) (usym_power G g (w .fst)) (usym_power G g (w' .fst)) ≔ calc
        usym_power G g (w .fst) = usym_hom C G f (usym_power C gen (w .fst))
          by inverse (USym G) (usym_hom C G f (usym_power C gen (w .fst))) (usym_power G g (w .fst))
            (cyclic_hom_generator_power b G g h (w .fst))
        = usym_hom C G f t by refl (usym_hom C G f) (w .snd .snd)
        = usym_hom C G f t' by e
        = usym_hom C G f (usym_power C gen (w' .fst))
          by refl (usym_hom C G f) (inverse (USym C) (usym_power C gen (w' .fst)) t' (w' .snd .snd))
        = usym_power G g (w' .fst) by cyclic_hom_generator_power b G g h (w' .fst) ∎ in
    calc
      t = usym_power C gen (w .fst) by inverse (USym C) (usym_power C gen (w .fst)) t (w .snd .snd)
      = usym_power C gen (w' .fst)
        by refl (usym_power C gen)
          (usym_power_injective_below G g (suc. b) hyp (w .fst) (w' .fst) (w .snd .fst) (w' .snd .fst) same)
      = t' by w' .snd .snd ∎

def cyclic_hom_of_element_mono (b : Nat) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  (hyp : (k : Nat) → BookLt zero. k → BookLt k (suc. b) → Id (USym G) (usym_power G g k) (usym_unit G) → Empty)
  : IsGroupMono (cyclic_group (suc. b)) G (cyclic_hom_of_element b G g h)
  ≔ path_reflecting_set_embedding (USym (cyclic_group (suc. b))) (USym G) (usym_set G)
      (usym_hom (cyclic_group (suc. b)) G (cyclic_hom_of_element b G g h)) (cyclic_hom_injective b G g h hyp)

{` The cyclic subgroup generated by g, as an element of Mono(G) and of Sub(G)
   (via E = mono_to_subgroup), with underlying group C_n. `}
def cyclic_mono_of_element (b : Nat) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  (hyp : (k : Nat) → BookLt zero. k → BookLt k (suc. b) → Id (USym G) (usym_power G g k) (usym_unit G) → Empty)
  : GroupMonos G
  ≔ (cyclic_group (suc. b), (cyclic_hom_of_element b G g h, cyclic_hom_of_element_mono b G g h hyp))

def cyclic_subgroup_of_element (b : Nat) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  (hyp : (k : Nat) → BookLt zero. k → BookLt k (suc. b) → Id (USym G) (usym_power G g k) (usym_unit G) → Empty)
  : Subgroups G
  ≔ mono_to_subgroup G (cyclic_mono_of_element b G g h hyp)

def cyclic_subgroup_group_path (b : Nat) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  (hyp : (k : Nat) → BookLt zero. k → BookLt k (suc. b) → Id (USym G) (usym_power G g k) (usym_unit G) → Empty)
  : Id Group (subgroup_group G (cyclic_subgroup_of_element b G g h hyp)) (cyclic_group (suc. b))
  ≔ mono_subgroup_group_path G (cyclic_mono_of_element b G g h hyp)

{` The same with the book's literal C_n = Aut_Cyc(Fin n, s) (cyclic_group_fin). `}
def cyclic_subgroup_group_fin_path (b : Nat) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G))
  (hyp : (k : Nat) → BookLt zero. k → BookLt k (suc. b) → Id (USym G) (usym_power G g k) (usym_unit G) → Empty)
  : Id Group (subgroup_group G (cyclic_subgroup_of_element b G g h hyp)) (cyclic_group_fin b)
  ≔ concat Group (subgroup_group G (cyclic_subgroup_of_element b G g h hyp)) (cyclic_group (suc. b)) (cyclic_group_fin b)
      (cyclic_subgroup_group_path b G g h hyp)
      (inverse Group (cyclic_group_fin b) (cyclic_group (suc. b)) (cyclic_group_fin_path b))

{` Elements of finite order: if n is the least positive period of g, the
   cyclic subgroup generated by g has underlying group C_n. `}
def cyclic_order_mono (b : Nat) (G : Group) (g : USym G) (min : IsMinimum (UsymPositivePeriod G g) (suc. b))
  : IsGroupMono (cyclic_group (suc. b)) G (cyclic_hom_of_element b G g (min .fst .snd))
  ≔ cyclic_hom_of_element_mono b G g (min .fst .snd) (usym_minimum_nontrivial_below G g (suc. b) min)

def cyclic_subgroup_of_order (b : Nat) (G : Group) (g : USym G) (min : IsMinimum (UsymPositivePeriod G g) (suc. b))
  : Subgroups G
  ≔ cyclic_subgroup_of_element b G g (min .fst .snd) (usym_minimum_nontrivial_below G g (suc. b) min)

def cyclic_subgroup_of_order_group_path (b : Nat) (G : Group) (g : USym G)
  (min : IsMinimum (UsymPositivePeriod G g) (suc. b))
  : Id Group (subgroup_group G (cyclic_subgroup_of_order b G g min)) (cyclic_group (suc. b))
  ≔ cyclic_subgroup_group_path b G g (min .fst .snd) (usym_minimum_nontrivial_below G g (suc. b) min)

{` The prime case (thm:cauchys): p = b+1 prime, g^p = e and g ≠ e give a
   cyclic subgroup of G with underlying group C_p. `}
def cyclic_prime_mono (b : Nat) (hp : NatIsPrime (suc. b)) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G)) (ne : Id (USym G) g (usym_unit G) → Empty)
  : IsGroupMono (cyclic_group (suc. b)) G (cyclic_hom_of_element b G g h)
  ≔ cyclic_hom_of_element_mono b G g h (prime_order_powers_nontrivial (suc. b) hp G g h ne)

def cyclic_prime_subgroup (b : Nat) (hp : NatIsPrime (suc. b)) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G)) (ne : Id (USym G) g (usym_unit G) → Empty)
  : Subgroups G
  ≔ cyclic_subgroup_of_element b G g h (prime_order_powers_nontrivial (suc. b) hp G g h ne)

def cyclic_prime_subgroup_group_path (b : Nat) (hp : NatIsPrime (suc. b)) (G : Group) (g : USym G)
  (h : Id (USym G) (usym_power G g (suc. b)) (usym_unit G)) (ne : Id (USym G) g (usym_unit G) → Empty)
  : Id Group (subgroup_group G (cyclic_prime_subgroup b hp G g h ne)) (cyclic_group (suc. b))
  ≔ cyclic_subgroup_group_path b G g h (prime_order_powers_nontrivial (suc. b) hp G g h ne)

{` Litmus checks. In C_4 the generator evaluates to 1 and generator^2 to 2;
   g = generator^2 has g^2 = e and g ≠ e, so the homomorphism C_2 → C_4
   sending the generator to g is a monomorphism, sends the generator to the
   symmetry with value 2, and gives a subgroup of C_4 with underlying group C_2. `}
def cyclic_hom_litmus_generator_value
  : Id Nat (cyc_loop_equiv (suc. (suc. (suc. zero.))) .map (cyclic_group_generator (suc. (suc. (suc. zero.)))) .fst)
      (suc. zero.)
  ≔ cyclic_group_generator_eval (suc. (suc. (suc. zero.))) .fst

def cyclic_four_square : USym (cyclic_group (suc. (suc. (suc. (suc. zero.)))))
  ≔ usym_power (cyclic_group (suc. (suc. (suc. (suc. zero.))))) (cyclic_group_generator (suc. (suc. (suc. zero.))))
      (suc. (suc. zero.))

def cyclic_four_square_order
  : Id (USym (cyclic_group (suc. (suc. (suc. (suc. zero.))))))
      (usym_power (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square (suc. (suc. zero.)))
      (usym_unit (cyclic_group (suc. (suc. (suc. (suc. zero.))))))
  ≔ let C4 ≔ cyclic_group (suc. (suc. (suc. (suc. zero.)))) in
    let two : Nat ≔ suc. (suc. zero.) in
    concat (USym C4) (usym_power C4 cyclic_four_square two)
      (usym_power C4 (cyclic_group_generator (suc. (suc. (suc. zero.)))) (mul two two)) (usym_unit C4)
      (inverse (USym C4) (usym_power C4 (cyclic_group_generator (suc. (suc. (suc. zero.)))) (mul two two))
        (usym_power C4 cyclic_four_square two)
        (usym_power_mul C4 (cyclic_group_generator (suc. (suc. (suc. zero.)))) two two))
      (cyclic_group_generator_order (suc. (suc. (suc. zero.))))

def cyclic_four_square_nontrivial (k : Nat) (hk0 : BookLt zero. k) (hk : BookLt k (suc. (suc. zero.)))
  : Id (USym (cyclic_group (suc. (suc. (suc. (suc. zero.)))))) (usym_power (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square k)
      (usym_unit (cyclic_group (suc. (suc. (suc. (suc. zero.)))))) → Empty
  ≔ match k [
  | zero. ↦ _ ↦ hk0 .snd .fst (hk0 .snd .snd)
  | suc. zero. ↦ e ↦ cyclic_group_generator_powers_nontrivial (suc. (suc. (suc. zero.))) (suc. (suc. zero.))
      (lt_to_book zero. (suc. (suc. zero.)) star.) (lt_to_book (suc. (suc. zero.)) (suc. (suc. (suc. (suc. zero.)))) star.)
      (concat (USym (cyclic_group (suc. (suc. (suc. (suc. zero.)))))) cyclic_four_square
        (usym_power (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square (suc. zero.))
        (usym_unit (cyclic_group (suc. (suc. (suc. (suc. zero.))))))
        (inverse (USym (cyclic_group (suc. (suc. (suc. (suc. zero.))))))
          (usym_power (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square (suc. zero.)) cyclic_four_square
          (usym_power_one (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square))
        e)
  | suc. (suc. k) ↦ _ ↦ absurd Empty (lt_from_book (suc. (suc. k)) (suc. (suc. zero.)) hk) ]

def cyclic_four_square_mono
  : IsGroupMono (cyclic_group (suc. (suc. zero.))) (cyclic_group (suc. (suc. (suc. (suc. zero.)))))
      (cyclic_hom_of_element (suc. zero.) (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square
        cyclic_four_square_order)
  ≔ cyclic_hom_of_element_mono (suc. zero.) (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square
      cyclic_four_square_order cyclic_four_square_nontrivial

{` Value at 0 of a symmetry of C_4 (a separate definition, to avoid E0500). `}
def cyclic_four_value (t : USym (cyclic_group (suc. (suc. (suc. (suc. zero.)))))) : Nat
  ≔ cyc_loop_equiv (suc. (suc. (suc. zero.))) .map t .fst

def cyclic_four_square_hom_value
  : Id Nat (cyc_loop_equiv (suc. (suc. (suc. zero.))) .map
      (usym_hom (cyclic_group (suc. (suc. zero.))) (cyclic_group (suc. (suc. (suc. (suc. zero.)))))
        (cyclic_hom_of_element (suc. zero.) (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square
          cyclic_four_square_order)
        (cyclic_group_generator (suc. zero.))) .fst)
      (suc. (suc. zero.))
  ≔ let C4 ≔ cyclic_group (suc. (suc. (suc. (suc. zero.)))) in
    let f ≔ cyclic_hom_of_element (suc. zero.) C4 cyclic_four_square cyclic_four_square_order in
    concat Nat
      (cyc_loop_equiv (suc. (suc. (suc. zero.))) .map (usym_hom (cyclic_group (suc. (suc. zero.))) C4 f
        (cyclic_group_generator (suc. zero.))) .fst)
      (cyc_loop_equiv (suc. (suc. (suc. zero.))) .map cyclic_four_square .fst)
      (suc. (suc. zero.))
      (map_path (USym C4) Nat cyclic_four_value
        (usym_hom (cyclic_group (suc. (suc. zero.))) C4 f (cyclic_group_generator (suc. zero.))) cyclic_four_square
        (cyclic_hom_generator (suc. zero.) C4 cyclic_four_square cyclic_four_square_order))
      (cyclic_generator_power_eval (suc. (suc. (suc. zero.))) (suc. (suc. zero.)) .fst)

def cyclic_four_square_subgroup : Subgroups (cyclic_group (suc. (suc. (suc. (suc. zero.)))))
  ≔ cyclic_subgroup_of_element (suc. zero.) (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square
      cyclic_four_square_order cyclic_four_square_nontrivial

def cyclic_four_square_subgroup_group_path
  : Id Group (subgroup_group (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square_subgroup)
      (cyclic_group (suc. (suc. zero.)))
  ≔ cyclic_subgroup_group_path (suc. zero.) (cyclic_group (suc. (suc. (suc. (suc. zero.))))) cyclic_four_square
      cyclic_four_square_order cyclic_four_square_nontrivial
