export "1015-sylow-sigma-four"
export "1027-cyclic-groups-simple"

{` Chapter 10, the example at fingp.tex 27–33, third paragraph, about Σ_n
   for n > 5, checked on Σ_6 (Fin 6 = {0,…,5}; the book's {1,2,3}, {4,5,6}
   are our {0,1,2}, {3,4,5}).

   - "3^2 = 9 divides n! = |Σ_n| for n > 5": factorial_nine_divides.
   - 3^2 is the largest power of 3 dividing |Σ_6| = 720, so the subgroups of
     order 9 are exactly the 3-Sylow subgroups (sigma6_order_nine_sylow).
   - WRONG AS PRINTED: "Σ_n has n(n−1)(n−2)/6 subgroups of order 3 (n > 2)".
     That number counts the subgroups generated by 3-cycles; for n ≥ 6 there
     are more: d = (0 1 2)(3 4 5) has order 3 and no non-identity element of
     ⟨d⟩ fixes a point (sigma6_d_subgroup_free), while every subgroup
     containing a 3-cycle (which fixes n − 3 ≥ 1 points) contains such an
     element; so ⟨d⟩ is a subgroup of order 3 not generated by a 3-cycle
     (sigma6_d_subgroup_not_point_fixing, instance
     sigma6_cycle012_subgroup_ne_d). (Σ_6 has 40 subgroups of order 3, not
     20; that count is not formalized.)
   - WRONG AS PRINTED: "the subgroup of cyclic permutations of {1,2,3} will
     not be conjugate to the subgroup of cyclic permutations of {4,5,6}":
     with g = (0 3)(1 4)(2 5), g·⟨(0 1 2)⟩ = ⟨(3 4 5)⟩
     (sigma6_cyclic_subgroups_conjugate). What fails to be conjugate for
     n > 5 is e.g. ⟨(0 1 2)⟩ and ⟨(0 1 2)(3 4 5)⟩ (not formalized).
   - "there are 10 of these (one for each subset of {1,…,6} of cardinality
     3)": there are binomial 6 3 = 20 such subsets (sigma6_three_subsets);
     the 10 subgroups of order 9 correspond to the partitions of the six
     letters into two triples. The count 10 itself is not formalized; module
     1017 proves what Sylow III gives (≡ 1 mod 3, divides 80). `}

def sigma6_n : Nat ≔ suc. (suc. (suc. (suc. (suc. (suc. zero.)))))

def fingp_three_sq : Nat ≔ nat_power (suc. (suc. (suc. zero.))) (suc. (suc. zero.))

{` Arithmetic on 6! = 720 is done symbolically: normalizing unary numerals
   of this size (factorial 5 = 120 already) does not finish in Narya, so
   6! = (2 · 5!) · 3 is rewritten with mul_assoc/mul_comm and the 3-adic
   valuation is computed by cancelling factors coprime to 3. `}
def fingp_mul_four (a b c d : Nat) : Id Nat (mul (mul a b) (mul c d)) (mul (mul a c) (mul b d))
  ≔ calc
      mul (mul a b) (mul c d) = mul a (mul b (mul c d)) by mul_assoc a b (mul c d)
      = mul a (mul (mul b c) d) by refl (mul a) (inverse Nat (mul (mul b c) d) (mul b (mul c d)) (mul_assoc b c d))
      = mul a (mul (mul c b) d) by refl (mul a) (refl ((x ↦ mul x d) : Nat → Nat) (mul_comm b c))
      = mul a (mul c (mul b d)) by refl (mul a) (mul_assoc c b d)
      = mul (mul a c) (mul b d) by inverse Nat (mul (mul a c) (mul b d)) (mul a (mul c (mul b d))) (mul_assoc a c (mul b d)) ∎

def nat_divides_mul_both (a b c d : Nat) (h1 : NatDivides a c) (h2 : NatDivides b d) : NatDivides (mul a b) (mul c d)
  ≔ mere_rec (Σ Nat (q ↦ Id Nat c (mul q a))) (NatDivides (mul a b) (mul c d)) (nat_divides_prop (mul a b) (mul c d))
      (u ↦ mere_rec (Σ Nat (q ↦ Id Nat d (mul q b))) (NatDivides (mul a b) (mul c d)) (nat_divides_prop (mul a b) (mul c d))
        (v ↦ nat_divides_intro (mul a b) (mul c d) (mul (u .fst) (v .fst))
          (concat Nat (mul c d) (mul (mul (u .fst) a) (mul (v .fst) b)) (mul (mul (u .fst) (v .fst)) (mul a b))
            (concat Nat (mul c d) (mul (mul (u .fst) a) d) (mul (mul (u .fst) a) (mul (v .fst) b))
              (refl ((x ↦ mul x d) : Nat → Nat) (u .snd)) (refl (mul (mul (u .fst) a)) (v .snd)))
            (fingp_mul_four (u .fst) a (v .fst) b)))
        h2)
      h1

def fingp_six_split : Id Nat sigma6_n (mul two three) ≔ refl sigma6_n

{` 6! = (2 · 5!) · 3. `}
def sigma6_factorial_split : Id Nat (factorial sigma6_n) (mul (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) three)
  ≔ calc
      factorial sigma6_n = mul (mul two three) (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))
        by refl ((x ↦ mul x (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) : Nat → Nat) fingp_six_split
      = mul two (mul three (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) by mul_assoc two three (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))
      = mul two (mul (factorial (suc. (suc. (suc. (suc. (suc. zero.)))))) three) by refl (mul two) (mul_comm three (factorial (suc. (suc. (suc. (suc. (suc. zero.)))))))
      = mul (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) three
        by inverse Nat (mul (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) three) (mul two (mul (factorial (suc. (suc. (suc. (suc. (suc. zero.)))))) three)) (mul_assoc two (factorial (suc. (suc. (suc. (suc. (suc. zero.)))))) three) ∎

def sigma6_three_divides_f5 : NatDivides three (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))
  ≔ nat_divides_mul_left three (suc. (suc. (suc. (suc. (suc. zero.))))) (factorial (suc. three))
      (nat_divides_mul_left three (suc. three) (factorial three)
        (nat_divides_mul_right three three (factorial two) (nat_divides_refl three)))

def sigma6_nine_divides_factorial : NatDivides fingp_three_sq (factorial sigma6_n)
  ≔ transport Nat (NatDivides fingp_three_sq) (mul (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) three) (factorial sigma6_n)
      (inverse Nat (factorial sigma6_n) (mul (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) three) sigma6_factorial_split)
      (nat_divides_mul_both three three (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) three
        (nat_divides_mul_left three two (factorial (suc. (suc. (suc. (suc. (suc. zero.)))))) sigma6_three_divides_f5) (nat_divides_refl three))

{` 9 | n! for n > 5. `}
def factorial_nine_divides_shift (j : Nat) : NatDivides fingp_three_sq (factorial (add sigma6_n j))
  ≔ match j [
  | zero. ↦ sigma6_nine_divides_factorial
  | suc. j ↦ nat_divides_mul_left fingp_three_sq (suc. (add sigma6_n j)) (factorial (add sigma6_n j))
      (factorial_nine_divides_shift j) ]

def factorial_nine_divides (n : Nat) (h : Lt (suc. (suc. (suc. (suc. (suc. zero.))))) n) : NatDivides fingp_three_sq (factorial n)
  ≔ let w ≔ le_to_book sigma6_n n h in
    transport Nat (x ↦ NatDivides fingp_three_sq (factorial x)) (add sigma6_n (w .fst)) n
      (concat Nat (add sigma6_n (w .fst)) (add (w .fst) sigma6_n) n (add_comm sigma6_n (w .fst)) (w .snd))
      (factorial_nine_divides_shift (w .fst))

{` 27 does not divide 6!: cancel the factor 3, then the factors 2, 5, 4
   (coprime to 3), and 9 does not divide 3! = 6. `}
def fingp_coprime_three (m : Nat)
  (e : Id Bool (decision_bool (NatDivides three m) (nat_divides_decidable_any three m)) false.)
  : NatCoprime m three
  ≔ nat_coprime_sym three m (prime_not_divides_coprime three m nat_prime_three
      (nat_decision_false_reflect (NatDivides three m) (nat_divides_decidable_any three m) e))

def sigma6_not_twenty_seven (h : NatDivides (nat_power three three) (factorial sigma6_n)) : Empty
  ≔ let h1 : NatDivides (mul fingp_three_sq three) (mul (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) three)
      ≔ transport Nat (NatDivides (nat_power three three)) (factorial sigma6_n) (mul (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) three)
          sigma6_factorial_split h in
    let h2 : NatDivides fingp_three_sq (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.)))))))
      ≔ nat_divides_mul_cancel_positive three fingp_three_sq (mul two (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))) star. h1 in
    let h3 : NatDivides fingp_three_sq (factorial (suc. (suc. (suc. (suc. (suc. zero.))))))
      ≔ nat_power_divides_coprime_cancel three two (factorial (suc. (suc. (suc. (suc. (suc. zero.)))))) two (fingp_coprime_three two (refl (false. : Bool))) h2 in
    let h4 : NatDivides fingp_three_sq (factorial (suc. three))
      ≔ nat_power_divides_coprime_cancel three (suc. (suc. (suc. (suc. (suc. zero.))))) (factorial (suc. three)) two (fingp_coprime_three (suc. (suc. (suc. (suc. (suc. zero.))))) (refl (false. : Bool))) h3 in
    let h5 : NatDivides fingp_three_sq (factorial three)
      ≔ nat_power_divides_coprime_cancel three (suc. three) (factorial three) two
          (fingp_coprime_three (suc. three) (refl (false. : Bool))) h4 in
    nat_decision_false_reflect (NatDivides fingp_three_sq (factorial three))
      (nat_divides_decidable_any fingp_three_sq (factorial three)) (refl (false. : Bool)) h5

{` 3^2 is the largest power of 3 dividing |Σ_6| = 6!; subgroups of order 9 are 3-Sylow. `}
def sigma6_largest_three
  : IsLargestPrimePower three two (factorial sigma6_n)
  ≔ (sigma6_nine_divides_factorial, sigma6_not_twenty_seven)

def sigma6_order_nine_sylow (T : Subgroups (symmetric_group sigma6_n)) (hT : IsFiniteGroup (subgroup_group (symmetric_group sigma6_n) T))
  (e : Id Nat (group_card (subgroup_group (symmetric_group sigma6_n) T) hT) fingp_three_sq)
  : IsSylowSubgroup (suc. (suc. (suc. zero.))) (symmetric_group sigma6_n) T
  ≔ fingp_sylow_of_card (suc. (suc. (suc. zero.))) (symmetric_group sigma6_n) (symmetric_group_finite sigma6_n) T hT
      (suc. (suc. zero.)) (factorial sigma6_n) (symmetric_group_card sigma6_n) e sigma6_largest_three

def sigma6_three_subsets
  : Id Nat (binomial sigma6_n three) (mul (suc. (suc. (suc. (suc. zero.)))) (suc. (suc. (suc. (suc. (suc. zero.))))))
  ≔ refl (binomial sigma6_n three)

{` Permutations of Fin 6. `}
def fin6_d : Fin sigma6_n → Fin sigma6_n ≔ [
  | inr. u ↦ inl. (inr. u)
  | inl. (inr. u) ↦ inl. (inl. (inr. u))
  | inl. (inl. (inr. u)) ↦ inr. u
  | inl. (inl. (inl. (inr. u))) ↦ inl. (inl. (inl. (inl. (inr. u))))
  | inl. (inl. (inl. (inl. (inr. u)))) ↦ inl. (inl. (inl. (inl. (inl. (inr. u)))))
  | inl. (inl. (inl. (inl. (inl. (inr. u))))) ↦ inl. (inl. (inl. (inr. u)))
  | inl. (inl. (inl. (inl. (inl. (inl. e))))) ↦ match e [] ]

def fin6_a : Fin sigma6_n → Fin sigma6_n ≔ [
  | inr. u ↦ inl. (inr. u)
  | inl. (inr. u) ↦ inl. (inl. (inr. u))
  | inl. (inl. (inr. u)) ↦ inr. u
  | inl. (inl. (inl. x)) ↦ inl. (inl. (inl. x)) ]

def fin6_b : Fin sigma6_n → Fin sigma6_n ≔ [
  | inr. u ↦ inr. u
  | inl. (inr. u) ↦ inl. (inr. u)
  | inl. (inl. (inr. u)) ↦ inl. (inl. (inr. u))
  | inl. (inl. (inl. (inr. u))) ↦ inl. (inl. (inl. (inl. (inr. u))))
  | inl. (inl. (inl. (inl. (inr. u)))) ↦ inl. (inl. (inl. (inl. (inl. (inr. u)))))
  | inl. (inl. (inl. (inl. (inl. (inr. u))))) ↦ inl. (inl. (inl. (inr. u)))
  | inl. (inl. (inl. (inl. (inl. (inl. e))))) ↦ match e [] ]

def fin6_g : Fin sigma6_n → Fin sigma6_n ≔ [
  | inr. u ↦ inl. (inl. (inl. (inr. u)))
  | inl. (inr. u) ↦ inl. (inl. (inl. (inl. (inr. u))))
  | inl. (inl. (inr. u)) ↦ inl. (inl. (inl. (inl. (inl. (inr. u)))))
  | inl. (inl. (inl. (inr. u))) ↦ inr. u
  | inl. (inl. (inl. (inl. (inr. u)))) ↦ inl. (inr. u)
  | inl. (inl. (inl. (inl. (inl. (inr. u))))) ↦ inl. (inl. (inr. u))
  | inl. (inl. (inl. (inl. (inl. (inl. e))))) ↦ match e [] ]

def fin6_zero : Fin sigma6_n ≔ inr. star.
def fin6_three : Fin sigma6_n ≔ inl. (inl. (inl. (inr. star.)))

def fingp_decidable_not (A : Type) (d : Decidable A) : Decidable (Not A)
  ≔ match d [ inl. a ↦ inr. (n ↦ n a) | inr. n ↦ inl. n ]

def fin6_cube (f : Fin sigma6_n → Fin sigma6_n)
  (e : Id Bool (decision_bool ((x : Fin sigma6_n) → Id (Fin sigma6_n) (f (f (f x))) x)
         (fin_forall_decidable sigma6_n (x ↦ Id (Fin sigma6_n) (f (f (f x))) x)
           (x ↦ fin_decidable_equality sigma6_n (f (f (f x))) x))) true.)
  : (x : Fin sigma6_n) → Id (Fin sigma6_n) (f (f (f x))) x
  ≔ decision_bool_reflect ((x : Fin sigma6_n) → Id (Fin sigma6_n) (f (f (f x))) x)
      (fin_forall_decidable sigma6_n (x ↦ Id (Fin sigma6_n) (f (f (f x))) x)
        (x ↦ fin_decidable_equality sigma6_n (f (f (f x))) x)) e

def fin6_d_cube : (x : Fin sigma6_n) → Id (Fin sigma6_n) (fin6_d (fin6_d (fin6_d x))) x ≔ fin6_cube fin6_d (refl (true. : Bool))
def fin6_a_cube : (x : Fin sigma6_n) → Id (Fin sigma6_n) (fin6_a (fin6_a (fin6_a x))) x ≔ fin6_cube fin6_a (refl (true. : Bool))
def fin6_b_cube : (x : Fin sigma6_n) → Id (Fin sigma6_n) (fin6_b (fin6_b (fin6_b x))) x ≔ fin6_cube fin6_b (refl (true. : Bool))

def fin6_g_involutive : (x : Fin sigma6_n) → Id (Fin sigma6_n) (fin6_g (fin6_g x)) x
  ≔ decision_bool_reflect ((x : Fin sigma6_n) → Id (Fin sigma6_n) (fin6_g (fin6_g x)) x)
      (fin_forall_decidable sigma6_n (x ↦ Id (Fin sigma6_n) (fin6_g (fin6_g x)) x)
        (x ↦ fin_decidable_equality sigma6_n (fin6_g (fin6_g x)) x)) (refl (true. : Bool))

{` d and d^2 have no fixed point. `}
def fin6_d_free : (x : Fin sigma6_n) → Not (Id (Fin sigma6_n) (fin6_d x) x)
  ≔ decision_bool_reflect ((x : Fin sigma6_n) → Not (Id (Fin sigma6_n) (fin6_d x) x))
      (fin_forall_decidable sigma6_n (x ↦ Not (Id (Fin sigma6_n) (fin6_d x) x))
        (x ↦ fingp_decidable_not (Id (Fin sigma6_n) (fin6_d x) x) (fin_decidable_equality sigma6_n (fin6_d x) x)))
      (refl (true. : Bool))

def fin6_d2_free : (x : Fin sigma6_n) → Not (Id (Fin sigma6_n) (fin6_d (fin6_d x)) x)
  ≔ decision_bool_reflect ((x : Fin sigma6_n) → Not (Id (Fin sigma6_n) (fin6_d (fin6_d x)) x))
      (fin_forall_decidable sigma6_n (x ↦ Not (Id (Fin sigma6_n) (fin6_d (fin6_d x)) x))
        (x ↦ fingp_decidable_not (Id (Fin sigma6_n) (fin6_d (fin6_d x)) x)
          (fin_decidable_equality sigma6_n (fin6_d (fin6_d x)) x)))
      (refl (true. : Bool))

{` The symmetries of Σ_6. `}
def sigma6_set : SetTypes ≔ standard_set sigma6_n

def sigma6_d : USym (symmetric_group sigma6_n) ≔ permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) fin6_d fin6_d_cube)
def sigma6_a : USym (symmetric_group sigma6_n) ≔ permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) fin6_a fin6_a_cube)
def sigma6_b : USym (symmetric_group sigma6_n) ≔ permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) fin6_b fin6_b_cube)
def sigma6_g : USym (symmetric_group sigma6_n)
  ≔ permutation_symmetry sigma6_set (quasi_inverse_equiv (Fin sigma6_n) (Fin sigma6_n) fin6_g fin6_g fin6_g_involutive fin6_g_involutive)

def sigma6_cube (f : Fin sigma6_n → Fin sigma6_n) (h : (x : Fin sigma6_n) → Id (Fin sigma6_n) (f (f (f x))) x)
  : Id (USym (symmetric_group sigma6_n))
      (usym_power (symmetric_group sigma6_n) (permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) f h)) three)
      (usym_unit (symmetric_group sigma6_n))
  ≔ perm3_symmetry_cube sigma6_set f h

def sigma6_ne (f : Fin sigma6_n → Fin sigma6_n) (h : (x : Fin sigma6_n) → Id (Fin sigma6_n) (f (f (f x))) x) (x : Fin sigma6_n)
  (e : Id Bool (decision_bool (Id (Fin sigma6_n) (f x) x) (fin_decidable_equality sigma6_n (f x) x)) false.)
  : Not (Id (USym (symmetric_group sigma6_n)) (permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) f h))
      (usym_unit (symmetric_group sigma6_n)))
  ≔ perm_symmetry_ne_unit sigma6_set (perm3_equiv (Fin sigma6_n) f h) x
      (nat_decision_false_reflect (Id (Fin sigma6_n) (f x) x) (fin_decidable_equality sigma6_n (f x) x) e)

def sigma6_cyclic (f : Fin sigma6_n → Fin sigma6_n) (h : (x : Fin sigma6_n) → Id (Fin sigma6_n) (f (f (f x))) x) (x : Fin sigma6_n)
  (e : Id Bool (decision_bool (Id (Fin sigma6_n) (f x) x) (fin_decidable_equality sigma6_n (f x) x)) false.)
  : Subgroups (symmetric_group sigma6_n)
  ≔ cyclic_prime_subgroup (suc. (suc. zero.)) nat_prime_three (symmetric_group sigma6_n)
      (permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) f h)) (sigma6_cube f h) (sigma6_ne f h x e)

{` ⟨d⟩, ⟨(0 1 2)⟩, ⟨(3 4 5)⟩. `}
def sigma6_d_subgroup : Subgroups (symmetric_group sigma6_n) ≔ sigma6_cyclic fin6_d fin6_d_cube fin6_zero (refl (false. : Bool))
def sigma6_a_subgroup : Subgroups (symmetric_group sigma6_n) ≔ sigma6_cyclic fin6_a fin6_a_cube fin6_zero (refl (false. : Bool))
def sigma6_b_subgroup : Subgroups (symmetric_group sigma6_n) ≔ sigma6_cyclic fin6_b fin6_b_cube fin6_three (refl (false. : Bool))

{` Membership in ⟨f⟩: f^k ∈ ⟨f⟩, and every member is f^k with k < 3. `}
def SymSubgroupMember (G : Group) (S : Subgroups G) (t : USym G) : Type
  ≔ Id (gset_underlying G (S .gset)) (gset_usym_act G (S .gset) t (S .point)) (S .point)

def sigma6_cyclic_hyp (f : Fin sigma6_n → Fin sigma6_n) (h : (x : Fin sigma6_n) → Id (Fin sigma6_n) (f (f (f x))) x) (x : Fin sigma6_n)
  (e : Id Bool (decision_bool (Id (Fin sigma6_n) (f x) x) (fin_decidable_equality sigma6_n (f x) x)) false.)
  : (k : Nat) → BookLt zero. k → BookLt k three
    → Id (USym (symmetric_group sigma6_n)) (usym_power (symmetric_group sigma6_n) (permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) f h)) k)
         (usym_unit (symmetric_group sigma6_n)) → Empty
  ≔ prime_order_powers_nontrivial three nat_prime_three (symmetric_group sigma6_n)
      (permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) f h)) (sigma6_cube f h) (sigma6_ne f h x e)

def sigma6_cyclic_generator_member (f : Fin sigma6_n → Fin sigma6_n) (h : (x : Fin sigma6_n) → Id (Fin sigma6_n) (f (f (f x))) x)
  (x : Fin sigma6_n) (e : Id Bool (decision_bool (Id (Fin sigma6_n) (f x) x) (fin_decidable_equality sigma6_n (f x) x)) false.)
  : SymSubgroupMember (symmetric_group sigma6_n) (sigma6_cyclic f h x e) (permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) f h))
  ≔ let G ≔ symmetric_group sigma6_n in
    let g ≔ permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) f h) in
    transport (USym G) (t ↦ SymSubgroupMember G (sigma6_cyclic f h x e) t) (usym_power G g (suc. zero.)) g (usym_power_one G g)
      (cyclic_subgroup_power_member (suc. (suc. zero.)) G g (sigma6_cube f h) (sigma6_cyclic_hyp f h x e) (suc. zero.))

def sigma6_cyclic_member_power (f : Fin sigma6_n → Fin sigma6_n) (h : (x : Fin sigma6_n) → Id (Fin sigma6_n) (f (f (f x))) x)
  (x : Fin sigma6_n) (e : Id Bool (decision_bool (Id (Fin sigma6_n) (f x) x) (fin_decidable_equality sigma6_n (f x) x)) false.)
  (t : USym (symmetric_group sigma6_n)) (r : SymSubgroupMember (symmetric_group sigma6_n) (sigma6_cyclic f h x e) t)
  : Mere (Σ Nat (k ↦ Product (BookLt k three)
      (Id (USym (symmetric_group sigma6_n)) t (usym_power (symmetric_group sigma6_n) (permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) f h)) k))))
  ≔ cyclic_subgroup_member_power (suc. (suc. zero.)) (symmetric_group sigma6_n) (permutation_symmetry sigma6_set (perm3_equiv (Fin sigma6_n) f h))
      (sigma6_cube f h) (sigma6_cyclic_hyp f h x e) t r

{` No non-identity element of ⟨d⟩ fixes a point. `}
def sigma6_d_power_action (k : Nat) (x : Fin sigma6_n)
  : Id (Fin sigma6_n) (permutation_action sigma6_set (usym_power (symmetric_group sigma6_n) sigma6_d k) x)
      (iterate (Fin sigma6_n) fin6_d k x)
  ≔ perm_symmetry_power_action sigma6_set (perm3_equiv (Fin sigma6_n) fin6_d fin6_d_cube) k x

def sigma6_d_power_free (t : USym (symmetric_group sigma6_n)) (x : Fin sigma6_n)
  (fx : Id (Fin sigma6_n) (permutation_action sigma6_set t x) x) (k : Nat)
  : Lt k three → Id (USym (symmetric_group sigma6_n)) t (usym_power (symmetric_group sigma6_n) sigma6_d k)
    → Id (USym (symmetric_group sigma6_n)) t (usym_unit (symmetric_group sigma6_n))
  ≔ let G ≔ symmetric_group sigma6_n in
    let act : USym G → Fin sigma6_n ≔ s ↦ permutation_action sigma6_set s x in
    match k [
    | zero. ↦ _ e ↦ e
    | suc. zero. ↦ _ e ↦ absurd (Id (USym G) t (usym_unit G))
        (fin6_d_free x (concat (Fin sigma6_n) (fin6_d x) (act t) x
          (inverse (Fin sigma6_n) (act t) (fin6_d x)
            (concat (Fin sigma6_n) (act t) (act (usym_power G sigma6_d (suc. zero.))) (fin6_d x)
              (refl act e) (sigma6_d_power_action (suc. zero.) x)))
          fx))
    | suc. (suc. zero.) ↦ _ e ↦ absurd (Id (USym G) t (usym_unit G))
        (fin6_d2_free x (concat (Fin sigma6_n) (fin6_d (fin6_d x)) (act t) x
          (inverse (Fin sigma6_n) (act t) (fin6_d (fin6_d x))
            (concat (Fin sigma6_n) (act t) (act (usym_power G sigma6_d (suc. (suc. zero.)))) (fin6_d (fin6_d x))
              (refl act e) (sigma6_d_power_action (suc. (suc. zero.)) x)))
          fx))
    | suc. (suc. (suc. k)) ↦ lt _ ↦ match lt [] ]

def sigma6_d_subgroup_free (t : USym (symmetric_group sigma6_n)) (r : SymSubgroupMember (symmetric_group sigma6_n) sigma6_d_subgroup t)
  (x : Fin sigma6_n) (fx : Id (Fin sigma6_n) (permutation_action sigma6_set t x) x)
  : Id (USym (symmetric_group sigma6_n)) t (usym_unit (symmetric_group sigma6_n))
  ≔ let G ≔ symmetric_group sigma6_n in
    mere_rec (Σ Nat (k ↦ Product (BookLt k three) (Id (USym G) t (usym_power G sigma6_d k))))
      (Id (USym G) t (usym_unit G)) (usym_set G t (usym_unit G))
      (w ↦ sigma6_d_power_free t x fx (w .fst) (lt_from_book (w .fst) three (w .snd .fst)) (w .snd .snd))
      (sigma6_cyclic_member_power fin6_d fin6_d_cube fin6_zero (refl (false. : Bool)) t r)

{` Hence ⟨d⟩ is not a subgroup containing a non-identity element with a
   fixed point (such as the subgroup generated by a 3-cycle). `}
def sigma6_d_subgroup_not_point_fixing (T : Subgroups (symmetric_group sigma6_n)) (t : USym (symmetric_group sigma6_n))
  (r : SymSubgroupMember (symmetric_group sigma6_n) T t) (ne : Not (Id (USym (symmetric_group sigma6_n)) t (usym_unit (symmetric_group sigma6_n))))
  (x : Fin sigma6_n) (fx : Id (Fin sigma6_n) (permutation_action sigma6_set t x) x)
  (e : Id (Subgroups (symmetric_group sigma6_n)) T sigma6_d_subgroup) : Empty
  ≔ ne (sigma6_d_subgroup_free t
      (transport (Subgroups (symmetric_group sigma6_n)) (S ↦ SymSubgroupMember (symmetric_group sigma6_n) S t) T sigma6_d_subgroup e r)
      x fx)

def sigma6_cycle012_subgroup_ne_d (e : Id (Subgroups (symmetric_group sigma6_n)) sigma6_a_subgroup sigma6_d_subgroup) : Empty
  ≔ sigma6_d_subgroup_not_point_fixing sigma6_a_subgroup sigma6_a
      (sigma6_cyclic_generator_member fin6_a fin6_a_cube fin6_zero (refl (false. : Bool)))
      (sigma6_ne fin6_a fin6_a_cube fin6_zero (refl (false. : Bool)))
      fin6_three (refl fin6_three) e

{` g·⟨(0 1 2)⟩ = ⟨(3 4 5)⟩ for g = (0 3)(1 4)(2 5): b·g = g·a. `}
def fin6_bg_ga : (x : Fin sigma6_n) → Id (Fin sigma6_n) (fin6_b (fin6_g x)) (fin6_g (fin6_a x))
  ≔ decision_bool_reflect ((x : Fin sigma6_n) → Id (Fin sigma6_n) (fin6_b (fin6_g x)) (fin6_g (fin6_a x)))
      (fin_forall_decidable sigma6_n (x ↦ Id (Fin sigma6_n) (fin6_b (fin6_g x)) (fin6_g (fin6_a x)))
        (x ↦ fin_decidable_equality sigma6_n (fin6_b (fin6_g x)) (fin6_g (fin6_a x))))
      (refl (true. : Bool))

def sigma6_bg_ga
  : Id (USym (symmetric_group sigma6_n)) (usym_mul (symmetric_group sigma6_n) sigma6_b sigma6_g)
      (usym_mul (symmetric_group sigma6_n) sigma6_g sigma6_a)
  ≔ let G ≔ symmetric_group sigma6_n in let S ≔ sigma6_set in
    permutation_symmetries_ext S (usym_mul G sigma6_b sigma6_g) (usym_mul G sigma6_g sigma6_a)
      (x ↦ concat (Fin sigma6_n) (permutation_action S (usym_mul G sigma6_b sigma6_g) x) (fin6_b (fin6_g x))
        (permutation_action S (usym_mul G sigma6_g sigma6_a) x)
        (permutation_action_mul S sigma6_b sigma6_g x)
        (concat (Fin sigma6_n) (fin6_b (fin6_g x)) (fin6_g (fin6_a x)) (permutation_action S (usym_mul G sigma6_g sigma6_a) x)
          (fin6_bg_ga x)
          (inverse (Fin sigma6_n) (permutation_action S (usym_mul G sigma6_g sigma6_a) x) (fin6_g (fin6_a x))
            (permutation_action_mul S sigma6_g sigma6_a x))))

def sigma6_b_fixes_moved_point
  : Id (gset_underlying (symmetric_group sigma6_n) (sigma6_a_subgroup .gset))
      (gset_usym_act (symmetric_group sigma6_n) (sigma6_a_subgroup .gset) sigma6_b
        (gset_usym_act (symmetric_group sigma6_n) (sigma6_a_subgroup .gset) sigma6_g (sigma6_a_subgroup .point)))
      (gset_usym_act (symmetric_group sigma6_n) (sigma6_a_subgroup .gset) sigma6_g (sigma6_a_subgroup .point))
  ≔ let G ≔ symmetric_group sigma6_n in let X ≔ sigma6_a_subgroup .gset in let x ≔ sigma6_a_subgroup .point in
    let Y ≔ gset_underlying G X in
    calc
      gset_usym_act G X sigma6_b (gset_usym_act G X sigma6_g x)
      = gset_usym_act G X (usym_mul G sigma6_b sigma6_g) x
        by inverse Y (gset_usym_act G X (usym_mul G sigma6_b sigma6_g) x) (gset_usym_act G X sigma6_b (gset_usym_act G X sigma6_g x))
          (gset_act_mul G X sigma6_b sigma6_g x)
      = gset_usym_act G X (usym_mul G sigma6_g sigma6_a) x
        by refl ((s ↦ gset_usym_act G X s x) : USym G → Y) sigma6_bg_ga
      = gset_usym_act G X sigma6_g (gset_usym_act G X sigma6_a x) by gset_act_mul G X sigma6_g sigma6_a x
      = gset_usym_act G X sigma6_g x
        by refl (gset_usym_act G X sigma6_g) (sigma6_cyclic_generator_member fin6_a fin6_a_cube fin6_zero (refl (false. : Bool))) ∎

def sigma6_b_subgroup_le_conjugate
  : SubgroupLe (symmetric_group sigma6_n) sigma6_b_subgroup
      (subgroup_at (symmetric_group sigma6_n) sigma6_a_subgroup
        (gset_usym_act (symmetric_group sigma6_n) (sigma6_a_subgroup .gset) sigma6_g (sigma6_a_subgroup .point)))
  ≔ let G ≔ symmetric_group sigma6_n in let X ≔ sigma6_a_subgroup .gset in
    let y ≔ gset_usym_act G X sigma6_g (sigma6_a_subgroup .point) in
    let Y ≔ gset_underlying G X in
    h r ↦ mere_rec (Σ Nat (k ↦ Product (BookLt k three) (Id (USym G) h (usym_power G sigma6_b k))))
      (Id Y (gset_usym_act G X h y) y) (gset_underlying_set G X (gset_usym_act G X h y) y)
      (w ↦ transport (USym G) (s ↦ Id Y (gset_usym_act G X s y) y) (usym_power G sigma6_b (w .fst)) h
        (inverse (USym G) h (usym_power G sigma6_b (w .fst)) (w .snd .snd))
        (stabilizer_power_fixed G X y sigma6_b sigma6_b_fixes_moved_point (w .fst)))
      (sigma6_cyclic_member_power fin6_b fin6_b_cube fin6_three (refl (false. : Bool)) h r)

def sigma6_cyclic_subgroups_conjugate
  : Id (Subgroups (symmetric_group sigma6_n)) (subgroup_conjugate (symmetric_group sigma6_n) sigma6_g sigma6_a_subgroup) sigma6_b_subgroup
  ≔ let G ≔ symmetric_group sigma6_n in let hG ≔ symmetric_group_finite sigma6_n in
    let A ≔ sigma6_a_subgroup in let B ≔ sigma6_b_subgroup in
    let y ≔ gset_usym_act G (A .gset) sigma6_g (A .point) in
    let hA ≔ cyclic_prime_subgroup_finite (suc. (suc. zero.)) nat_prime_three G sigma6_a (sigma6_cube fin6_a fin6_a_cube)
      (sigma6_ne fin6_a fin6_a_cube fin6_zero (refl (false. : Bool))) in
    let hB ≔ cyclic_prime_subgroup_finite (suc. (suc. zero.)) nat_prime_three G sigma6_b (sigma6_cube fin6_b fin6_b_cube)
      (sigma6_ne fin6_b fin6_b_cube fin6_three (refl (false. : Bool))) in
    let hy ≔ subgroup_at_finite G hG A hA y in
    let cards : Id Nat (group_card (subgroup_group G B) hB) (group_card (subgroup_group G (subgroup_at G A y)) hy)
      ≔ concat Nat (group_card (subgroup_group G B) hB) three (group_card (subgroup_group G (subgroup_at G A y)) hy)
          (cyclic_prime_subgroup_card (suc. (suc. zero.)) nat_prime_three G sigma6_b (sigma6_cube fin6_b fin6_b_cube)
            (sigma6_ne fin6_b fin6_b_cube fin6_three (refl (false. : Bool))) hB)
          (inverse Nat (group_card (subgroup_group G (subgroup_at G A y)) hy) three
            (concat Nat (group_card (subgroup_group G (subgroup_at G A y)) hy) (group_card (subgroup_group G A) hA) three
              (subgroup_at_card G hG A hA y)
              (cyclic_prime_subgroup_card (suc. (suc. zero.)) nat_prime_three G sigma6_a (sigma6_cube fin6_a fin6_a_cube)
                (sigma6_ne fin6_a fin6_a_cube fin6_zero (refl (false. : Bool))) hA))) in
    concat (Subgroups G) (subgroup_conjugate G sigma6_g A) (subgroup_at G A y) B
      (subgroup_conjugate_at G sigma6_g A)
      (inverse (Subgroups G) B (subgroup_at G A y)
        (subgroup_le_card_eq G hG B (subgroup_at G A y) hB hy sigma6_b_subgroup_le_conjugate cards))
