export "1027-cyclic-groups-simple"
export "903-normal-subgroups"

{` Chapter 10, cor:whatSylow2needs (fingp.tex 95-100): for a homomorphism
   f : G → G' with kernel N and a subgroup H of G such that H and G' are
   finite of coprime cardinalities, H is a subgroup of N.

   Supporting material: every symmetry g of a finite group has an order
   (the least positive n with g^n = e; it exists by the pigeonhole
   principle), the order divides |G| (Lagrange for the cyclic subgroup
   generated by g, module 1011), and g^|G| = e.

   Proof of the corollary: for h in H, f(h)^|H| = f(h^|H|) = e, so the
   order of f(h) divides |H| and |G'|, hence is 1, i.e. f(h) = e. The
   book's proof via the image of f∘i and Lagrange on both sides is
   replaced by this element-wise argument; surjectivity of f is not
   needed for "every symmetry of H is in the kernel"
   (coprime_subgroup_in_kernel). It is used to make N a subgroup in the
   sense of Sub(G) (the kernel G-set f^*P_{G'} is transitive exactly when
   f is surjective, module 903), giving H ⊆ N literally
   (coprime_subgroup_le_kernel). `}

{` Every symmetry of a finite group has a positive period (pigeonhole on
   g^0, ..., g^n with n = |G|). `}
def usym_cancel_right (G : Group) (a b : USym G) (p : Id (USym G) (usym_mul G a b) b) : Id (USym G) a (usym_unit G)
  ≔ let A ≔ BG G .carrier in
    let s ≔ shape G in
    concat_cancel_left A s s s b a (refl s)
      (concat (Id A s s) (concat A s s s b a) b (concat A s s s b (refl s)) p
        (inverse (Id A s s) (concat A s s s b (refl s)) b (concat_p1 A s s b)))

def usym_power_fin_map (G : Group) (n : Nat) (e : Equiv (USym G) (Fin n)) (g : USym G) (i : Fin (suc. n)) : Fin n
  ≔ e .map (usym_power G g (fin_index (suc. n) i))

def usym_power_fin_collision (G : Group) (n : Nat) (e : Equiv (USym G) (Fin n)) (g : USym G)
  : Collision (Fin (suc. n)) (Fin n) (usym_power_fin_map G n e g)
  ≔ fin_pigeonhole n (usym_power_fin_map G n e g)

def usym_period_of_ordered (G : Group) (g : USym G) (i j : Nat) (le : Le i j) (ne : Not (Id Nat i j))
  (same : Id (USym G) (usym_power G g i) (usym_power G g j)) : Σ Nat (UsymPositivePeriod G g)
  ≔ let w : BookLe i j ≔ le_to_book i j le in
    let d ≔ w .fst in
    let dz : Not (Id Nat d zero.)
      ≔ q ↦ ne (concat Nat i (add d i) j
          (concat Nat i (add zero. i) (add d i) (inverse Nat (add zero. i) i (add_zero_left i))
            (map_path Nat Nat (k ↦ add k i) zero. d (inverse Nat d zero. q)))
          (w .snd)) in
    (d, ((d, (dz, refl d)),
      usym_cancel_right G (usym_power G g d) (usym_power G g i)
        (calc
          usym_mul G (usym_power G g d) (usym_power G g i)
          = usym_power G g (add d i)
            by inverse (USym G) (usym_power G g (add d i)) (usym_mul G (usym_power G g d) (usym_power G g i))
              (usym_power_add_left G g d i)
          = usym_power G g j by map_path Nat (USym G) (usym_power G g) (add d i) j (w .snd)
          = usym_power G g i by inverse (USym G) (usym_power G g i) (usym_power G g j) same ∎)))

def usym_period_of_distinct (G : Group) (g : USym G) (i j : Nat) (ne : Not (Id Nat i j))
  (same : Id (USym G) (usym_power G g i) (usym_power G g j)) : Σ Nat (UsymPositivePeriod G g)
  ≔ match le_total i j [
    | inl. l ↦ usym_period_of_ordered G g i j l ne same
    | inr. l ↦ usym_period_of_ordered G g j i l (q ↦ ne (inverse Nat j i q))
        (inverse (USym G) (usym_power G g i) (usym_power G g j) same) ]

def usym_positive_period_exists (G : Group) (hG : IsFiniteGroup G) (g : USym G)
  : Mere (Σ Nat (UsymPositivePeriod G g))
  ≔ let n ≔ group_card G hG in
    mere_rec (Id Type (USym G) (Fin n)) (Mere (Σ Nat (UsymPositivePeriod G g)))
      (mere_isprop (Σ Nat (UsymPositivePeriod G g)))
      (q ↦
        let e ≔ id_to_equiv (USym G) (Fin n) q in
        let c ≔ usym_power_fin_collision G n e g in
        mere (Σ Nat (UsymPositivePeriod G g))
          (usym_period_of_distinct G g (fin_index (suc. n) (c .left)) (fin_index (suc. n) (c .right))
            (p ↦ c .distinct (fin_index_injective (suc. n) (c .left) (c .right) p))
            (equivalence_injective (USym G) (Fin n) e (usym_power G g (fin_index (suc. n) (c .left)))
              (usym_power G g (fin_index (suc. n) (c .right))) (c .same))))
      (cardinality_spec (USym G) hG)

{` The order of g: the least positive period. `}
def usym_order_data (G : Group) (hG : IsFiniteGroup G) (g : USym G) : Σ Nat (IsMinimum (UsymPositivePeriod G g))
  ≔ mere_rec (Σ Nat (UsymPositivePeriod G g)) (Σ Nat (IsMinimum (UsymPositivePeriod G g)))
      (minimum_prop (UsymPositivePeriod G g) (usym_positive_period_prop G g))
      (w ↦ usym_least_period_finite G hG g (w .fst) (w .snd))
      (usym_positive_period_exists G hG g)

def usym_order (G : Group) (hG : IsFiniteGroup G) (g : USym G) : Nat ≔ usym_order_data G hG g .fst

{` The order of g divides |G|. `}
def usym_order_divides_card_at (G : Group) (hG : IsFiniteGroup G) (g : USym G) (d : Nat)
  (min : IsMinimum (UsymPositivePeriod G g) d) : NatDivides d (group_card G hG)
  ≔ match d [
    | zero. ↦ absurd (NatDivides zero. (group_card G hG)) (lt_from_book zero. zero. (min .fst .fst))
    | suc. b ↦
      let S ≔ cyclic_subgroup_of_order b G g min in
      let pth ≔ cyclic_subgroup_of_order_group_path b G g min in
      let hS : IsFiniteGroup (subgroup_group G S)
        ≔ group_finite_path (cyclic_group (suc. b)) (subgroup_group G S)
            (inverse Group (subgroup_group G S) (cyclic_group (suc. b)) pth) (cyclic_group_finite b) in
      transport Nat (k ↦ NatDivides k (group_card G hG)) (group_card (subgroup_group G S) hS) (suc. b)
        (concat Nat (group_card (subgroup_group G S) hS) (group_card (cyclic_group (suc. b)) (cyclic_group_finite b)) (suc. b)
          (group_card_path (subgroup_group G S) (cyclic_group (suc. b)) pth hS (cyclic_group_finite b))
          (cyclic_group_card b (cyclic_group_finite b)))
        (lagrange_subgroup_divides G hG S hS) ]

def usym_order_divides_card (G : Group) (hG : IsFiniteGroup G) (g : USym G)
  : NatDivides (usym_order G hG g) (group_card G hG)
  ≔ usym_order_divides_card_at G hG g (usym_order_data G hG g .fst) (usym_order_data G hG g .snd)

{` g^|G| = e. `}
def usym_power_card_unit (G : Group) (hG : IsFiniteGroup G) (g : USym G)
  : Id (USym G) (usym_power G g (group_card G hG)) (usym_unit G)
  ≔ let o ≔ usym_order_data G hG g in
    mere_rec (Σ Nat (q ↦ Id Nat (group_card G hG) (mul q (o .fst))))
      (Id (USym G) (usym_power G g (group_card G hG)) (usym_unit G))
      (usym_set G (usym_power G g (group_card G hG)) (usym_unit G))
      (w ↦ concat (USym G) (usym_power G g (group_card G hG)) (usym_power G g (mul (w .fst) (o .fst))) (usym_unit G)
        (map_path Nat (USym G) (usym_power G g) (group_card G hG) (mul (w .fst) (o .fst)) (w .snd))
        (usym_power_multiple_unit G g (o .fst) (o .snd .fst .snd) (w .fst)))
      (usym_order_divides_card G hG g)

{` A homomorphism between finite groups of coprime cardinalities is trivial. `}
def coprime_hom_trivial (H G' : Group) (hH : IsFiniteGroup H) (hG' : IsFiniteGroup G')
  (cop : NatCoprime (group_card H hH) (group_card G' hG')) (phi : GroupHom H G') (h : USym H)
  : Id (USym G') (usym_hom H G' phi h) (usym_unit G')
  ≔ let a ≔ usym_hom H G' phi h in
    let o ≔ usym_order_data G' hG' a in
    let n ≔ group_card H hH in
    let pH : Id (USym G') (usym_power G' a n) (usym_unit G')
      ≔ calc
          usym_power G' a n
          = usym_hom H G' phi (usym_power H h n)
            by inverse (USym G') (usym_hom H G' phi (usym_power H h n)) (usym_power G' a n) (usym_hom_power H G' phi h n)
          = usym_hom H G' phi (usym_unit H)
            by map_path (USym H) (USym G') (usym_hom H G' phi) (usym_power H h n) (usym_unit H) (usym_power_card_unit H hH h)
          = usym_unit G' by usym_hom_unit H G' phi ∎ in
    let one : Id Nat (o .fst) (suc. zero.)
      ≔ cop (o .fst) (usym_order_divides G' a (o .fst) (o .snd) n pH) (usym_order_divides_card G' hG' a) in
    calc
      a
      = usym_power G' a (suc. zero.) by inverse (USym G') (usym_power G' a (suc. zero.)) a (usym_power_one G' a)
      = usym_power G' a (o .fst) by map_path Nat (USym G') (usym_power G' a) (suc. zero.) (o .fst) (inverse Nat (o .fst) (suc. zero.) one)
      = usym_unit G' by o .snd .fst .snd ∎

{` subgroup_inclusion_usym (module 507): the inclusion sends h to h.1. `}

{` cor:whatSylow2needs: every symmetry of H is in the kernel of f. `}
def coprime_subgroup_in_kernel (G G' : Group) (f : GroupHom G G') (H : Subgroups G)
  (hH : IsFiniteGroup (subgroup_group G H)) (hG' : IsFiniteGroup G')
  (cop : NatCoprime (group_card (subgroup_group G H) hH) (group_card G' hG'))
  (g : USym G) (r : Id (gset_underlying G (H .gset)) (gset_usym_act G (H .gset) g (H .point)) (H .point))
  : Id (USym G') (usym_hom G G' f g) (usym_unit G')
  ≔ let K ≔ subgroup_group G H in
    let i ≔ subgroup_inclusion G H in
    let St ≔ GSetStabilizer G (H .gset) (H .point) in
    let E ≔ subgroup_usym_stabilizer_equiv G H in
    let h ≔ equiv_inverse_map (USym K) St E (g, r) in
    let hi : Id (USym G) (usym_hom K G i h) g
      ≔ concat (USym G) (usym_hom K G i h) (E .map h .fst) g (subgroup_inclusion_usym G H h)
          (map_path St (USym G) (fingp_usym_point G (g' ↦ Id (gset_underlying G (H .gset))
            (gset_usym_act G (H .gset) g' (H .point)) (H .point))) (E .map h) (g, r) (equiv_counit (USym K) St E (g, r))) in
    calc
      usym_hom G G' f g
      = usym_hom G G' f (usym_hom K G i h)
        by map_path (USym G) (USym G') (usym_hom G G' f) g (usym_hom K G i h) (inverse (USym G) (usym_hom K G i h) g hi)
      = usym_hom K G' (group_hom_compose K G G' i f) h
        by inverse (USym G') (usym_hom K G' (group_hom_compose K G G' i f) h) (usym_hom G G' f (usym_hom K G i h))
          (happly (USym K) (_ ↦ USym G') (usym_hom K G' (group_hom_compose K G G' i f))
            (x ↦ usym_hom G G' f (usym_hom K G i x)) (usym_hom_compose K G G' i f) h)
      = usym_unit G' by coprime_hom_trivial K G' hH hG' cop (group_hom_compose K G G' i f) h ∎

{` The kernel G-set f^*P_{G'}: g · Bf_pt = Bf_pt iff f(g) = e. `}
def kernel_gset_fixes_of_trivial (G G' : Group) (f : GroupHom G G') (g : USym G)
  (e : Id (USym G') (usym_hom G G' f g) (usym_unit G'))
  : Id (gset_underlying G (kernel_gset G G' f)) (gset_usym_act G (kernel_gset G G' f) g (hom_point G G' f)) (hom_point G G' f)
  ≔ let A ≔ BG G' .carrier in
    let s ≔ shape G' in
    let t ≔ hom_function G G' f (shape G) in
    let q ≔ hom_point G G' f in
    let a ≔ refl (hom_function G G' f) g in
    calc
      concat A s t t q a
      = concat A s t t (concat A s t t q a) (refl t) by inverse (Id A s t) (concat A s t t (concat A s t t q a) (refl t)) (concat A s t t q a) (concat_p1 A s t (concat A s t t q a))
      = concat A s t t (concat A s t t q a) (concat A t s t (inverse A s t q) q)
        by map_path (Id A t t) (Id A s t) (concat A s t t (concat A s t t q a)) (refl t) (concat A t s t (inverse A s t q) q)
          (inverse (Id A t t) (concat A t s t (inverse A s t q) q) (refl t) (concat_inverse_left A s t q))
      = concat A s s t (concat A s t s (concat A s t t q a) (inverse A s t q)) q
        by inverse (Id A s t) (concat A s s t (concat A s t s (concat A s t t q a) (inverse A s t q)) q)
          (concat A s t t (concat A s t t q a) (concat A t s t (inverse A s t q) q))
          (concat_assoc A s t s t (concat A s t t q a) (inverse A s t q) q)
      = concat A s s t (concat A s t s q (concat A t t s a (inverse A s t q))) q
        by map_path (Id A s s) (Id A s t) (u ↦ concat A s s t u q)
          (concat A s t s (concat A s t t q a) (inverse A s t q)) (concat A s t s q (concat A t t s a (inverse A s t q)))
          (concat_assoc A s t t s q a (inverse A s t q))
      = concat A s s t (refl s) q
        by map_path (Id A s s) (Id A s t) (u ↦ concat A s s t u q)
          (concat A s t s q (concat A t t s a (inverse A s t q))) (refl s) e
      = q by concat_1p A s t q ∎

{` cor:whatSylow2needs with N as a subgroup: for f surjective (connected
   fibers, module 903) the kernel is the subgroup (f^*P_{G'}, Bf_pt), and
   H ⊆ N. `}
def kernel_as_subgroup (G G' : Group) (f : GroupHom G G') (c : IsConnectedHom G G' f) : Subgroups G
  ≔ (kernel_gset G G' f, hom_point G G' f, kernel_gset_transitive G G' f c)

def coprime_subgroup_le_kernel (G G' : Group) (f : GroupHom G G') (c : IsConnectedHom G G' f) (H : Subgroups G)
  (hH : IsFiniteGroup (subgroup_group G H)) (hG' : IsFiniteGroup G')
  (cop : NatCoprime (group_card (subgroup_group G H) hH) (group_card G' hG'))
  : SubgroupLe G H (kernel_as_subgroup G G' f c)
  ≔ g r ↦ kernel_gset_fixes_of_trivial G G' f g (coprime_subgroup_in_kernel G G' f H hH hG' cop g r)

{` Litmus: in C_3, the generator has order 3 and its cube is e. `}
def usym_order_litmus_cyclic_three
  : Id (USym (cyclic_group (suc. (suc. (suc. zero.)))))
      (usym_power (cyclic_group (suc. (suc. (suc. zero.)))) (cyclic_group_generator (suc. (suc. zero.)))
        (group_card (cyclic_group (suc. (suc. (suc. zero.)))) (cyclic_group_finite (suc. (suc. zero.)))))
      (usym_unit (cyclic_group (suc. (suc. (suc. zero.)))))
  ≔ usym_power_card_unit (cyclic_group (suc. (suc. (suc. zero.)))) (cyclic_group_finite (suc. (suc. zero.)))
      (cyclic_group_generator (suc. (suc. zero.)))
