export "1028-coprime-subgroup-kernel"
export "710-hom-delooping"
export "420-group-products-abelian"

{` Chapter 10, cor:orderpsquaredgroups (fingp.tex 218-226), first part:
   the elements of a noncyclic group G of order p^2 (p prime).

   * A group of order p^(m+1) has a central symmetry g ≠ e (the proof of
     lem:nontrivcenter: the fixed points of the adjoint G-set are the
     central symmetries, lem:fixedptsize makes their number divisible by
     p, and e is one of them). Module 1025 proves this for the center
     Z(G) of chapter 12; the form here avoids importing chapter 12.
   * "Since G is not cyclic we have that g^p = e for all g": the order of
     g divides p^2; order p^2 would make the cyclic subgroup generated by
     g all of G, so G ≅ C_{p^2} (order_p_squared_exponent).
   * A symmetry h that is not a power of a given g of order p exists,
     because the p powers of g are not all of the p^2 symmetries.

   "G is cyclic" is read as: G is identified with some cyclic group C_n
   (NotCyclicGroup is its negation). `}

def NotCyclicGroup (G : Group) : Type ≔ Not (Mere (Σ Nat (n ↦ Id Group G (cyclic_group n))))

{` Group algebra in USym G via the abstract group abstr G. `}
def usym_conj_fixed_commutes (G : Group) (g h : USym G)
  (f : Id (USym G) (usym_mul G h (usym_mul G g (usym_inv G h))) g)
  : Id (USym G) (usym_mul G h g) (usym_mul G g h)
  ≔ let A ≔ abstr G in
    let U ≔ USym G in
    let m ≔ usym_mul G in
    let L ≔ usym_abstract_laws G in
    let ih ≔ usym_inv G h in
    calc
      m h g
      = m h (m g (usym_unit G))
        by map_path U U (m h) g (m g (usym_unit G)) (inverse U (m g (usym_unit G)) g (L .unit_right g))
      = m h (m g (m ih h))
        by map_path U U (u ↦ m h (m g u)) (usym_unit G) (m ih h) (inverse U (m ih h) (usym_unit G) (ag_inv_left A h))
      = m h (m (m g ih) h) by map_path U U (m h) (m g (m ih h)) (m (m g ih) h) (L .assoc g ih h)
      = m (m h (m g ih)) h by L .assoc h (m g ih) h
      = m g h by map_path U U (u ↦ m u h) (m h (m g ih)) g f ∎

def AdjointFixed (G : Group) (g : USym G) : Type
  ≔ (h : USym G) → Id (USym G) (gset_usym_act G (adjoint_gset G) h g) g

def adjoint_fixed_commutes (G : Group) (g : USym G) (f : AdjointFixed G g) (h : USym G)
  : Id (USym G) (usym_mul G h g) (usym_mul G g h)
  ≔ usym_conj_fixed_commutes G g h
      (concat (USym G) (usym_mul G h (usym_mul G g (usym_inv G h))) (gset_usym_act G (adjoint_gset G) h g) g
        (inverse (USym G) (gset_usym_act G (adjoint_gset G) h g) (usym_mul G h (usym_mul G g (usym_inv G h)))
          (adjoint_gset_usym_act G h g))
        (f h))

def adjoint_unit_fixed (G : Group) : AdjointFixed G (usym_unit G)
  ≔ h ↦
    let U ≔ USym G in
    let L ≔ usym_abstract_laws G in
    calc
      gset_usym_act G (adjoint_gset G) h (usym_unit G)
      = usym_mul G h (usym_mul G (usym_unit G) (usym_inv G h)) by adjoint_gset_usym_act G h (usym_unit G)
      = usym_mul G h (usym_inv G h)
        by map_path U U (usym_mul G h) (usym_mul G (usym_unit G) (usym_inv G h)) (usym_inv G h) (L .unit_left (usym_inv G h))
      = usym_unit G by L .inv_right h ∎

def fingp_prime_divides_power_succ (p m : Nat) : NatDivides p (nat_power p (suc. m))
  ≔ nat_divides_intro p (nat_power p (suc. m)) (nat_power p m) (refl (nat_power p (suc. m)))

{` A prime is not ≤ 1. `}
def fingp_prime_not_le_one (p : Nat) (hp : NatIsPrime p) (h : Le p (suc. zero.)) : Empty
  ≔ match p [
    | zero. ↦ prime_gt_one zero. hp
    | suc. zero. ↦ prime_gt_one (suc. zero.) hp
    | suc. (suc. k) ↦ h ]

{` A group of order p^(m+1) has a central symmetry g ≠ e. `}
def p_group_central_nontrivial (p : Nat) (hp : NatIsPrime p) (m : Nat) (G : Group) (hG : IsFiniteGroup G)
  (hc : Id Nat (group_card G hG) (nat_power p (suc. m)))
  : Mere (Σ (USym G) (g ↦ Product ((h : USym G) → Id (USym G) (usym_mul G h g) (usym_mul G g h))
      (Not (Id (USym G) g (usym_unit G)))))
  ≔ let U ≔ USym G in
    let X ≔ adjoint_gset G in
    let F ≔ GSetFixedPoints G X in
    let hF ≔ gset_fixed_points_finite G hG X hG in
    let dU ≔ finite_group_decidable_equality G hG in
    let R ≔ Σ U (g ↦ Product ((h : U) → Id U (usym_mul G h g) (usym_mul G g h)) (Not (Id U g (usym_unit G)))) in
    let dF : NatDivides p (cardinality F hF)
      ≔ p_group_fixed_points_divisible p hp (suc. m) G hG hc X hG
          (transport Nat (NatDivides p) (nat_power p (suc. m)) (group_card G hG)
            (inverse Nat (group_card G hG) (nat_power p (suc. m)) hc) (fingp_prime_divides_power_succ p m)) in
    let ePt : F ≔ (usym_unit G, adjoint_unit_fixed G) in
    match finite_quantifiers F hF (u ↦ Not (Id U (u .fst) (usym_unit G))) (u ↦ negation_prop (Id U (u .fst) (usym_unit G)))
      (u ↦ match dU (u .fst) (usym_unit G) [ inl. q ↦ inr. (n ↦ n q) | inr. n ↦ inl. n ]) .snd [
    | inl. t ↦ mere_rec (Σ F (u ↦ Not (Id U (u .fst) (usym_unit G)))) (Mere R) (mere_isprop R)
        (w ↦ mere R (w .fst .fst, (adjoint_fixed_commutes G (w .fst .fst) (w .fst .snd), w .snd))) t
    | inr. no ↦
      let allE : (u : F) → Id U (u .fst) (usym_unit G)
        ≔ u ↦ match dU (u .fst) (usym_unit G) [
          | inl. q ↦ q
          | inr. n ↦ absurd (Id U (u .fst) (usym_unit G)) (no (mere (Σ F (u' ↦ Not (Id U (u' .fst) (usym_unit G)))) (u, n))) ] in
      let hprop : isProp F
        ≔ u v ↦ subtype_equal U (g ↦ (h : U) → Id U (gset_usym_act G X h g) g) (gset_fixed_points_prop G X) u v
            (concat U (u .fst) (usym_unit G) (v .fst) (allE u) (inverse U (v .fst) (usym_unit G) (allE v))) in
      let one : Id Nat (cardinality F hF) (suc. zero.) ≔ inhabited_prop_cardinality F hprop hF ePt in
      absurd (Mere R)
        (fingp_prime_not_le_one p hp (nat_divides_le p zero.
          (transport Nat (NatDivides p) (cardinality F hF) (suc. zero.) one dF))) ]

{` The underlying group of the full subgroup is G; a subgroup with as many
   symmetries as G has underlying group G. `}
def full_subgroup_group_path (G : Group) : Id Group (subgroup_group G (group_full_subgroup G)) G
  ≔ mono_subgroup_group_path G (G, (group_hom_id G, group_hom_id_mono G))

def subgroup_full_order_group_path (G : Group) (hG : IsFiniteGroup G) (S : Subgroups G)
  (hS : IsFiniteGroup (subgroup_group G S)) (e : Id Nat (group_card (subgroup_group G S) hS) (group_card G hG))
  : Id Group (subgroup_group G S) G
  ≔ concat Group (subgroup_group G S) (subgroup_group G (group_full_subgroup G)) G
      (map_path (Subgroups G) Group (subgroup_group G) S (group_full_subgroup G) (lagrange_counting_equal_order G hG S hS e))
      (full_subgroup_group_path G)

{` A symmetry whose order is |G| makes G cyclic. `}
def order_full_cyclic (G : Group) (hG : IsFiniteGroup G) (t : USym G) (d : Nat)
  (min : IsMinimum (UsymPositivePeriod G t) d) (e : Id Nat d (group_card G hG))
  : Mere (Σ Nat (n ↦ Id Group G (cyclic_group n)))
  ≔ match d [
    | zero. ↦ absurd (Mere (Σ Nat (n ↦ Id Group G (cyclic_group n)))) (lt_from_book zero. zero. (min .fst .fst))
    | suc. b ↦
      let S ≔ cyclic_subgroup_of_order b G t min in
      let pth ≔ cyclic_subgroup_of_order_group_path b G t min in
      let hS : IsFiniteGroup (subgroup_group G S)
        ≔ group_finite_path (cyclic_group (suc. b)) (subgroup_group G S)
            (inverse Group (subgroup_group G S) (cyclic_group (suc. b)) pth) (cyclic_group_finite b) in
      let cS : Id Nat (group_card (subgroup_group G S) hS) (group_card G hG)
        ≔ concat Nat (group_card (subgroup_group G S) hS) (suc. b) (group_card G hG)
            (concat Nat (group_card (subgroup_group G S) hS) (group_card (cyclic_group (suc. b)) (cyclic_group_finite b)) (suc. b)
              (group_card_path (subgroup_group G S) (cyclic_group (suc. b)) pth hS (cyclic_group_finite b))
              (cyclic_group_card b (cyclic_group_finite b)))
            e in
      mere (Σ Nat (n ↦ Id Group G (cyclic_group n)))
        (suc. b, concat Group G (subgroup_group G S) (cyclic_group (suc. b))
          (inverse Group (subgroup_group G S) G (subgroup_full_order_group_path G hG S hS cS)) pth) ]

def order_p_squared_order_divides_at (b : Nat) (hp : NatIsPrime (suc. b)) (G : Group) (hG : IsFiniteGroup G)
  (hc : Id Nat (group_card G hG) (nat_power (suc. b) (suc. (suc. zero.)))) (nc : NotCyclicGroup G)
  (t : USym G) (d : Nat) (min : IsMinimum (UsymPositivePeriod G t) d) (k : Nat) (le : Le k (suc. (suc. zero.)))
  (e : Id Nat d (nat_power (suc. b) k)) : NatDivides d (suc. b)
  ≔ match k [
    | zero. ↦ transport Nat (x ↦ NatDivides x (suc. b)) (suc. zero.) d (inverse Nat d (suc. zero.) e) (nat_one_divides (suc. b))
    | suc. zero. ↦ transport Nat (x ↦ NatDivides x (suc. b)) (suc. b) d
        (inverse Nat d (suc. b) (concat Nat d (nat_power (suc. b) (suc. zero.)) (suc. b) e (nat_power_one (suc. b))))
        (nat_divides_refl (suc. b))
    | suc. (suc. zero.) ↦ absurd (NatDivides d (suc. b))
        (nc (order_full_cyclic G hG t d min (concat Nat d (nat_power (suc. b) (suc. (suc. zero.))) (group_card G hG) e
          (inverse Nat (group_card G hG) (nat_power (suc. b) (suc. (suc. zero.))) hc))))
    | suc. (suc. (suc. k)) ↦ absurd (NatDivides d (suc. b)) le ]

{` In a noncyclic group of order p^2 every order divides p. `}
def order_p_squared_order_divides (b : Nat) (hp : NatIsPrime (suc. b)) (G : Group) (hG : IsFiniteGroup G)
  (hc : Id Nat (group_card G hG) (nat_power (suc. b) (suc. (suc. zero.)))) (nc : NotCyclicGroup G)
  (t : USym G) (d : Nat) (min : IsMinimum (UsymPositivePeriod G t) d) : NatDivides d (suc. b)
  ≔ let p : Nat ≔ suc. b in
    let dv : NatDivides d (nat_power p (suc. (suc. zero.)))
      ≔ transport Nat (NatDivides d) (group_card G hG) (nat_power p (suc. (suc. zero.))) hc
          (usym_order_divides_card_at G hG t d min) in
    let w ≔ prime_power_divisor p hp (suc. (suc. zero.)) d dv in
    order_p_squared_order_divides_at b hp G hG hc nc t d min (w .fst) (w .snd .fst) (w .snd .snd)

{` "Since G is not cyclic we have that g^p = e for all g". `}
def order_p_squared_exponent (b : Nat) (hp : NatIsPrime (suc. b)) (G : Group) (hG : IsFiniteGroup G)
  (hc : Id Nat (group_card G hG) (nat_power (suc. b) (suc. (suc. zero.)))) (nc : NotCyclicGroup G) (t : USym G)
  : Id (USym G) (usym_power G t (suc. b)) (usym_unit G)
  ≔ let o ≔ usym_order_data G hG t in
    mere_rec (Σ Nat (q ↦ Id Nat (suc. b) (mul q (o .fst)))) (Id (USym G) (usym_power G t (suc. b)) (usym_unit G))
      (usym_set G (usym_power G t (suc. b)) (usym_unit G))
      (w ↦ concat (USym G) (usym_power G t (suc. b)) (usym_power G t (mul (w .fst) (o .fst))) (usym_unit G)
        (map_path Nat (USym G) (usym_power G t) (suc. b) (mul (w .fst) (o .fst)) (w .snd))
        (usym_power_multiple_unit G t (o .fst) (o .snd .fst .snd) (w .fst)))
      (order_p_squared_order_divides b hp G hG hc nc t (o .fst) (o .snd))

{` p ≠ p^2 for a prime p. `}
def fingp_prime_ne_square (b : Nat) (hp : NatIsPrime (suc. b)) (e : Id Nat (suc. b) (nat_power (suc. b) (suc. (suc. zero.))))
  : Empty
  ≔ let p : Nat ≔ suc. b in
    prime_ne_one p hp
      (inverse Nat (suc. zero.) p
        (fingp_mul_cancel_left p (suc. zero.) p (prime_positive p hp)
          (calc
            mul p (suc. zero.)
            = p by mul_one_right p
            = nat_power p (suc. (suc. zero.)) by e
            = mul p p by map_path Nat Nat (x ↦ mul x p) (mul (suc. zero.) p) p (mul_one_left p) ∎)))

{` A symmetry outside the powers of g (g ≠ e). `}
def order_p_squared_outside (b : Nat) (hp : NatIsPrime (suc. b)) (G : Group) (hG : IsFiniteGroup G)
  (hc : Id Nat (group_card G hG) (nat_power (suc. b) (suc. (suc. zero.)))) (nc : NotCyclicGroup G)
  (g : USym G) (ne : Not (Id (USym G) g (usym_unit G)))
  : Mere (Σ (USym G) (h ↦ (r : Remainder (suc. b)) → Not (Id (USym G) h (usym_power G g (r .fst)))))
  ≔ let p : Nat ≔ suc. b in
    let U ≔ USym G in
    let Rm ≔ Remainder p in
    let dU ≔ finite_group_decidable_equality G hG in
    let P : U → Type ≔ t ↦ Mere (Σ Rm (r ↦ Id U t (usym_power G g (r .fst)))) in
    let dP : (t : U) → Decidable (P t)
      ≔ t ↦ finite_quantifiers Rm (fingp_remainder_finite p) (r ↦ Id U t (usym_power G g (r .fst)))
          (r ↦ usym_set G t (usym_power G g (r .fst))) (r ↦ dU t (usym_power G g (r .fst))) .snd in
    let R ≔ Σ U (h ↦ (r : Rm) → Not (Id U h (usym_power G g (r .fst)))) in
    match finite_quantifiers U hG (t ↦ Not (P t)) (t ↦ negation_prop (P t))
      (t ↦ match dP t [ inl. x ↦ inr. (n ↦ n x) | inr. n ↦ inl. n ]) .snd [
    | inl. m ↦ mere_rec (Σ U (t ↦ Not (P t))) (Mere R) (mere_isprop R)
        (w ↦ mere R (w .fst, r q ↦ w .snd (mere (Σ Rm (r' ↦ Id U (w .fst) (usym_power G g (r' .fst)))) (r, q)))) m
    | inr. no ↦
      let allP : (t : U) → P t
        ≔ t ↦ match dP t [ inl. x ↦ x | inr. n ↦ absurd (P t) (no (mere (Σ U (t' ↦ Not (P t'))) (t, n))) ] in
      let f : Rm → U ≔ r ↦ usym_power G g (r .fst) in
      let hyp ≔ prime_order_powers_nontrivial p hp G g (order_p_squared_exponent b hp G hG hc nc g) ne in
      let inj : PathReflecting Rm U f
        ≔ r r' q ↦ subtype_equal Nat (k ↦ BookLt k p) (k ↦ book_lt_prop k p) r r'
            (usym_power_injective_below G g p hyp (r .fst) (r' .fst) (r .snd) (r' .snd) q) in
      let eqv ≔ set_bijection_equiv Rm U (usym_set G) f inj allP in
      absurd (Mere R)
        (fingp_prime_ne_square b hp
          (calc
            p
            = cardinality Rm (fingp_remainder_finite p)
              by inverse Nat (cardinality Rm (fingp_remainder_finite p)) p (fingp_remainder_card p)
            = group_card G hG by cardinality_equiv Rm U eqv (fingp_remainder_finite p) hG
            = nat_power p (suc. (suc. zero.)) by hc ∎)) ]
