export "1051-order-p-subgroup-count"
export "1053-permutation-code-count"

{` Chapter 10, the example at fingp.tex 27-33: the exact
   numbers of subgroups of order 3 of Σ_n for n ≤ 6.

   The symmetries g of Σ_n with g³ = e are counted by enumeration
   (module 1053): 3, 9, 21, 81 for n = 3, 4, 5, 6. By
   order_p_period_count (module 1051), |{g | g³ = e}| = 1 + 2·|Sub_3(Σ_n)|,
   so Σ_3, Σ_4, Σ_5, Σ_6 have 1, 4, 10, 40 subgroups of order 3. For n ≤ 5
   this is the book's n(n-1)(n-2)/6; for n = 6 the book's formula gives 20
   (it counts only the subgroups generated by a 3-cycle; the other 20 are
   generated by products of two disjoint 3-cycles). `}

{` The symmetries of order dividing 3 are counted by codes. `}
def sym_period_three_card (n : Nat) (hQ : IsFinite (McKayPeriodElements (symmetric_group n) (suc. (suc. zero.))))
  : Id Nat (cardinality (McKayPeriodElements (symmetric_group n) (suc. (suc. zero.))) hQ)
      (perm_code_count n (sym_bool_code_predicate n (pcode_power_unit_test n 3)))
  ≔ let m ≔ perm_code_count n (sym_bool_code_predicate n (pcode_power_unit_test n 3)) in
    concat Nat (cardinality (McKayPeriodElements (symmetric_group n) (suc. (suc. zero.))) hQ) (cardinality (Fin m) (fin_is_finite m)) m
      (cardinality_equiv (McKayPeriodElements (symmetric_group n) (suc. (suc. zero.))) (Fin m) (sym_power_unit_count_equiv n 3)
        hQ (fin_is_finite m))
      (fin_cardinality m)

{` If Σ_n has 1 + 2k symmetries with g³ = e, it has k subgroups of order 3. `}
def sym_order_three_subgroups_card (n k : Nat) (hS : IsFinite (FiniteOrderSubgroups (symmetric_group n) 3))
  (c : Id Nat (perm_code_count n (sym_bool_code_predicate n (pcode_power_unit_test n 3))) (add (suc. zero.) (mul k 2)))
  : Id Nat (cardinality (FiniteOrderSubgroups (symmetric_group n) 3) hS) k
  ≔ let G ≔ symmetric_group n in
    let Q ≔ McKayPeriodElements G (suc. (suc. zero.)) in
    let m ≔ perm_code_count n (sym_bool_code_predicate n (pcode_power_unit_test n 3)) in
    let hQ : IsFinite Q ≔ finite_of_equiv Q (Fin m) (sym_power_unit_count_equiv n 3) (fin_is_finite m) in
    let s ≔ cardinality (FiniteOrderSubgroups G 3) hS in
    let e : Id Nat (add (suc. zero.) (mul s 2)) (add (suc. zero.) (mul k 2))
      ≔ concat Nat (add (suc. zero.) (mul s 2)) (cardinality Q hQ) (add (suc. zero.) (mul k 2))
          (inverse Nat (cardinality Q hQ) (add (suc. zero.) (mul s 2))
            (order_p_period_count (suc. (suc. zero.)) nat_prime_three G (symmetric_group_finite n) hQ hS))
          (concat Nat (cardinality Q hQ) m (add (suc. zero.) (mul k 2)) (sym_period_three_card n hQ) c) in
    nat_mul_cancel_right (suc. zero.) s k (add_cancel_left (suc. zero.) (mul s 2) (mul k 2) e)

def sigma_order_three_subgroups_finite (n : Nat) : IsFinite (FiniteOrderSubgroups (symmetric_group n) 3)
  ≔ order_p_subgroups_finite (suc. (suc. zero.)) nat_prime_three (symmetric_group n) (symmetric_group_finite n)

{` Σ_3, Σ_4, Σ_5, Σ_6 have 1, 4, 10, 40 subgroups of order 3. `}
def sigma3_order_three_subgroups_card (hS : IsFinite (FiniteOrderSubgroups (symmetric_group 3) 3))
  : Id Nat (cardinality (FiniteOrderSubgroups (symmetric_group 3) 3) hS) 1
  ≔ sym_order_three_subgroups_card 3 1 hS sym_order_three_count_three

def sigma4_order_three_subgroups_card (hS : IsFinite (FiniteOrderSubgroups (symmetric_group 4) 3))
  : Id Nat (cardinality (FiniteOrderSubgroups (symmetric_group 4) 3) hS) 4
  ≔ sym_order_three_subgroups_card 4 4 hS sym_order_three_count_four

def sigma5_order_three_subgroups_card (hS : IsFinite (FiniteOrderSubgroups (symmetric_group 5) 3))
  : Id Nat (cardinality (FiniteOrderSubgroups (symmetric_group 5) 3) hS) 10
  ≔ sym_order_three_subgroups_card 5 10 hS sym_order_three_count_five

def sigma6_order_three_subgroups_card (hS : IsFinite (FiniteOrderSubgroups (symmetric_group 6) 3))
  : Id Nat (cardinality (FiniteOrderSubgroups (symmetric_group 6) 3) hS) 40
  ≔ sym_order_three_subgroups_card 6 40 hS sym_order_three_count_six
