export "867-free-word-claims"

{` Chapter 11 (fggroups.tex), sections "Intersecting subgroups" and
   "Connections with automata (*)" (lines 834-961), part 1: finitely
   generated subgroups of F(S) at the level of words.

   Words, the reduction rho = word_reduction S dec and the inverse word
   (word_inverse, module 867) are those of chapter 8.  A finitely generated
   subgroup H of F(S) is given by a finite list gens of words (its
   generators).  A word w represents an element of H if merely some word h
   in the generators and their inverses (a signed word over the alphabet of
   generators, FgautoGen) evaluates to a word with the same reduction as w.
   Since F(S) is the set of reduced words (module 882), this is the
   subgroup of F(S) generated by the elements rho(g), g in gens; module 1157
   transfers it to a subset of USym (constructed_free_group S dec).

   This module proves the word identities needed later (inverse of a
   concatenation, rho(w w^-1) = rho(w^-1 w) = eps) and that membership is
   closed under the group operations. `}

{` Path helpers for words. `}
def fgauto_wtrans (S : Type) (a b c : SignedWord S) (p : Id (SignedWord S) a b) (q : Id (SignedWord S) b c)
  : Id (SignedWord S) a c
  ≔ concat (SignedWord S) a b c p q

def fgauto_wsym (S : Type) (a b : SignedWord S) (p : Id (SignedWord S) a b) : Id (SignedWord S) b a
  ≔ inverse (SignedWord S) a b p

{` rho is a congruence for concatenation on both sides. `}
def fgauto_red_congr_left (S : Type) (dec : DecidableEquality S) (u u' v : SignedWord S)
  (p : Id (SignedWord S) (word_reduction S dec u) (word_reduction S dec u'))
  : Id (SignedWord S) (word_reduction S dec (append (SignedLetter S) u v))
      (word_reduction S dec (append (SignedLetter S) u' v))
  ≔ fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) u v))
      (word_reduction S dec (append (SignedLetter S) (word_reduction S dec u) v))
      (word_reduction S dec (append (SignedLetter S) u' v))
      (word_reduction_append_left S dec u v)
      (fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) (word_reduction S dec u) v))
        (word_reduction S dec (append (SignedLetter S) (word_reduction S dec u') v))
        (word_reduction S dec (append (SignedLetter S) u' v))
        (refl ((z ↦ word_reduction S dec (append (SignedLetter S) z v)) : SignedWord S → SignedWord S) p)
        (fgauto_wsym S (word_reduction S dec (append (SignedLetter S) u' v))
          (word_reduction S dec (append (SignedLetter S) (word_reduction S dec u') v))
          (word_reduction_append_left S dec u' v)))

def fgauto_red_congr_right (S : Type) (dec : DecidableEquality S) (u v v' : SignedWord S)
  (p : Id (SignedWord S) (word_reduction S dec v) (word_reduction S dec v'))
  : Id (SignedWord S) (word_reduction S dec (append (SignedLetter S) u v))
      (word_reduction S dec (append (SignedLetter S) u v'))
  ≔ fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) u v))
      (word_reduction S dec (append (SignedLetter S) u (word_reduction S dec v)))
      (word_reduction S dec (append (SignedLetter S) u v'))
      (word_reduction_append_right S dec u v)
      (fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) u (word_reduction S dec v)))
        (word_reduction S dec (append (SignedLetter S) u (word_reduction S dec v')))
        (word_reduction S dec (append (SignedLetter S) u v'))
        (refl ((z ↦ word_reduction S dec (append (SignedLetter S) u z)) : SignedWord S → SignedWord S) p)
        (fgauto_wsym S (word_reduction S dec (append (SignedLetter S) u v'))
          (word_reduction S dec (append (SignedLetter S) u (word_reduction S dec v')))
          (word_reduction_append_right S dec u v')))

def fgauto_red_congr (S : Type) (dec : DecidableEquality S) (u u' v v' : SignedWord S)
  (p : Id (SignedWord S) (word_reduction S dec u) (word_reduction S dec u'))
  (q : Id (SignedWord S) (word_reduction S dec v) (word_reduction S dec v'))
  : Id (SignedWord S) (word_reduction S dec (append (SignedLetter S) u v))
      (word_reduction S dec (append (SignedLetter S) u' v'))
  ≔ fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) u v))
      (word_reduction S dec (append (SignedLetter S) u' v))
      (word_reduction S dec (append (SignedLetter S) u' v'))
      (fgauto_red_congr_left S dec u u' v p) (fgauto_red_congr_right S dec u' v v' q)

{` Reassociation under rho. `}
def fgauto_red_assoc (S : Type) (dec : DecidableEquality S) (u v w : SignedWord S)
  : Id (SignedWord S) (word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) u v) w))
      (word_reduction S dec (append (SignedLetter S) u (append (SignedLetter S) v w)))
  ≔ refl (word_reduction S dec) (append_assoc (SignedLetter S) u v w)

{` A word with trivial reduction can be inserted or removed. `}
def fgauto_red_drop_right (S : Type) (dec : DecidableEquality S) (u e : SignedWord S)
  (h : Id (SignedWord S) (word_reduction S dec e) nil.)
  : Id (SignedWord S) (word_reduction S dec (append (SignedLetter S) u e)) (word_reduction S dec u)
  ≔ fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) u e))
      (word_reduction S dec (append (SignedLetter S) u nil.)) (word_reduction S dec u)
      (fgauto_red_congr_right S dec u e nil. h)
      (refl (word_reduction S dec) (append_nil (SignedLetter S) u))

def fgauto_red_drop_left (S : Type) (dec : DecidableEquality S) (e u : SignedWord S)
  (h : Id (SignedWord S) (word_reduction S dec e) nil.)
  : Id (SignedWord S) (word_reduction S dec (append (SignedLetter S) e u)) (word_reduction S dec u)
  ≔ fgauto_red_congr_left S dec e nil. u h

{` The inverse word: inverse of a concatenation, involutivity. `}
def fgauto_word_inverse_append (S : Type) (u v : SignedWord S)
  : Id (SignedWord S) (word_inverse S (append (SignedLetter S) u v))
      (append (SignedLetter S) (word_inverse S v) (word_inverse S u))
  ≔ match u [
  | nil. ↦ fgauto_wsym S (append (SignedLetter S) (word_inverse S v) nil.) (word_inverse S v)
      (append_nil (SignedLetter S) (word_inverse S v))
  | cons. x u' ↦ fgauto_wtrans S
      (append (SignedLetter S) (word_inverse S (append (SignedLetter S) u' v)) (cons. (letter_complement S x) nil.))
      (append (SignedLetter S) (append (SignedLetter S) (word_inverse S v) (word_inverse S u'))
        (cons. (letter_complement S x) nil.))
      (append (SignedLetter S) (word_inverse S v)
        (append (SignedLetter S) (word_inverse S u') (cons. (letter_complement S x) nil.)))
      (refl ((z ↦ append (SignedLetter S) z (cons. (letter_complement S x) nil.)) : SignedWord S → SignedWord S)
        (fgauto_word_inverse_append S u' v))
      (append_assoc (SignedLetter S) (word_inverse S v) (word_inverse S u') (cons. (letter_complement S x) nil.)) ]

def fgauto_word_inverse_single (S : Type) (x : SignedLetter S)
  : Id (SignedWord S) (word_inverse S (cons. x nil.)) (cons. (letter_complement S x) nil.)
  ≔ refl (cons. (letter_complement S x) nil. : SignedWord S)

def fgauto_word_inverse_involutive (S : Type) (w : SignedWord S)
  : Id (SignedWord S) (word_inverse S (word_inverse S w)) w
  ≔ match w [
  | nil. ↦ refl (nil. : SignedWord S)
  | cons. x v ↦ fgauto_wtrans S
      (word_inverse S (append (SignedLetter S) (word_inverse S v) (cons. (letter_complement S x) nil.)))
      (append (SignedLetter S) (word_inverse S (cons. (letter_complement S x) nil.)) (word_inverse S (word_inverse S v)))
      (cons. x v)
      (fgauto_word_inverse_append S (word_inverse S v) (cons. (letter_complement S x) nil.))
      (cons. (letter_complement_involutive S x) (fgauto_word_inverse_involutive S v)) ]

{` rho(w w^-1) = eps and rho(w^-1 w) = eps. `}
def fgauto_red_inverse_right (S : Type) (dec : DecidableEquality S) (w : SignedWord S)
  : Id (SignedWord S) (word_reduction S dec (append (SignedLetter S) w (word_inverse S w))) nil.
  ≔ match w [
  | nil. ↦ refl (nil. : SignedWord S)
  | cons. x v ↦
    let c : SignedWord S ≔ cons. (letter_complement S x) nil. in
    fgauto_wtrans S
      (word_letter_reduce S dec x (word_reduction S dec
        (append (SignedLetter S) v (append (SignedLetter S) (word_inverse S v) c))))
      (word_letter_reduce S dec x c) nil.
      (refl (word_letter_reduce S dec x)
        (fgauto_wtrans S
          (word_reduction S dec (append (SignedLetter S) v (append (SignedLetter S) (word_inverse S v) c)))
          (word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) v (word_inverse S v)) c))
          c
          (fgauto_wsym S (word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) v (word_inverse S v)) c))
            (word_reduction S dec (append (SignedLetter S) v (append (SignedLetter S) (word_inverse S v) c)))
            (fgauto_red_assoc S dec v (word_inverse S v) c))
          (fgauto_red_drop_left S dec (append (SignedLetter S) v (word_inverse S v)) c
            (fgauto_red_inverse_right S dec v))))
      (word_letter_reduce_drop S dec x nil.) ]

def fgauto_red_inverse_left (S : Type) (dec : DecidableEquality S) (w : SignedWord S)
  : Id (SignedWord S) (word_reduction S dec (append (SignedLetter S) (word_inverse S w) w)) nil.
  ≔ fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) (word_inverse S w) w))
      (word_reduction S dec (append (SignedLetter S) (word_inverse S w) (word_inverse S (word_inverse S w)))) nil.
      (fgauto_wsym S (word_reduction S dec (append (SignedLetter S) (word_inverse S w) (word_inverse S (word_inverse S w))))
        (word_reduction S dec (append (SignedLetter S) (word_inverse S w) w))
        (refl ((z ↦ word_reduction S dec (append (SignedLetter S) (word_inverse S w) z)) : SignedWord S → SignedWord S)
          (fgauto_word_inverse_involutive S w)))
      (fgauto_red_inverse_right S dec (word_inverse S w))

{` rho(a) = rho(b) implies rho(a^-1) = rho(b^-1). `}
def fgauto_red_inverse_congr (S : Type) (dec : DecidableEquality S) (a b : SignedWord S)
  (p : Id (SignedWord S) (word_reduction S dec a) (word_reduction S dec b))
  : Id (SignedWord S) (word_reduction S dec (word_inverse S a)) (word_reduction S dec (word_inverse S b))
  ≔ let ia ≔ word_inverse S a in
    let ib ≔ word_inverse S b in
    calc
      word_reduction S dec ia
      = word_reduction S dec (append (SignedLetter S) ia (append (SignedLetter S) b ib))
        by fgauto_wsym S (word_reduction S dec (append (SignedLetter S) ia (append (SignedLetter S) b ib)))
             (word_reduction S dec ia) (fgauto_red_drop_right S dec ia (append (SignedLetter S) b ib)
               (fgauto_red_inverse_right S dec b))
      = word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) ia b) ib)
        by fgauto_wsym S (word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) ia b) ib))
             (word_reduction S dec (append (SignedLetter S) ia (append (SignedLetter S) b ib)))
             (fgauto_red_assoc S dec ia b ib)
      = word_reduction S dec ib
        by fgauto_red_drop_left S dec (append (SignedLetter S) ia b) ib
             (fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) ia b))
               (word_reduction S dec (append (SignedLetter S) ia a)) nil.
               (fgauto_red_congr_right S dec ia b a
                 (fgauto_wsym S (word_reduction S dec a) (word_reduction S dec b) p))
               (fgauto_red_inverse_left S dec a)) ∎

{` List membership (proof-relevant: a position). `}
def FgautoMem (A : Type) (a : A) (l : List A) : Type
  ≔ match l [ nil. ↦ Empty | cons. b t ↦ Sum (Id A a b) (FgautoMem A a t) ]

def fgauto_mem_append_left (A : Type) (a : A) (l m : List A) (h : FgautoMem A a l)
  : FgautoMem A a (append A l m)
  ≔ match l [
  | nil. ↦ match h []
  | cons. b t ↦ match h [ inl. p ↦ inl. p | inr. h' ↦ inr. (fgauto_mem_append_left A a t m h') ] ]

def fgauto_mem_append_right (A : Type) (a : A) (l m : List A) (h : FgautoMem A a m)
  : FgautoMem A a (append A l m)
  ≔ match l [ nil. ↦ h | cons. b t ↦ inr. (fgauto_mem_append_right A a t m h) ]

def fgauto_mem_append_split (A : Type) (a : A) (l m : List A) (h : FgautoMem A a (append A l m))
  : Sum (FgautoMem A a l) (FgautoMem A a m)
  ≔ match l [
  | nil. ↦ inr. h
  | cons. b t ↦ match h [
    | inl. p ↦ inl. (inl. p)
    | inr. h' ↦ match fgauto_mem_append_split A a t m h' [ inl. k ↦ inl. (inr. k) | inr. k ↦ inr. k ] ] ]

{` The alphabet of generators and the evaluation of a word in the generators
   (a generator g is read as g, its formal inverse as g^-1). `}
def FgautoGen (S : Type) (gens : List (SignedWord S)) : Type
  ≔ Σ (SignedWord S) (g ↦ FgautoMem (SignedWord S) g gens)

def fgauto_gen_letter_eval (S : Type) (gens : List (SignedWord S)) (x : SignedLetter (FgautoGen S gens))
  : SignedWord S
  ≔ match x [ inl. g ↦ g .fst | inr. g ↦ word_inverse S (g .fst) ]

def fgauto_gen_eval (S : Type) (gens : List (SignedWord S)) (h : SignedWord (FgautoGen S gens)) : SignedWord S
  ≔ match h [
  | nil. ↦ nil.
  | cons. x t ↦ append (SignedLetter S) (fgauto_gen_letter_eval S gens x) (fgauto_gen_eval S gens t) ]

def fgauto_gen_eval_append (S : Type) (gens : List (SignedWord S)) (h k : SignedWord (FgautoGen S gens))
  : Id (SignedWord S) (fgauto_gen_eval S gens (append (SignedLetter (FgautoGen S gens)) h k))
      (append (SignedLetter S) (fgauto_gen_eval S gens h) (fgauto_gen_eval S gens k))
  ≔ match h [
  | nil. ↦ refl (fgauto_gen_eval S gens k)
  | cons. x t ↦ fgauto_wtrans S
      (append (SignedLetter S) (fgauto_gen_letter_eval S gens x)
        (fgauto_gen_eval S gens (append (SignedLetter (FgautoGen S gens)) t k)))
      (append (SignedLetter S) (fgauto_gen_letter_eval S gens x)
        (append (SignedLetter S) (fgauto_gen_eval S gens t) (fgauto_gen_eval S gens k)))
      (append (SignedLetter S) (append (SignedLetter S) (fgauto_gen_letter_eval S gens x) (fgauto_gen_eval S gens t))
        (fgauto_gen_eval S gens k))
      (refl ((z ↦ append (SignedLetter S) (fgauto_gen_letter_eval S gens x) z) : SignedWord S → SignedWord S)
        (fgauto_gen_eval_append S gens t k))
      (fgauto_wsym S
        (append (SignedLetter S) (append (SignedLetter S) (fgauto_gen_letter_eval S gens x) (fgauto_gen_eval S gens t))
          (fgauto_gen_eval S gens k))
        (append (SignedLetter S) (fgauto_gen_letter_eval S gens x)
          (append (SignedLetter S) (fgauto_gen_eval S gens t) (fgauto_gen_eval S gens k)))
        (append_assoc (SignedLetter S) (fgauto_gen_letter_eval S gens x) (fgauto_gen_eval S gens t)
          (fgauto_gen_eval S gens k))) ]

def fgauto_gen_letter_eval_complement (S : Type) (gens : List (SignedWord S)) (x : SignedLetter (FgautoGen S gens))
  : Id (SignedWord S) (fgauto_gen_letter_eval S gens (letter_complement (FgautoGen S gens) x))
      (word_inverse S (fgauto_gen_letter_eval S gens x))
  ≔ match x [
  | inl. g ↦ refl (word_inverse S (g .fst))
  | inr. g ↦ fgauto_wsym S (word_inverse S (word_inverse S (g .fst))) (g .fst)
      (fgauto_word_inverse_involutive S (g .fst)) ]

def fgauto_gen_eval_inverse (S : Type) (gens : List (SignedWord S)) (h : SignedWord (FgautoGen S gens))
  : Id (SignedWord S) (fgauto_gen_eval S gens (word_inverse (FgautoGen S gens) h))
      (word_inverse S (fgauto_gen_eval S gens h))
  ≔ match h [
  | nil. ↦ refl (nil. : SignedWord S)
  | cons. x t ↦
    let G ≔ FgautoGen S gens in
    let ex ≔ fgauto_gen_letter_eval S gens x in
    let et ≔ fgauto_gen_eval S gens t in
    calc
      fgauto_gen_eval S gens (append (SignedLetter G) (word_inverse G t) (cons. (letter_complement G x) nil.))
      = append (SignedLetter S) (fgauto_gen_eval S gens (word_inverse G t))
          (fgauto_gen_eval S gens (cons. (letter_complement G x) nil.))
        by fgauto_gen_eval_append S gens (word_inverse G t) (cons. (letter_complement G x) nil.)
      = append (SignedLetter S) (word_inverse S et)
          (append (SignedLetter S) (word_inverse S ex) nil.)
        by refl ((u ↦ v ↦ append (SignedLetter S) u (append (SignedLetter S) v nil.))
               : SignedWord S → SignedWord S → SignedWord S)
             (fgauto_gen_eval_inverse S gens t) (fgauto_gen_letter_eval_complement S gens x)
      = append (SignedLetter S) (word_inverse S et) (word_inverse S ex)
        by refl ((u ↦ append (SignedLetter S) (word_inverse S et) u) : SignedWord S → SignedWord S)
             (append_nil (SignedLetter S) (word_inverse S ex))
      = word_inverse S (append (SignedLetter S) ex et)
        by fgauto_wsym S (word_inverse S (append (SignedLetter S) ex et))
             (append (SignedLetter S) (word_inverse S et) (word_inverse S ex))
             (fgauto_word_inverse_append S ex et) ∎ ]

{` Membership in the subgroup generated by gens. `}
def FgautoInSubgroup (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S) : Type
  ≔ Mere (Σ (SignedWord (FgautoGen S gens)) (h ↦
       Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h)) (word_reduction S dec w)))

def fgauto_in_subgroup_prop (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : isProp (FgautoInSubgroup S dec gens w)
  ≔ mere_isprop (Σ (SignedWord (FgautoGen S gens)) (h ↦
       Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h)) (word_reduction S dec w)))

def fgauto_in_subgroup_witness (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (w : SignedWord S) (h : SignedWord (FgautoGen S gens))
  (p : Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h)) (word_reduction S dec w))
  : FgautoInSubgroup S dec gens w
  ≔ mere (Σ (SignedWord (FgautoGen S gens)) (h ↦
       Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h)) (word_reduction S dec w))) (h, p)

{` Membership only depends on the reduction. `}
def fgauto_in_subgroup_red (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (u v : SignedWord S)
  (p : Id (SignedWord S) (word_reduction S dec u) (word_reduction S dec v)) (m : FgautoInSubgroup S dec gens u)
  : FgautoInSubgroup S dec gens v
  ≔ mere_rec (Σ (SignedWord (FgautoGen S gens)) (h ↦
       Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h)) (word_reduction S dec u)))
      (FgautoInSubgroup S dec gens v) (fgauto_in_subgroup_prop S dec gens v)
      (z ↦ fgauto_in_subgroup_witness S dec gens v (z .fst)
        (fgauto_wtrans S (word_reduction S dec (fgauto_gen_eval S gens (z .fst))) (word_reduction S dec u)
          (word_reduction S dec v) (z .snd) p)) m

def fgauto_in_subgroup_unit (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  : FgautoInSubgroup S dec gens nil.
  ≔ fgauto_in_subgroup_witness S dec gens nil. nil. (refl (nil. : SignedWord S))

def fgauto_in_subgroup_generator (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (g : SignedWord S) (m : FgautoMem (SignedWord S) g gens) : FgautoInSubgroup S dec gens g
  ≔ fgauto_in_subgroup_witness S dec gens g (cons. (inl. (g, m)) nil.)
      (refl (word_reduction S dec) (append_nil (SignedLetter S) g))

def fgauto_in_subgroup_mul (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (u v : SignedWord S)
  (mu : FgautoInSubgroup S dec gens u) (mv : FgautoInSubgroup S dec gens v)
  : FgautoInSubgroup S dec gens (append (SignedLetter S) u v)
  ≔ let G ≔ FgautoGen S gens in
    let T : SignedWord S → Type ≔ w ↦ Σ (SignedWord G) (h ↦
       Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h)) (word_reduction S dec w)) in
    let goal ≔ FgautoInSubgroup S dec gens (append (SignedLetter S) u v) in
    mere_rec (T u) goal (fgauto_in_subgroup_prop S dec gens (append (SignedLetter S) u v))
      (a ↦ mere_rec (T v) goal (fgauto_in_subgroup_prop S dec gens (append (SignedLetter S) u v))
        (b ↦ fgauto_in_subgroup_witness S dec gens (append (SignedLetter S) u v)
          (append (SignedLetter G) (a .fst) (b .fst))
          (fgauto_wtrans S
            (word_reduction S dec (fgauto_gen_eval S gens (append (SignedLetter G) (a .fst) (b .fst))))
            (word_reduction S dec (append (SignedLetter S) (fgauto_gen_eval S gens (a .fst)) (fgauto_gen_eval S gens (b .fst))))
            (word_reduction S dec (append (SignedLetter S) u v))
            (refl (word_reduction S dec) (fgauto_gen_eval_append S gens (a .fst) (b .fst)))
            (fgauto_red_congr S dec (fgauto_gen_eval S gens (a .fst)) u (fgauto_gen_eval S gens (b .fst)) v
              (a .snd) (b .snd)))) mv) mu

def fgauto_in_subgroup_inv (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (u : SignedWord S)
  (mu : FgautoInSubgroup S dec gens u) : FgautoInSubgroup S dec gens (word_inverse S u)
  ≔ let G ≔ FgautoGen S gens in
    mere_rec (Σ (SignedWord G) (h ↦
       Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h)) (word_reduction S dec u)))
      (FgautoInSubgroup S dec gens (word_inverse S u)) (fgauto_in_subgroup_prop S dec gens (word_inverse S u))
      (a ↦ fgauto_in_subgroup_witness S dec gens (word_inverse S u) (word_inverse G (a .fst))
        (fgauto_wtrans S (word_reduction S dec (fgauto_gen_eval S gens (word_inverse G (a .fst))))
          (word_reduction S dec (word_inverse S (fgauto_gen_eval S gens (a .fst))))
          (word_reduction S dec (word_inverse S u))
          (refl (word_reduction S dec) (fgauto_gen_eval_inverse S gens (a .fst)))
          (fgauto_red_inverse_congr S dec (fgauto_gen_eval S gens (a .fst)) u (a .snd)))) mu

{` Right cosets: H p = H q iff p q^-1 represents an element of H. `}
def FgautoSameCoset (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (p q : SignedWord S) : Type
  ≔ FgautoInSubgroup S dec gens (append (SignedLetter S) p (word_inverse S q))

{` Transitivity and symmetry of the coset relation (reflexivity:
   fgauto_in_subgroup_red with fgauto_red_inverse_right). `}
def fgauto_same_coset_refl (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (p : SignedWord S)
  : FgautoSameCoset S dec gens p p
  ≔ fgauto_in_subgroup_red S dec gens nil. (append (SignedLetter S) p (word_inverse S p))
      (fgauto_wsym S (word_reduction S dec (append (SignedLetter S) p (word_inverse S p))) nil.
        (fgauto_red_inverse_right S dec p))
      (fgauto_in_subgroup_unit S dec gens)

def fgauto_same_coset_trans (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (p q r : SignedWord S)
  (a : FgautoSameCoset S dec gens p q) (b : FgautoSameCoset S dec gens q r) : FgautoSameCoset S dec gens p r
  ≔ let iq ≔ word_inverse S q in
    let ir ≔ word_inverse S r in
    fgauto_in_subgroup_red S dec gens
      (append (SignedLetter S) (append (SignedLetter S) p iq) (append (SignedLetter S) q ir))
      (append (SignedLetter S) p ir)
      (calc
        word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) p iq) (append (SignedLetter S) q ir))
        = word_reduction S dec (append (SignedLetter S) p (append (SignedLetter S) iq (append (SignedLetter S) q ir)))
          by fgauto_red_assoc S dec p iq (append (SignedLetter S) q ir)
        = word_reduction S dec (append (SignedLetter S) p (append (SignedLetter S) (append (SignedLetter S) iq q) ir))
          by fgauto_red_congr_right S dec p (append (SignedLetter S) iq (append (SignedLetter S) q ir))
               (append (SignedLetter S) (append (SignedLetter S) iq q) ir)
               (fgauto_wsym S (word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) iq q) ir))
                 (word_reduction S dec (append (SignedLetter S) iq (append (SignedLetter S) q ir)))
                 (fgauto_red_assoc S dec iq q ir))
        = word_reduction S dec (append (SignedLetter S) p ir)
          by fgauto_red_congr_right S dec p (append (SignedLetter S) (append (SignedLetter S) iq q) ir) ir
               (fgauto_red_drop_left S dec (append (SignedLetter S) iq q) ir (fgauto_red_inverse_left S dec q)) ∎)
      (fgauto_in_subgroup_mul S dec gens (append (SignedLetter S) p iq) (append (SignedLetter S) q ir) a b)

def fgauto_same_coset_sym (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (p q : SignedWord S)
  (a : FgautoSameCoset S dec gens p q) : FgautoSameCoset S dec gens q p
  ≔ fgauto_in_subgroup_red S dec gens (word_inverse S (append (SignedLetter S) p (word_inverse S q)))
      (append (SignedLetter S) q (word_inverse S p))
      (refl (word_reduction S dec)
        (fgauto_wtrans S (word_inverse S (append (SignedLetter S) p (word_inverse S q)))
          (append (SignedLetter S) (word_inverse S (word_inverse S q)) (word_inverse S p))
          (append (SignedLetter S) q (word_inverse S p))
          (fgauto_word_inverse_append S p (word_inverse S q))
          (refl ((z ↦ append (SignedLetter S) z (word_inverse S p)) : SignedWord S → SignedWord S)
            (fgauto_word_inverse_involutive S q))))
      (fgauto_in_subgroup_inv S dec gens (append (SignedLetter S) p (word_inverse S q)) a)

{` H eps = H w iff w represents an element of H. `}
def fgauto_same_coset_unit_member (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  (a : FgautoSameCoset S dec gens w nil.) : FgautoInSubgroup S dec gens w
  ≔ fgauto_in_subgroup_red S dec gens (append (SignedLetter S) w nil.) w
      (refl (word_reduction S dec) (append_nil (SignedLetter S) w)) a

def fgauto_member_same_coset_unit (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  (m : FgautoInSubgroup S dec gens w) : FgautoSameCoset S dec gens w nil.
  ≔ fgauto_in_subgroup_red S dec gens w (append (SignedLetter S) w nil.)
      (refl (word_reduction S dec)
        (fgauto_wsym S (append (SignedLetter S) w nil.) w (append_nil (SignedLetter S) w)))
      m
