export "1153-fgauto-stallings"
export "882-free-group-bridge"

{` Chapter 11, automata part 5: transfer of the word-level notions to the
   free group F(S) = constructed_free_group S dec (module 877), whose
   elements are the reduced words via the book's interpretation
   [-] : R_S ~ USym F(S) (constructed_free_group_interpretation_equiv,
   module 882).

   fgauto_fg_subgroup S dec gens is the subset of USym F(S) of elements g
   whose reduced word [g]^-1 represents an element of <gens> in the sense of
   FgautoInSubgroup.  It is a subgroup (closed under unit, product and
   inverse), contains [g] for every generator, and is contained in every
   such subset (fgauto_fg_subgroup_least): it is the subgroup of F(S)
   generated by the elements [g], g in gens.  (In chapter-5 terms
   (Subgroups G, a pointed transitive G-set) it corresponds to the G-set of
   its cosets; we work with the subset because the statements of this
   section are about elements and words.)  The theorem at 839 and the
   corollary at 932 are restated for F(S). `}

def fgauto_free_group (S : Type) (dec : DecidableEquality S) : Group ≔ constructed_free_group S dec

{` The interpretation of an arbitrary word in F(S). `}
def fgauto_word_element (S : Type) (dec : DecidableEquality S) (w : SignedWord S) : USym (fgauto_free_group S dec)
  ≔ free_group_word S dec (constructed_free_group_signature S dec) w

def fgauto_word_element_reduction (S : Type) (dec : DecidableEquality S) (w : SignedWord S)
  : Id (USym (fgauto_free_group S dec)) (fgauto_word_element S dec (word_reduction S dec w)) (fgauto_word_element S dec w)
  ≔ free_word_interpretation_reduction S dec (constructed_free_group_signature S dec) w

{` The reduced word of an element (inverse of the interpretation). `}
def fgauto_element_word (S : Type) (dec : DecidableEquality S) (g : USym (fgauto_free_group S dec)) : SignedWord S
  ≔ equiv_inverse_map (ReducedWord S) (USym (fgauto_free_group S dec)) (constructed_free_group_interpretation_equiv S dec) g
      .fst

def fgauto_element_word_of_word (S : Type) (dec : DecidableEquality S) (w : SignedWord S)
  : Id (SignedWord S) (fgauto_element_word S dec (fgauto_word_element S dec w)) (word_reduction S dec w)
  ≔ let e ≔ constructed_free_group_interpretation_equiv S dec in
    let r : ReducedWord S ≔ (word_reduction S dec w, word_reduction_reduced S dec w) in
    concat (SignedWord S) (fgauto_element_word S dec (fgauto_word_element S dec w))
      (fgauto_element_word S dec (e .map r)) (word_reduction S dec w)
      (refl (fgauto_element_word S dec)
        (inverse (USym (fgauto_free_group S dec)) (e .map r) (fgauto_word_element S dec w)
          (fgauto_word_element_reduction S dec w)))
      (refl ((z ↦ z .fst) : ReducedWord S → SignedWord S)
        (inverse (ReducedWord S) r (equiv_inverse_map (ReducedWord S) (USym (fgauto_free_group S dec)) e (e .map r))
          (equiv_unit (ReducedWord S) (USym (fgauto_free_group S dec)) e r)))

def fgauto_element_word_reduced (S : Type) (dec : DecidableEquality S) (g : USym (fgauto_free_group S dec))
  : IsReducedWord S (fgauto_element_word S dec g)
  ≔ equiv_inverse_map (ReducedWord S) (USym (fgauto_free_group S dec)) (constructed_free_group_interpretation_equiv S dec) g
      .snd

def fgauto_element_word_element (S : Type) (dec : DecidableEquality S) (g : USym (fgauto_free_group S dec))
  : Id (USym (fgauto_free_group S dec)) (fgauto_word_element S dec (fgauto_element_word S dec g)) g
  ≔ equiv_counit (ReducedWord S) (USym (fgauto_free_group S dec)) (constructed_free_group_interpretation_equiv S dec) g

{` The subgroup of F(S) generated by gens, as a subset of USym F(S). `}
def fgauto_fg_subgroup (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  : Subtypes (USym (fgauto_free_group S dec))
  ≔ g ↦ (FgautoInSubgroup S dec gens (fgauto_element_word S dec g),
         fgauto_in_subgroup_prop S dec gens (fgauto_element_word S dec g))

def fgauto_fg_subgroup_word (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : Product (fgauto_fg_subgroup S dec gens (fgauto_word_element S dec w) .fst → FgautoInSubgroup S dec gens w)
      (FgautoInSubgroup S dec gens w → fgauto_fg_subgroup S dec gens (fgauto_word_element S dec w) .fst)
  ≔ let p ≔ fgauto_element_word_of_word S dec w in
    (m ↦ fgauto_in_subgroup_red S dec gens (fgauto_element_word S dec (fgauto_word_element S dec w)) w
       (fgauto_wtrans S (word_reduction S dec (fgauto_element_word S dec (fgauto_word_element S dec w)))
         (word_reduction S dec (word_reduction S dec w)) (word_reduction S dec w)
         (refl (word_reduction S dec) p) (word_reduction_idempotent S dec w)) m,
     m ↦ fgauto_in_subgroup_red S dec gens w (fgauto_element_word S dec (fgauto_word_element S dec w))
       (fgauto_wsym S (word_reduction S dec (fgauto_element_word S dec (fgauto_word_element S dec w)))
         (word_reduction S dec w)
         (fgauto_wtrans S (word_reduction S dec (fgauto_element_word S dec (fgauto_word_element S dec w)))
           (word_reduction S dec (word_reduction S dec w)) (word_reduction S dec w)
           (refl (word_reduction S dec) p) (word_reduction_idempotent S dec w))) m)

{` Subgroups of a group as subsets of USym G closed under the operations. `}
def FgautoSubgroupSubset (G : Group) (P : Subtypes (USym G)) : Type
  ≔ Product (P (usym_unit G) .fst)
      (Product ((g h : USym G) → P g .fst → P h .fst → P (usym_mul G g h) .fst)
        ((g : USym G) → P g .fst → P (usym_inv G g) .fst))

def fgauto_subset_transport (G : Group) (P : Subtypes (USym G)) (g h : USym G) (e : Id (USym G) g h) (m : P g .fst)
  : P h .fst
  ≔ transport (USym G) (z ↦ P z .fst) g h e m

{` Products and inverses of interpreted words. `}
def fgauto_word_element_mul (S : Type) (dec : DecidableEquality S) (u v : SignedWord S)
  : Id (USym (fgauto_free_group S dec))
      (usym_mul (fgauto_free_group S dec) (fgauto_word_element S dec u) (fgauto_word_element S dec v))
      (fgauto_word_element S dec (append (SignedLetter S) u v))
  ≔ concat (USym (fgauto_free_group S dec))
      (usym_mul (fgauto_free_group S dec) (fgauto_word_element S dec u) (fgauto_word_element S dec v))
      (fgauto_word_element S dec (word_reduction S dec (append (SignedLetter S) u v)))
      (fgauto_word_element S dec (append (SignedLetter S) u v))
      (free_group_word_mul S dec (constructed_free_group_signature S dec) u v)
      (fgauto_word_element_reduction S dec (append (SignedLetter S) u v))

def fgauto_word_element_inverse (S : Type) (dec : DecidableEquality S) (u : SignedWord S)
  : Id (USym (fgauto_free_group S dec)) (usym_inv (fgauto_free_group S dec) (fgauto_word_element S dec u))
      (fgauto_word_element S dec (word_inverse S u))
  ≔ free_group_word_inverse S dec (constructed_free_group_signature S dec) u

def fgauto_word_element_red_path (S : Type) (dec : DecidableEquality S) (u v : SignedWord S)
  (p : Id (SignedWord S) (word_reduction S dec u) (word_reduction S dec v))
  : Id (USym (fgauto_free_group S dec)) (fgauto_word_element S dec u) (fgauto_word_element S dec v)
  ≔ concat (USym (fgauto_free_group S dec)) (fgauto_word_element S dec u)
      (fgauto_word_element S dec (word_reduction S dec u)) (fgauto_word_element S dec v)
      (inverse (USym (fgauto_free_group S dec)) (fgauto_word_element S dec (word_reduction S dec u))
        (fgauto_word_element S dec u) (fgauto_word_element_reduction S dec u))
      (concat (USym (fgauto_free_group S dec)) (fgauto_word_element S dec (word_reduction S dec u))
        (fgauto_word_element S dec (word_reduction S dec v)) (fgauto_word_element S dec v)
        (refl (fgauto_word_element S dec) p) (fgauto_word_element_reduction S dec v))

{` <gens> is a subgroup of F(S) containing the generators. `}
def fgauto_fg_subgroup_is_subgroup (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  : FgautoSubgroupSubset (fgauto_free_group S dec) (fgauto_fg_subgroup S dec gens)
  ≔ let F ≔ fgauto_free_group S dec in
    let P ≔ fgauto_fg_subgroup S dec gens in
    let back : (g : USym F) → P g .fst → FgautoInSubgroup S dec gens (fgauto_element_word S dec g)
      ≔ g m ↦ m in
    let fwd : (w : SignedWord S) → FgautoInSubgroup S dec gens w → P (fgauto_word_element S dec w) .fst
      ≔ w m ↦ fgauto_fg_subgroup_word S dec gens w .snd m in
    let ew ≔ fgauto_element_word S dec in
    (fgauto_subset_transport F P (fgauto_word_element S dec nil.) (usym_unit F) (refl (usym_unit F))
       (fwd nil. (fgauto_in_subgroup_unit S dec gens)),
     (g h mg mh ↦ fgauto_subset_transport F P (fgauto_word_element S dec (append (SignedLetter S) (ew g) (ew h)))
        (usym_mul F g h)
        (concat (USym F) (fgauto_word_element S dec (append (SignedLetter S) (ew g) (ew h)))
          (usym_mul F (fgauto_word_element S dec (ew g)) (fgauto_word_element S dec (ew h))) (usym_mul F g h)
          (inverse (USym F) (usym_mul F (fgauto_word_element S dec (ew g)) (fgauto_word_element S dec (ew h)))
            (fgauto_word_element S dec (append (SignedLetter S) (ew g) (ew h)))
            (fgauto_word_element_mul S dec (ew g) (ew h)))
          (refl ((a b ↦ usym_mul F a b) : USym F → USym F → USym F)
            (fgauto_element_word_element S dec g) (fgauto_element_word_element S dec h)))
        (fwd (append (SignedLetter S) (ew g) (ew h)) (fgauto_in_subgroup_mul S dec gens (ew g) (ew h) mg mh)),
      g mg ↦ fgauto_subset_transport F P (fgauto_word_element S dec (word_inverse S (ew g))) (usym_inv F g)
        (concat (USym F) (fgauto_word_element S dec (word_inverse S (ew g)))
          (usym_inv F (fgauto_word_element S dec (ew g))) (usym_inv F g)
          (inverse (USym F) (usym_inv F (fgauto_word_element S dec (ew g)))
            (fgauto_word_element S dec (word_inverse S (ew g))) (fgauto_word_element_inverse S dec (ew g)))
          (refl (usym_inv F) (fgauto_element_word_element S dec g)))
        (fwd (word_inverse S (ew g)) (fgauto_in_subgroup_inv S dec gens (ew g) mg))))

def fgauto_fg_subgroup_generator (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (g : SignedWord S) (m : FgautoMem (SignedWord S) g gens)
  : fgauto_fg_subgroup S dec gens (fgauto_word_element S dec g) .fst
  ≔ fgauto_fg_subgroup_word S dec gens g .snd (fgauto_in_subgroup_generator S dec gens g m)

{` It is the least such subgroup. `}
def fgauto_gen_eval_in (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (P : Subtypes (USym (fgauto_free_group S dec))) (hP : FgautoSubgroupSubset (fgauto_free_group S dec) P)
  (hg : (g : SignedWord S) → FgautoMem (SignedWord S) g gens → P (fgauto_word_element S dec g) .fst)
  (h : SignedWord (FgautoGen S gens)) : P (fgauto_word_element S dec (fgauto_gen_eval S gens h)) .fst
  ≔ let F ≔ fgauto_free_group S dec in
    match h [
    | nil. ↦ hP .fst
    | cons. x t ↦
      let ex ≔ fgauto_gen_letter_eval S gens x in
      let et ≔ fgauto_gen_eval S gens t in
      fgauto_subset_transport F P (usym_mul F (fgauto_word_element S dec ex) (fgauto_word_element S dec et))
        (fgauto_word_element S dec (append (SignedLetter S) ex et))
        (fgauto_word_element_mul S dec ex et)
        (hP .snd .fst (fgauto_word_element S dec ex) (fgauto_word_element S dec et)
          (match x [
           | inl. g ↦ hg (g .fst) (g .snd)
           | inr. g ↦ fgauto_subset_transport F P (usym_inv F (fgauto_word_element S dec (g .fst)))
               (fgauto_word_element S dec (word_inverse S (g .fst))) (fgauto_word_element_inverse S dec (g .fst))
               (hP .snd .snd (fgauto_word_element S dec (g .fst)) (hg (g .fst) (g .snd))) ])
          (fgauto_gen_eval_in S dec gens P hP hg t)) ]

def fgauto_fg_subgroup_least (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (P : Subtypes (USym (fgauto_free_group S dec))) (hP : FgautoSubgroupSubset (fgauto_free_group S dec) P)
  (hg : (g : SignedWord S) → FgautoMem (SignedWord S) g gens → P (fgauto_word_element S dec g) .fst)
  : Inclusion (USym (fgauto_free_group S dec)) (fgauto_fg_subgroup S dec gens) P
  ≔ g m ↦
    let F ≔ fgauto_free_group S dec in
    let w ≔ fgauto_element_word S dec g in
    mere_rec (Σ (SignedWord (FgautoGen S gens)) (h ↦
       Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h)) (word_reduction S dec w)))
      (P g .fst) (P g .snd)
      (z ↦ fgauto_subset_transport F P (fgauto_word_element S dec (fgauto_gen_eval S gens (z .fst))) g
        (concat (USym F) (fgauto_word_element S dec (fgauto_gen_eval S gens (z .fst))) (fgauto_word_element S dec w) g
          (fgauto_word_element_red_path S dec (fgauto_gen_eval S gens (z .fst)) w (z .snd))
          (fgauto_element_word_element S dec g))
        (fgauto_gen_eval_in S dec gens P hP hg (z .fst))) m

{` fggroups.tex:839 for F(S): a reduced word u represents an element of
   the subgroup H generated by gens (i.e. [u] in H) iff S(H) accepts u. `}
def fgauto_stallings_theorem (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (u : SignedWord S) (hu : IsReducedWord S u)
  : Product (fgauto_fg_subgroup S dec gens (fgauto_word_element S dec u) .fst → FgautoStallingsAccepts S dec gens u)
      (FgautoStallingsAccepts S dec gens u → fgauto_fg_subgroup S dec gens (fgauto_word_element S dec u) .fst)
  ≔ (m ↦ fgauto_member_accepted S dec gens u hu (fgauto_fg_subgroup_word S dec gens u .fst m),
     a ↦ fgauto_fg_subgroup_word S dec gens u .snd
       (fgauto_recognized_member S dec gens u (fgauto_stallings_accepts_recognizes S dec gens u .fst a)))

{` fggroups.tex:932 for F(S): membership of [u] in H is decidable. `}
def fgauto_generalized_word_problem_free_group (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (g : USym (fgauto_free_group S dec)) : Decidable (fgauto_fg_subgroup S dec gens g .fst)
  ≔ fgauto_generalized_word_problem S dec gens (fgauto_element_word S dec g)
