export "1155-fgauto-reachability"

{` Chapter 11, automata part 7: the theorem at fggroups.tex:924 (cosets of
   finitely generated subgroups of F(S) are exactly the languages of finite
   inverse automata, after reduction).

   As printed ("Let X ⊆ F(S). Then Y is a coset Hw ... iff there is a
   finite state inverse automaton whose language (after reduction) is Y")
   the statement has a typo (X/Y, we use X) and is false for automata with
   empty language: a coset Hw always contains rho(w), whereas the inverse
   automaton with two vertices and no edges, from one to the other, has
   empty language (fgauto_coset_automata_counterexample).  We prove the
   corrected statement: X is a coset Hw of a finitely generated H iff X is
   nonempty and is the reduced language of a finite inverse automaton
   (fgauto_coset_iff_inverse_automaton).

   For "=>" the automaton is the Stallings automaton of H with a hair
   reading w from the base (the bouquet of the generators plus the path of
   w, folded), whose terminal vertex is the image of the end of the hair;
   folding the same graph while tracking another vertex gives the same edges
   (fgauto_fold_ind2).  For "<=" H is generated by the spanning-tree loop
   words of the automaton (module 1155) and w is the tree word of the
   terminal vertex; determinism is not needed in this direction. `}

{` Folding while tracking two vertices. `}
def fgauto_fold_ind2_step (S : Type) (dec : DecidableEquality S)
  (P : List (FgautoEdge S (SignedWord S)) → SignedWord S → SignedWord S → Type)
  (hP : (E : List (FgautoEdge S (SignedWord S))) (b b' : SignedWord S) (c : FgautoConflict S (SignedWord S) E)
    → P E b b'
    → P (fgauto_map_edges S (SignedWord S) (SignedWord S) (fgauto_merge S dec (c .ctgt1) (c .ctgt2)) E)
        (fgauto_merge S dec (c .ctgt1) (c .ctgt2) b) (fgauto_merge S dec (c .ctgt1) (c .ctgt2) b'))
  (f : Nat)
  (recur : (E1 : List (FgautoEdge S (SignedWord S))) (b1 b1' : SignedWord S) → P E1 b1 b1'
    → P (fgauto_fold S dec f E1 b1 .fst) (fgauto_fold S dec f E1 b1 .snd) (fgauto_fold S dec f E1 b1' .snd))
  (E : List (FgautoEdge S (SignedWord S))) (b b' : SignedWord S) (h : P E b b')
  (d : Sum (FgautoConflict S (SignedWord S) E) (FgautoDeterministic S (SignedWord S) E))
  : P (fgauto_fold_step S dec (fgauto_fold S dec f) E b d .fst) (fgauto_fold_step S dec (fgauto_fold S dec f) E b d .snd)
      (fgauto_fold_step S dec (fgauto_fold S dec f) E b' d .snd)
  ≔ match d [
  | inr. _ ↦ h
  | inl. c ↦ recur (fgauto_map_edges S (SignedWord S) (SignedWord S) (fgauto_merge S dec (c .ctgt1) (c .ctgt2)) E)
      (fgauto_merge S dec (c .ctgt1) (c .ctgt2) b) (fgauto_merge S dec (c .ctgt1) (c .ctgt2) b') (hP E b b' c h) ]

def fgauto_fold_ind2 (S : Type) (dec : DecidableEquality S)
  (P : List (FgautoEdge S (SignedWord S)) → SignedWord S → SignedWord S → Type)
  (hP : (E : List (FgautoEdge S (SignedWord S))) (b b' : SignedWord S) (c : FgautoConflict S (SignedWord S) E)
    → P E b b'
    → P (fgauto_map_edges S (SignedWord S) (SignedWord S) (fgauto_merge S dec (c .ctgt1) (c .ctgt2)) E)
        (fgauto_merge S dec (c .ctgt1) (c .ctgt2) b) (fgauto_merge S dec (c .ctgt1) (c .ctgt2) b'))
  (fuel : Nat) (E : List (FgautoEdge S (SignedWord S))) (b b' : SignedWord S) (h : P E b b')
  : P (fgauto_fold S dec fuel E b .fst) (fgauto_fold S dec fuel E b .snd) (fgauto_fold S dec fuel E b' .snd)
  ≔ match fuel [
  | zero. ↦ h
  | suc. f ↦ fgauto_fold_ind2_step S dec P hP f (fgauto_fold_ind2 S dec P hP f) E b b' h
      (fgauto_conflict_search S (SignedWord S) dec (signed_word_decidable_equality S dec) E) ]

{` The hair: the path reading w from the vertex p, its vertices named by
   the prefixes read so far. `}
def fgauto_hair (S : Type) (p : SignedWord S) (w : SignedWord S) : List (FgautoEdge S (SignedWord S))
  ≔ match w [
  | nil. ↦ nil.
  | cons. x t ↦ cons. (p, x, append (SignedLetter S) p (cons. x nil.)) (fgauto_hair S (append (SignedLetter S) p (cons. x nil.)) t) ]

def fgauto_hair_run (S : Type) (p : SignedWord S) (w : SignedWord S)
  : FgautoRun S (SignedWord S) (fgauto_hair S p w) p w (append (SignedLetter S) p w)
  ≔ match w [
  | nil. ↦ fgauto_wsym S (append (SignedLetter S) p nil.) p (append_nil (SignedLetter S) p)
  | cons. x t ↦
    let P ≔ append (SignedLetter S) p (cons. x nil.) in
    (P, (fgauto_step_head S (SignedWord S) (p, x, P) (fgauto_hair S P t),
      fgauto_run_end S (SignedWord S) (cons. (p, x, P) (fgauto_hair S P t)) P t (append (SignedLetter S) P t)
        (append (SignedLetter S) p (cons. x t)) (append_assoc (SignedLetter S) p (cons. x nil.) t)
        (fgauto_run_mono S (SignedWord S) (fgauto_hair S P t) (cons. (p, x, P) (fgauto_hair S P t))
          (p0 x0 q0 s ↦ inr. s) P t (append (SignedLetter S) P t) (fgauto_hair_run S P t)))) ]

def fgauto_hair_inv (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (p : SignedWord S)
  (w : SignedWord S) : FgautoEdgeInv S dec gens (fgauto_hair S p w)
  ≔ p0 x0 q0 s ↦ match w [
  | nil. ↦ match s []
  | cons. x t ↦
    let P ≔ append (SignedLetter S) p (cons. x nil.) in
    match s [
    | inl. e ↦ fgauto_same_coset_transport S dec gens P (append (SignedLetter S) p0 (cons. x0 nil.)) P q0
        (refl ((u v ↦ append (SignedLetter S) u (cons. v nil.)) : SignedWord S → SignedLetter S → SignedWord S)
          (fgauto_wsym S p0 p (e .fst)) (inverse (SignedLetter S) x0 x (e .snd .fst)))
        (fgauto_wsym S q0 P (e .snd .snd)) (fgauto_same_coset_refl S dec gens P)
    | inr. s' ↦ fgauto_hair_inv S dec gens P t p0 x0 q0 s' ] ]

def fgauto_append_inv (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (E E' : List (FgautoEdge S (SignedWord S))) (h : FgautoEdgeInv S dec gens E) (h' : FgautoEdgeInv S dec gens E')
  : FgautoEdgeInv S dec gens (append (FgautoEdge S (SignedWord S)) E E')
  ≔ p x q s ↦ match fgauto_step_append_split S (SignedWord S) E E' p x q s [ inl. k ↦ h p x q k | inr. k ↦ h' p x q k ]

{` The coset automaton of H = <gens> and w. `}
def fgauto_coset_graph (S : Type) (gens : List (SignedWord S)) (w : SignedWord S) : List (FgautoEdge S (SignedWord S))
  ≔ fgauto_symmetrize S (SignedWord S) (append (FgautoEdge S (SignedWord S)) (fgauto_petals S gens) (fgauto_hair S nil. w))

def fgauto_coset_fuel (S : Type) (gens : List (SignedWord S)) (w : SignedWord S) : Nat
  ≔ length (SignedWord S) (fgauto_endpoints S (SignedWord S) (fgauto_coset_graph S gens w))

def fgauto_coset_edges (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : List (FgautoEdge S (SignedWord S))
  ≔ fgauto_fold S dec (fgauto_coset_fuel S gens w) (fgauto_coset_graph S gens w) nil. .fst

def fgauto_coset_base (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : SignedWord S
  ≔ fgauto_fold S dec (fgauto_coset_fuel S gens w) (fgauto_coset_graph S gens w) nil. .snd

def fgauto_coset_term (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : SignedWord S
  ≔ fgauto_fold S dec (fgauto_coset_fuel S gens w) (fgauto_coset_graph S gens w) w .snd

def fgauto_coset_deterministic (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : FgautoDeterministic S (SignedWord S) (fgauto_coset_edges S dec gens w)
  ≔ fgauto_fold_deterministic S dec (fgauto_coset_fuel S gens w) (fgauto_coset_graph S gens w) nil.
      (fgauto_endpoints S (SignedWord S) (fgauto_coset_graph S gens w))
      (fgauto_endpoints_in S (SignedWord S) (fgauto_coset_graph S gens w))
      (le_refl (fgauto_coset_fuel S gens w))

def fgauto_coset_symmetric (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : FgautoSymmetric S (SignedWord S) (fgauto_coset_edges S dec gens w)
  ≔ fgauto_fold_ind S dec (E b ↦ FgautoSymmetric S (SignedWord S) E)
      (E b c h ↦ fgauto_map_symmetric S (SignedWord S) (SignedWord S) (fgauto_merge S dec (c .ctgt1) (c .ctgt2)) E h)
      (fgauto_coset_fuel S gens w) (fgauto_coset_graph S gens w) nil.
      (fgauto_symmetrize_symmetric S (SignedWord S)
        (append (FgautoEdge S (SignedWord S)) (fgauto_petals S gens) (fgauto_hair S nil. w)))

def fgauto_coset_graph_inv (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : FgautoEdgeInv S dec gens (fgauto_coset_graph S gens w)
  ≔ fgauto_symmetrize_inv S dec gens (append (FgautoEdge S (SignedWord S)) (fgauto_petals S gens) (fgauto_hair S nil. w))
      (fgauto_append_inv S dec gens (fgauto_petals S gens) (fgauto_hair S nil. w)
        (fgauto_petals_inv S dec gens gens (fgauto_in_subgroup_generator S dec gens))
        (fgauto_hair_inv S dec gens nil. w))

{` Invariant: edges respect cosets, base in H, terminal in the coset H w. `}
def FgautoCosetAutInv (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  (E : List (FgautoEdge S (SignedWord S))) (b t : SignedWord S) : Type
  ≔ Product (FgautoEdgeInv S dec gens E)
      (Product (FgautoSameCoset S dec gens b nil.) (FgautoSameCoset S dec gens t w))

def fgauto_coset_aut_inv (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : FgautoCosetAutInv S dec gens w (fgauto_coset_edges S dec gens w) (fgauto_coset_base S dec gens w)
      (fgauto_coset_term S dec gens w)
  ≔ fgauto_fold_ind2 S dec (FgautoCosetAutInv S dec gens w)
      (E b t c h ↦
        let hab ≔ fgauto_conflict_coset S dec gens E (h .fst) c in
        let f ≔ fgauto_merge S dec (c .ctgt1) (c .ctgt2) in
        (fgauto_merge_inv S dec gens E (h .fst) (c .ctgt1) (c .ctgt2) hab,
         (fgauto_same_coset_trans S dec gens (f b) b nil. (fgauto_merge_coset S dec gens (c .ctgt1) (c .ctgt2) b hab)
            (h .snd .fst),
          fgauto_same_coset_trans S dec gens (f t) t w (fgauto_merge_coset S dec gens (c .ctgt1) (c .ctgt2) t hab)
            (h .snd .snd))))
      (fgauto_coset_fuel S gens w) (fgauto_coset_graph S gens w) nil. w
      (fgauto_coset_graph_inv S dec gens w,
       (fgauto_same_coset_refl S dec gens nil., fgauto_same_coset_refl S dec gens w))

def fgauto_coset_loops (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : FgautoGeneratorLoops S gens (fgauto_coset_edges S dec gens w) (fgauto_coset_base S dec gens w)
  ≔ fgauto_fold_ind S dec (FgautoGeneratorLoops S gens)
      (E b c h g m ↦ fgauto_run_map S (SignedWord S) (SignedWord S) (fgauto_merge S dec (c .ctgt1) (c .ctgt2)) E b g b (h g m))
      (fgauto_coset_fuel S gens w) (fgauto_coset_graph S gens w) nil.
      (g m ↦ fgauto_run_mono S (SignedWord S) (fgauto_petals S gens) (fgauto_coset_graph S gens w)
        (p0 x0 q0 s ↦ fgauto_step_append_left S (SignedWord S)
          (append (FgautoEdge S (SignedWord S)) (fgauto_petals S gens) (fgauto_hair S nil. w))
          (fgauto_reverse_edges S (SignedWord S) (append (FgautoEdge S (SignedWord S)) (fgauto_petals S gens) (fgauto_hair S nil. w)))
          p0 x0 q0 (fgauto_step_append_left S (SignedWord S) (fgauto_petals S gens) (fgauto_hair S nil. w) p0 x0 q0 s))
        nil. g nil. (fgauto_petals_loop S gens g m))

def fgauto_coset_hair_run (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : FgautoRun S (SignedWord S) (fgauto_coset_edges S dec gens w) (fgauto_coset_base S dec gens w) w
      (fgauto_coset_term S dec gens w)
  ≔ fgauto_fold_ind2 S dec (E b t ↦ FgautoRun S (SignedWord S) E b w t)
      (E b t c h ↦ fgauto_run_map S (SignedWord S) (SignedWord S) (fgauto_merge S dec (c .ctgt1) (c .ctgt2)) E b w t h)
      (fgauto_coset_fuel S gens w) (fgauto_coset_graph S gens w) nil. w
      (fgauto_run_mono S (SignedWord S) (fgauto_hair S nil. w) (fgauto_coset_graph S gens w)
        (p0 x0 q0 s ↦ fgauto_step_append_left S (SignedWord S)
          (append (FgautoEdge S (SignedWord S)) (fgauto_petals S gens) (fgauto_hair S nil. w))
          (fgauto_reverse_edges S (SignedWord S) (append (FgautoEdge S (SignedWord S)) (fgauto_petals S gens) (fgauto_hair S nil. w)))
          p0 x0 q0 (fgauto_step_append_right S (SignedWord S) (fgauto_petals S gens) (fgauto_hair S nil. w) p0 x0 q0 s))
        nil. w w (fgauto_hair_run S nil. w))

{` Runs between coset-compatible endpoints. `}
def fgauto_run_coset_member (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (E : List (FgautoEdge S (SignedWord S))) (h : FgautoEdgeInv S dec gens E) (b t w : SignedWord S)
  (hb : FgautoSameCoset S dec gens b nil.) (ht : FgautoSameCoset S dec gens t w) (u : SignedWord S)
  (r : FgautoRun S (SignedWord S) E b u t) : FgautoSameCoset S dec gens u w
  ≔ let ib ≔ word_inverse S b in
    let iw ≔ word_inverse S w in
    let buw ≔ append (SignedLetter S) (append (SignedLetter S) b u) iw in
    fgauto_in_subgroup_red S dec gens (append (SignedLetter S) ib buw) (append (SignedLetter S) u iw)
      (calc
        word_reduction S dec (append (SignedLetter S) ib buw)
        = word_reduction S dec (append (SignedLetter S) ib (append (SignedLetter S) b (append (SignedLetter S) u iw)))
          by refl ((z ↦ word_reduction S dec (append (SignedLetter S) ib z)) : SignedWord S → SignedWord S)
               (append_assoc (SignedLetter S) b u iw)
        = word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) ib b) (append (SignedLetter S) u iw))
          by fgauto_wsym S
               (word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) ib b) (append (SignedLetter S) u iw)))
               (word_reduction S dec (append (SignedLetter S) ib (append (SignedLetter S) b (append (SignedLetter S) u iw))))
               (fgauto_red_assoc S dec ib b (append (SignedLetter S) u iw))
        = word_reduction S dec (append (SignedLetter S) u iw)
          by fgauto_red_drop_left S dec (append (SignedLetter S) ib b) (append (SignedLetter S) u iw)
               (fgauto_red_inverse_left S dec b) ∎)
      (fgauto_in_subgroup_mul S dec gens ib buw
        (fgauto_in_subgroup_inv S dec gens b (fgauto_same_coset_unit_member S dec gens b hb))
        (fgauto_same_coset_trans S dec gens (append (SignedLetter S) b u) t w (fgauto_run_coset S dec gens E h b u t r) ht))

{` Reduction of h w where rho(h) = rho(u w^-1). `}
def fgauto_red_coset_word (S : Type) (dec : DecidableEquality S) (h u w : SignedWord S)
  (p : Id (SignedWord S) (word_reduction S dec h) (word_reduction S dec (append (SignedLetter S) u (word_inverse S w))))
  : Id (SignedWord S) (word_reduction S dec (append (SignedLetter S) h w)) (word_reduction S dec u)
  ≔ let iw ≔ word_inverse S w in
    calc
      word_reduction S dec (append (SignedLetter S) h w)
      = word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) u iw) w)
        by fgauto_red_congr_left S dec h (append (SignedLetter S) u iw) w p
      = word_reduction S dec (append (SignedLetter S) u (append (SignedLetter S) iw w))
        by fgauto_red_assoc S dec u iw w
      = word_reduction S dec u
        by fgauto_red_drop_right S dec u (append (SignedLetter S) iw w) (fgauto_red_inverse_left S dec w) ∎

{` The reduced language of the coset automaton is H w. `}
def FgautoCosetAccepts (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w u : SignedWord S) : Type
  ≔ Id (Sum Unit (SignedWord S))
      (fgauto_delta S (SignedWord S) dec (signed_word_decidable_equality S dec) (fgauto_coset_edges S dec gens w)
        (fgauto_coset_base S dec gens w) u)
      (inr. (fgauto_coset_term S dec gens w))

def fgauto_coset_accepts_member (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w u : SignedWord S)
  (a : FgautoCosetAccepts S dec gens w u) : FgautoSameCoset S dec gens u w
  ≔ let I ≔ fgauto_coset_aut_inv S dec gens w in
    fgauto_run_coset_member S dec gens (fgauto_coset_edges S dec gens w) (I .fst) (fgauto_coset_base S dec gens w)
      (fgauto_coset_term S dec gens w) w (I .snd .fst) (I .snd .snd) u
      (fgauto_delta_sound S (SignedWord S) dec (signed_word_decidable_equality S dec) (fgauto_coset_edges S dec gens w)
        (fgauto_coset_base S dec gens w) u (fgauto_coset_term S dec gens w) a)

def fgauto_coset_member_accepts (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w u : SignedWord S)
  (hu : IsReducedWord S u) (m : FgautoSameCoset S dec gens u w) : FgautoCosetAccepts S dec gens w u
  ≔ let E ≔ fgauto_coset_edges S dec gens w in
    let b ≔ fgauto_coset_base S dec gens w in
    let t ≔ fgauto_coset_term S dec gens w in
    let hs ≔ fgauto_coset_symmetric S dec gens w in
    let hd ≔ fgauto_coset_deterministic S dec gens w in
    let uw ≔ append (SignedLetter S) u (word_inverse S w) in
    mere_rec (Σ (SignedWord (FgautoGen S gens)) (h ↦
       Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h)) (word_reduction S dec uw)))
      (FgautoCosetAccepts S dec gens w u)
      (fgauto_vertex_option_set S dec
        (fgauto_delta S (SignedWord S) dec (signed_word_decidable_equality S dec) E b u) (inr. t))
      (z ↦
        let hw ≔ append (SignedLetter S) (fgauto_gen_eval S gens (z .fst)) w in
        fgauto_delta_det S (SignedWord S) dec (signed_word_decidable_equality S dec) E hd b u t
          (fgauto_run_word S (SignedWord S) E b (word_reduction S dec hw) u t
            (fgauto_wtrans S (word_reduction S dec hw) (word_reduction S dec u) u
              (fgauto_red_coset_word S dec (fgauto_gen_eval S gens (z .fst)) u w (z .snd))
              (word_reduction_of_reduced S dec u hu))
            (fgauto_run_reduction S (SignedWord S) dec E hs hd b hw t
              (fgauto_run_append S (SignedWord S) E b (fgauto_gen_eval S gens (z .fst)) b w t
                (fgauto_gen_eval_run S gens E b hs (fgauto_coset_loops S dec gens w) (z .fst))
                (fgauto_coset_hair_run S dec gens w))))) m

{` Inverse automata with an initial and a terminal vertex, and their
   language after reduction rho(L(A)) (as a predicate on reduced words). `}
def FgautoInverseAutomaton (S : Type) : Type ≔ sig (
  avert : Type,
  adec : DecidableEquality avert,
  aedges : List (FgautoEdge S avert),
  ainit : avert,
  aterm : avert,
  asym : FgautoSymmetric S avert aedges,
  adet : FgautoDeterministic S avert aedges)

def FgautoReducedLanguage (S : Type) (dec : DecidableEquality S) (A : FgautoInverseAutomaton S) (u : SignedWord S) : Type
  ≔ Mere (Σ (SignedWord S) (w ↦ Product (FgautoRun S (A .avert) (A .aedges) (A .ainit) w (A .aterm))
       (Id (SignedWord S) (word_reduction S dec w) u)))

{` Subsets of F(S), as predicates on reduced words. `}
def FgautoFreeSubset (S : Type) : Type ≔ Subtypes (ReducedWord S)

def FgautoIsCoset (S : Type) (dec : DecidableEquality S) (X : FgautoFreeSubset S) : Type
  ≔ Mere (Σ (List (SignedWord S)) (gens ↦ Σ (SignedWord S) (w ↦
       (u : ReducedWord S) → Product (X u .fst → FgautoSameCoset S dec gens (u .fst) w)
         (FgautoSameCoset S dec gens (u .fst) w → X u .fst))))

def FgautoIsInverseAutomatonLanguage (S : Type) (dec : DecidableEquality S) (X : FgautoFreeSubset S) : Type
  ≔ Mere (Σ (FgautoInverseAutomaton S) (A ↦
       (u : ReducedWord S) → Product (X u .fst → FgautoReducedLanguage S dec A (u .fst))
         (FgautoReducedLanguage S dec A (u .fst) → X u .fst)))

def FgautoNonempty (S : Type) (X : FgautoFreeSubset S) : Type ≔ Mere (Σ (ReducedWord S) (u ↦ X u .fst))

{` The coset automaton as an inverse automaton; its reduced language is H w. `}
def fgauto_coset_automaton (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (w : SignedWord S)
  : FgautoInverseAutomaton S
  ≔ (SignedWord S, signed_word_decidable_equality S dec, fgauto_coset_edges S dec gens w, fgauto_coset_base S dec gens w,
     fgauto_coset_term S dec gens w, fgauto_coset_symmetric S dec gens w, fgauto_coset_deterministic S dec gens w)

def fgauto_coset_automaton_language (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (w : SignedWord S) (u : SignedWord S) (hu : IsReducedWord S u)
  : Product (FgautoSameCoset S dec gens u w → FgautoReducedLanguage S dec (fgauto_coset_automaton S dec gens w) u)
      (FgautoReducedLanguage S dec (fgauto_coset_automaton S dec gens w) u → FgautoSameCoset S dec gens u w)
  ≔ let E ≔ fgauto_coset_edges S dec gens w in
    let b ≔ fgauto_coset_base S dec gens w in
    let t ≔ fgauto_coset_term S dec gens w in
    let L ≔ (v : SignedWord S) ↦ Product (FgautoRun S (SignedWord S) E b v t) (Id (SignedWord S) (word_reduction S dec v) u) in
    (m ↦ mere (Σ (SignedWord S) L)
       (u, (fgauto_delta_sound S (SignedWord S) dec (signed_word_decidable_equality S dec) E b u t
             (fgauto_coset_member_accepts S dec gens w u hu m),
            word_reduction_of_reduced S dec u hu)),
     l ↦ mere_rec (Σ (SignedWord S) L) (FgautoSameCoset S dec gens u w)
       (fgauto_in_subgroup_prop S dec gens (append (SignedLetter S) u (word_inverse S w)))
       (z ↦ fgauto_coset_accepts_member S dec gens w u
         (fgauto_delta_det S (SignedWord S) dec (signed_word_decidable_equality S dec) E
           (fgauto_coset_deterministic S dec gens w) b u t
           (fgauto_run_word S (SignedWord S) E b (word_reduction S dec (z .fst)) u t (z .snd .snd)
             (fgauto_run_reduction S (SignedWord S) dec E (fgauto_coset_symmetric S dec gens w)
               (fgauto_coset_deterministic S dec gens w) b (z .fst) t (z .snd .fst))))) l)

{` "=>": a coset of a finitely generated subgroup is the reduced language of
   a finite inverse automaton (and nonempty). `}
def fgauto_coset_to_automaton (S : Type) (dec : DecidableEquality S) (X : FgautoFreeSubset S)
  (h : FgautoIsCoset S dec X) : Product (FgautoNonempty S X) (FgautoIsInverseAutomatonLanguage S dec X)
  ≔ let T ≔ Σ (List (SignedWord S)) (gens ↦ Σ (SignedWord S) (w ↦
       (u : ReducedWord S) → Product (X u .fst → FgautoSameCoset S dec gens (u .fst) w)
         (FgautoSameCoset S dec gens (u .fst) w → X u .fst))) in
    (mere_rec T (FgautoNonempty S X) (mere_isprop (Σ (ReducedWord S) (u ↦ X u .fst)))
       (c ↦
         let gens ≔ c .fst in
         let w ≔ c .snd .fst in
         let rw : ReducedWord S ≔ (word_reduction S dec w, word_reduction_reduced S dec w) in
         mere (Σ (ReducedWord S) (u ↦ X u .fst))
           (rw, c .snd .snd rw .snd
             (fgauto_in_subgroup_red S dec gens nil. (append (SignedLetter S) (word_reduction S dec w) (word_inverse S w))
               (fgauto_wsym S (word_reduction S dec (append (SignedLetter S) (word_reduction S dec w) (word_inverse S w))) nil.
                 (fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) (word_reduction S dec w) (word_inverse S w)))
                   (word_reduction S dec (append (SignedLetter S) w (word_inverse S w))) nil.
                   (fgauto_wsym S (word_reduction S dec (append (SignedLetter S) w (word_inverse S w)))
                     (word_reduction S dec (append (SignedLetter S) (word_reduction S dec w) (word_inverse S w)))
                     (word_reduction_append_left S dec w (word_inverse S w)))
                   (fgauto_red_inverse_right S dec w)))
               (fgauto_in_subgroup_unit S dec gens)))) h,
     mere_rec T (FgautoIsInverseAutomatonLanguage S dec X)
       (mere_isprop (Σ (FgautoInverseAutomaton S) (A ↦
         (u : ReducedWord S) → Product (X u .fst → FgautoReducedLanguage S dec A (u .fst))
           (FgautoReducedLanguage S dec A (u .fst) → X u .fst))))
       (c ↦
         let gens ≔ c .fst in
         let w ≔ c .snd .fst in
         mere (Σ (FgautoInverseAutomaton S) (A ↦
           (u : ReducedWord S) → Product (X u .fst → FgautoReducedLanguage S dec A (u .fst))
             (FgautoReducedLanguage S dec A (u .fst) → X u .fst)))
           (fgauto_coset_automaton S dec gens w,
            u ↦ (x ↦ fgauto_coset_automaton_language S dec gens w (u .fst) (u .snd) .fst (c .snd .snd u .fst x),
                 l ↦ c .snd .snd u .snd (fgauto_coset_automaton_language S dec gens w (u .fst) (u .snd) .snd l)))) h)

{` "<=": the nonempty reduced language of a finite inverse automaton is a
   coset H t_term of the subgroup generated by the loop words. `}
def fgauto_automaton_language_coset (S : Type) (dec : DecidableEquality S) (A : FgautoInverseAutomaton S)
  (ne : Mere (Σ (SignedWord S) (w ↦ FgautoRun S (A .avert) (A .aedges) (A .ainit) w (A .aterm))))
  (u : SignedWord S) (hu : IsReducedWord S u)
  : Product (FgautoReducedLanguage S dec A u
      → FgautoSameCoset S dec (fgauto_loop_gens S (A .avert) (A .adec) (A .aedges) (A .ainit)) u
          (fgauto_tree_word S (A .avert) (A .adec) (A .aedges) (A .ainit) (A .aterm)))
      (FgautoSameCoset S dec (fgauto_loop_gens S (A .avert) (A .adec) (A .aedges) (A .ainit)) u
          (fgauto_tree_word S (A .avert) (A .adec) (A .aedges) (A .ainit) (A .aterm))
        → FgautoReducedLanguage S dec A u)
  ≔ let V ≔ A .avert in
    let E ≔ A .aedges in
    let i ≔ A .ainit in
    let t ≔ A .aterm in
    let gens ≔ fgauto_loop_gens S V (A .adec) E i in
    let tt ≔ fgauto_tree_word S V (A .adec) E i t in
    let L ≔ (v : SignedWord S) ↦ Product (FgautoRun S V E i v t) (Id (SignedWord S) (word_reduction S dec v) u) in
    (l ↦ mere_rec (Σ (SignedWord S) L) (FgautoSameCoset S dec gens u tt)
       (fgauto_in_subgroup_prop S dec gens (append (SignedLetter S) u (word_inverse S tt)))
       (z ↦ fgauto_in_subgroup_red S dec gens (append (SignedLetter S) (z .fst) (word_inverse S tt))
         (append (SignedLetter S) u (word_inverse S tt))
         (fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) (z .fst) (word_inverse S tt)))
           (word_reduction S dec (append (SignedLetter S) (word_reduction S dec (z .fst)) (word_inverse S tt)))
           (word_reduction S dec (append (SignedLetter S) u (word_inverse S tt)))
           (word_reduction_append_left S dec (z .fst) (word_inverse S tt))
           (refl ((y ↦ word_reduction S dec (append (SignedLetter S) y (word_inverse S tt))) : SignedWord S → SignedWord S)
             (z .snd .snd)))
         (fgauto_loop_gens_coset S V dec (A .adec) E i (z .fst) t (z .snd .fst))) l,
     m ↦ match fgauto_mem_decide V (A .adec) t (fgauto_reached S V (A .adec) E i) [
       | inr. nt ↦ match mere_rec (Σ (SignedWord S) (w ↦ FgautoRun S V E i w t)) Empty empty_prop
           (z ↦ nt (fgauto_reach_complete S V (A .adec) E i (z .fst) t (z .snd))) ne []
       | inl. mt ↦ mere_rec (Σ (SignedWord (FgautoGen S gens)) (h ↦
           Id (SignedWord S) (word_reduction S dec (fgauto_gen_eval S gens h))
             (word_reduction S dec (append (SignedLetter S) u (word_inverse S tt)))))
           (FgautoReducedLanguage S dec A u) (mere_isprop (Σ (SignedWord S) L))
           (z ↦ mere (Σ (SignedWord S) L)
             (append (SignedLetter S) (fgauto_gen_eval S gens (z .fst)) tt,
              (fgauto_run_append S V E i (fgauto_gen_eval S gens (z .fst)) i tt t
                 (fgauto_gen_eval_run_at S V gens E i (A .asym) (fgauto_loop_gens_loop S V (A .adec) E i (A .asym)) (z .fst))
                 (fgauto_tree_word_run S V (A .adec) E i t mt),
               fgauto_wtrans S (word_reduction S dec (append (SignedLetter S) (fgauto_gen_eval S gens (z .fst)) tt))
                 (word_reduction S dec u) u
                 (fgauto_red_coset_word S dec (fgauto_gen_eval S gens (z .fst)) u tt (z .snd))
                 (word_reduction_of_reduced S dec u hu)))) m ])

def fgauto_automaton_to_coset (S : Type) (dec : DecidableEquality S) (X : FgautoFreeSubset S)
  (ne : FgautoNonempty S X) (h : FgautoIsInverseAutomatonLanguage S dec X) : FgautoIsCoset S dec X
  ≔ let C ≔ Σ (List (SignedWord S)) (gens ↦ Σ (SignedWord S) (w ↦
       (u : ReducedWord S) → Product (X u .fst → FgautoSameCoset S dec gens (u .fst) w)
         (FgautoSameCoset S dec gens (u .fst) w → X u .fst))) in
    mere_rec (Σ (FgautoInverseAutomaton S) (A ↦
         (u : ReducedWord S) → Product (X u .fst → FgautoReducedLanguage S dec A (u .fst))
           (FgautoReducedLanguage S dec A (u .fst) → X u .fst)))
      (FgautoIsCoset S dec X) (mere_isprop C)
      (Ah ↦
        let A ≔ Ah .fst in
        let hx ≔ Ah .snd in
        let R ≔ Σ (SignedWord S) (w ↦ FgautoRun S (A .avert) (A .aedges) (A .ainit) w (A .aterm)) in
        let nerun : Mere R
          ≔ mere_rec (Σ (ReducedWord S) (u ↦ X u .fst)) (Mere R) (mere_isprop R)
              (z ↦ mere_rec (Σ (SignedWord S) (w ↦ Product (FgautoRun S (A .avert) (A .aedges) (A .ainit) w (A .aterm))
                    (Id (SignedWord S) (word_reduction S dec w) (z .fst .fst))))
                  (Mere R) (mere_isprop R) (y ↦ mere R (y .fst, y .snd .fst)) (hx (z .fst) .fst (z .snd))) ne in
        mere C (fgauto_loop_gens S (A .avert) (A .adec) (A .aedges) (A .ainit),
          (fgauto_tree_word S (A .avert) (A .adec) (A .aedges) (A .ainit) (A .aterm),
           u ↦ (x ↦ fgauto_automaton_language_coset S dec A nerun (u .fst) (u .snd) .fst (hx u .fst x),
                c ↦ hx u .snd (fgauto_automaton_language_coset S dec A nerun (u .fst) (u .snd) .snd c))))) h

{` fggroups.tex:924, corrected: X ⊆ F(S) is a coset H w of a finitely
   generated subgroup H iff X is nonempty and is the reduced language of a
   finite inverse automaton. `}
def fgauto_coset_iff_inverse_automaton (S : Type) (dec : DecidableEquality S) (X : FgautoFreeSubset S)
  : Product (FgautoIsCoset S dec X → Product (FgautoNonempty S X) (FgautoIsInverseAutomatonLanguage S dec X))
      (Product (FgautoNonempty S X) (FgautoIsInverseAutomatonLanguage S dec X) → FgautoIsCoset S dec X)
  ≔ (fgauto_coset_to_automaton S dec X, h ↦ fgauto_automaton_to_coset S dec X (h .fst) (h .snd))

{` The printed statement fails: an inverse automaton with empty language. `}
def fgauto_two_points_decidable_equality : DecidableEquality (Sum Unit Unit)
  ≔ sum_decidable_equality Unit Unit (x y ↦ inl. (unit_prop x y)) (x y ↦ inl. (unit_prop x y))

def fgauto_empty_inverse_automaton (S : Type) : FgautoInverseAutomaton S
  ≔ (Sum Unit Unit, fgauto_two_points_decidable_equality, nil., inl. star., inr. star.,
     (p x q s ↦ match s []), (p x q q' s s' ↦ match s []))

def fgauto_empty_automaton_no_run (S : Type) (w : SignedWord S)
  (r : FgautoRun S (Sum Unit Unit) nil. (inl. star.) w (inr. star.)) : Empty
  ≔ match w [
  | nil. ↦ sum_encode Unit Unit (inl. star.) (inr. star.) r
  | cons. x w' ↦ match r .snd .fst [] ]

def fgauto_empty_inverse_automaton_language (S : Type) (dec : DecidableEquality S) (u : SignedWord S)
  : Not (FgautoReducedLanguage S dec (fgauto_empty_inverse_automaton S) u)
  ≔ l ↦ mere_rec (Σ (SignedWord S) (w ↦ Product (FgautoRun S (Sum Unit Unit) nil. (inl. star.) w (inr. star.))
           (Id (SignedWord S) (word_reduction S dec w) u)))
      Empty empty_prop
      (z ↦ fgauto_empty_automaton_no_run S (z .fst) (z .snd .fst)) l

def fgauto_empty_subset (S : Type) : FgautoFreeSubset S ≔ u ↦ (Empty, empty_prop)

def fgauto_coset_automata_counterexample (S : Type) (dec : DecidableEquality S)
  : Product (FgautoIsInverseAutomatonLanguage S dec (fgauto_empty_subset S))
      (Not (FgautoIsCoset S dec (fgauto_empty_subset S)))
  ≔ (mere (Σ (FgautoInverseAutomaton S) (A ↦
         (u : ReducedWord S) → Product (fgauto_empty_subset S u .fst → FgautoReducedLanguage S dec A (u .fst))
           (FgautoReducedLanguage S dec A (u .fst) → fgauto_empty_subset S u .fst)))
       (fgauto_empty_inverse_automaton S,
        u ↦ (e ↦ match e [], l ↦ fgauto_empty_inverse_automaton_language S dec (u .fst) l)),
     c ↦ mere_rec (Σ (ReducedWord S) (u ↦ fgauto_empty_subset S u .fst)) Empty empty_prop (z ↦ z .snd)
       (fgauto_coset_to_automaton S dec (fgauto_empty_subset S) c .fst))
