export "1157-fgauto-stallings-vertices"

{` Chapter 11, automata part 9: the theorem at fggroups.tex:844.  For H
   generated by gens: H has finite index in F(S) iff S(H) is total, and then
   the index is the number of vertices of S(H).

   The index is the number of right cosets H w: FgautoRightCosets is the set
   quotient of words by H u = H v (i.e. u v^-1 in H), and H has finite index
   when this set is finite (IsFinite, def:is-finite).  (Words modulo the
   coset relation are the right cosets of H in F(S), since words modulo
   reduction are F(S), module 862.)  S(H) is total when every vertex has an
   outgoing x-edge for every signed letter x.

   "<=" and the count: in a total S(H), running from the base gives a map
   from words to vertices that identifies exactly the words of the same
   coset and hits every vertex (all vertices are reachable), hence
   cosets ~ vertices ~ Fin(#vertices).  "=>": if a vertex p has no x-edge,
   with t a word leading from the base to p, the cosets H t x^n are pairwise
   distinct: H t x^i = H t x^j (i /= j) would make the nonempty power
   rho(x^i x^-j) of x or x-bar a loop at p, which requires an x-edge at p.
   Finitely many cosets contradict this by the pigeonhole principle. `}

{` Right cosets and finite index. `}
def fgauto_coset_relation (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  : EquivalenceRelation (SignedWord S)
  ≔ (u v ↦ (FgautoSameCoset S dec gens u v, fgauto_in_subgroup_prop S dec gens (append (SignedLetter S) u (word_inverse S v))),
     fgauto_same_coset_refl S dec gens, fgauto_same_coset_sym S dec gens, fgauto_same_coset_trans S dec gens)

def FgautoRightCosets (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) : Type
  ≔ Quotient (SignedWord S) (fgauto_coset_relation S dec gens)

def fgauto_right_coset (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (u : SignedWord S)
  : FgautoRightCosets S dec gens
  ≔ quotient_class (SignedWord S) (fgauto_coset_relation S dec gens) u

def FgautoFiniteIndex (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) : Type
  ≔ IsFinite (FgautoRightCosets S dec gens)

def fgauto_index (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) (h : FgautoFiniteIndex S dec gens) : Nat
  ≔ cardinality (FgautoRightCosets S dec gens) h

{` Totality. `}
def FgautoTotal (S V : Type) (E : List (FgautoEdge S V)) (Vs : List V) : Type
  ≔ (p : V) → FgautoMem V p Vs → (x : SignedLetter S) → Σ V (q ↦ FgautoStep S V E p x q)

def FgautoStallingsTotal (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S)) : Type
  ≔ FgautoTotal S (SignedWord S) (fgauto_stallings_edges S dec gens) (fgauto_stallings_vertices S dec gens)

{` Runs in deterministic graphs are unique. `}
def fgauto_run_unique (S V : Type) (E : List (FgautoEdge S V)) (hd : FgautoDeterministic S V E)
  (p : V) (w : SignedWord S) (q q' : V) (r : FgautoRun S V E p w q) (r' : FgautoRun S V E p w q') : Id V q q'
  ≔ match w [
  | nil. ↦ concat V q p q' (inverse V p q r) r'
  | cons. x w' ↦ fgauto_run_unique S V E hd (r .fst) w' q q' (r .snd .snd)
      (fgauto_run_start S V E (r' .fst) (r .fst) w' q'
        (inverse V (r .fst) (r' .fst) (hd p x (r .fst) (r' .fst) (r .snd .fst) (r' .snd .fst))) (r' .snd .snd)) ]

{` Running a total graph. `}
def fgauto_total_run (S V : Type) (E : List (FgautoEdge S V)) (Vs : List V) (tot : FgautoTotal S V E Vs)
  (ends : (p : V) (x : SignedLetter S) (q : V) → FgautoStep S V E p x q → FgautoMem V q Vs)
  (p : V) (mp : FgautoMem V p Vs) (u : SignedWord S) : Σ V (q ↦ Product (FgautoMem V q Vs) (FgautoRun S V E p u q))
  ≔ match u [
  | nil. ↦ (p, (mp, refl p))
  | cons. x u' ↦
    let z ≔ tot p mp x in
    let r ≔ fgauto_total_run S V E Vs tot ends (z .fst) (ends p x (z .fst) (z .snd)) u' in
    (r .fst, (r .snd .fst, (z .fst, (z .snd, r .snd .snd)))) ]

def fgauto_stallings_total_run (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (tot : FgautoStallingsTotal S dec gens) (u : SignedWord S)
  : Σ (SignedWord S) (q ↦ Product (FgautoMem (SignedWord S) q (fgauto_stallings_vertices S dec gens))
      (FgautoRun S (SignedWord S) (fgauto_stallings_edges S dec gens) (fgauto_stallings_base S dec gens) u q))
  ≔ fgauto_total_run S (SignedWord S) (fgauto_stallings_edges S dec gens) (fgauto_stallings_vertices S dec gens) tot
      (p x q s ↦ fgauto_stallings_endpoint_vertex S dec gens p x q s .snd)
      (fgauto_stallings_base S dec gens) (fgauto_stallings_base_vertex S dec gens) u

def fgauto_stallings_vertex_set (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  : isSet (FgautoStallingsVertex S dec gens)
  ≔ decidable_set_is_set (FgautoStallingsVertex S dec gens)
      (hedberg (FgautoStallingsVertex S dec gens)
        (fgauto_list_set_decidable_equality (SignedWord S) (signed_word_decidable_equality S dec)
          (fgauto_stallings_vertices S dec gens)))

def fgauto_total_vertex (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (tot : FgautoStallingsTotal S dec gens) (u : SignedWord S) : FgautoStallingsVertex S dec gens
  ≔ let r ≔ fgauto_stallings_total_run S dec gens tot u in
    (r .fst, mere (FgautoMem (SignedWord S) (r .fst) (fgauto_stallings_vertices S dec gens)) (r .snd .fst))

{` Same coset => same vertex. `}
def fgauto_total_vertex_respects (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (tot : FgautoStallingsTotal S dec gens) (u v : SignedWord S) (h : FgautoSameCoset S dec gens u v)
  : Id (FgautoStallingsVertex S dec gens) (fgauto_total_vertex S dec gens tot u) (fgauto_total_vertex S dec gens tot v)
  ≔ let E ≔ fgauto_stallings_edges S dec gens in
    let b ≔ fgauto_stallings_base S dec gens in
    let hd ≔ fgauto_stallings_deterministic S dec gens in
    let hs ≔ fgauto_stallings_symmetric S dec gens in
    let M ≔ append (SignedLetter S) u (word_inverse S v) in
    let ru ≔ fgauto_stallings_total_run S dec gens tot u in
    let rv ≔ fgauto_stallings_total_run S dec gens tot v in
    let rM ≔ fgauto_stallings_total_run S dec gens tot M in
    let acc ≔ fgauto_delta_sound S (SignedWord S) dec (signed_word_decidable_equality S dec) E b (word_reduction S dec M) b
      (fgauto_member_accepted S dec gens (word_reduction S dec M) (word_reduction_reduced S dec M)
        (fgauto_in_subgroup_red S dec gens M (word_reduction S dec M)
          (fgauto_wsym S (word_reduction S dec (word_reduction S dec M)) (word_reduction S dec M)
            (word_reduction_idempotent S dec M)) h)) in
    let eb ≔ fgauto_run_unique S (SignedWord S) E hd b (word_reduction S dec M) (rM .fst) b
      (fgauto_run_reduction S (SignedWord S) dec E hs hd b M (rM .fst) (rM .snd .snd)) acc in
    let sp ≔ fgauto_run_split S (SignedWord S) E b u (word_inverse S v) b
      (fgauto_run_end S (SignedWord S) E b M (rM .fst) b eb (rM .snd .snd)) in
    let m ≔ sp .fst in
    let qm ≔ fgauto_run_unique S (SignedWord S) E hd b u (ru .fst) m (ru .snd .snd) (sp .snd .fst) in
    let vm ≔ fgauto_run_word S (SignedWord S) E b (word_inverse S (word_inverse S v)) v m
      (fgauto_word_inverse_involutive S v)
      (fgauto_run_inverse S (SignedWord S) E hs m (word_inverse S v) b (sp .snd .snd)) in
    let qm' ≔ fgauto_run_unique S (SignedWord S) E hd b v (rv .fst) m (rv .snd .snd) vm in
    fgauto_list_set_path (SignedWord S) (fgauto_stallings_vertices S dec gens)
      (fgauto_total_vertex S dec gens tot u) (fgauto_total_vertex S dec gens tot v)
      (fgauto_wtrans S (ru .fst) m (rv .fst) qm (fgauto_wsym S (rv .fst) m qm'))

{` Same vertex => same coset. `}
def fgauto_total_vertex_reflects (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (tot : FgautoStallingsTotal S dec gens) (u v : SignedWord S)
  (e : Id (FgautoStallingsVertex S dec gens) (fgauto_total_vertex S dec gens tot u) (fgauto_total_vertex S dec gens tot v))
  : FgautoSameCoset S dec gens u v
  ≔ let E ≔ fgauto_stallings_edges S dec gens in
    let b ≔ fgauto_stallings_base S dec gens in
    let hs ≔ fgauto_stallings_symmetric S dec gens in
    let ru ≔ fgauto_stallings_total_run S dec gens tot u in
    let rv ≔ fgauto_stallings_total_run S dec gens tot v in
    let q ≔ refl ((z ↦ z .fst) : FgautoStallingsVertex S dec gens → SignedWord S) e in
    fgauto_run_loop_member S dec gens E (fgauto_stallings_coset_inv S dec gens .fst) b
      (fgauto_stallings_coset_inv S dec gens .snd) (append (SignedLetter S) u (word_inverse S v))
      (fgauto_run_append S (SignedWord S) E b u (rv .fst) (word_inverse S v) b
        (fgauto_run_end S (SignedWord S) E b u (ru .fst) (rv .fst) q (ru .snd .snd))
        (fgauto_run_inverse S (SignedWord S) E hs b v (rv .fst) (rv .snd .snd)))

{` The vertex reached by a word with a given run. `}
def fgauto_total_vertex_of_run (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (tot : FgautoStallingsTotal S dec gens) (w : SignedWord S) (v : FgautoStallingsVertex S dec gens)
  (r : FgautoRun S (SignedWord S) (fgauto_stallings_edges S dec gens) (fgauto_stallings_base S dec gens) w (v .fst))
  : Id (FgautoStallingsVertex S dec gens) (fgauto_total_vertex S dec gens tot w) v
  ≔ fgauto_list_set_path (SignedWord S) (fgauto_stallings_vertices S dec gens) (fgauto_total_vertex S dec gens tot w) v
      (fgauto_run_unique S (SignedWord S) (fgauto_stallings_edges S dec gens) (fgauto_stallings_deterministic S dec gens)
        (fgauto_stallings_base S dec gens) w (fgauto_stallings_total_run S dec gens tot w .fst) (v .fst)
        (fgauto_stallings_total_run S dec gens tot w .snd .snd) r)

def fgauto_vertex_word (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (v : FgautoStallingsVertex S dec gens)
  : Σ (SignedWord S) (w ↦ FgautoRun S (SignedWord S) (fgauto_stallings_edges S dec gens) (fgauto_stallings_base S dec gens) w (v .fst))
  ≔ fgauto_stallings_vertex_reachable S dec gens (v .fst)
      (decidable_pick (FgautoMem (SignedWord S) (v .fst) (fgauto_stallings_vertices S dec gens))
        (fgauto_mem_decide (SignedWord S) (signed_word_decidable_equality S dec) (v .fst) (fgauto_stallings_vertices S dec gens))
        (v .snd))

{` fggroups.tex:844, "<=" and the count: if S(H) is total, the right
   cosets of H are in bijection with the vertices of S(H). `}
def fgauto_cosets_vertices_equiv (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (tot : FgautoStallingsTotal S dec gens) : Equiv (FgautoRightCosets S dec gens) (FgautoStallingsVertex S dec gens)
  ≔ let R ≔ fgauto_coset_relation S dec gens in
    let C ≔ FgautoRightCosets S dec gens in
    let T ≔ FgautoStallingsVertex S dec gens in
    let phi : C → T ≔ quotient_rec (SignedWord S) T R (fgauto_stallings_vertex_set S dec gens)
      (fgauto_total_vertex S dec gens tot) (fgauto_total_vertex_respects S dec gens tot) in
    let psi : T → C ≔ v ↦ fgauto_right_coset S dec gens (fgauto_vertex_word S dec gens v .fst) in
    quasi_inverse_equiv C T phi psi
      (z ↦ mere_rec (BookFiber (SignedWord S) C (quotient_class (SignedWord S) R) z) (Id C (psi (phi z)) z)
        (quotient_set (SignedWord S) R (psi (phi z)) z)
        (y ↦
          let u ≔ y .fst in
          let w ≔ fgauto_vertex_word S dec gens (fgauto_total_vertex S dec gens tot u) in
          concat C (psi (phi z)) (psi (phi (fgauto_right_coset S dec gens u))) z
            (refl ((z0 ↦ psi (phi z0)) : C → C) (y .snd))
            (concat C (fgauto_right_coset S dec gens (w .fst)) (fgauto_right_coset S dec gens u) z
              (quotient_encode (SignedWord S) R (w .fst) u
                (fgauto_total_vertex_reflects S dec gens tot (w .fst) u
                  (fgauto_total_vertex_of_run S dec gens tot (w .fst) (fgauto_total_vertex S dec gens tot u) (w .snd))))
              (inverse C z (fgauto_right_coset S dec gens u) (y .snd))))
        (quotient_surjective (SignedWord S) R z))
      (v ↦ fgauto_total_vertex_of_run S dec gens tot (fgauto_vertex_word S dec gens v .fst) v
        (fgauto_vertex_word S dec gens v .snd))

def fgauto_total_finite_index (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (tot : FgautoStallingsTotal S dec gens)
  : Σ (FgautoFiniteIndex S dec gens) (h ↦ Id Nat (fgauto_index S dec gens h) (fgauto_stallings_vertex_count S dec gens))
  ≔ let C ≔ FgautoRightCosets S dec gens in
    let n ≔ fgauto_stallings_vertex_count S dec gens in
    let p : Id Type C (Fin n) ≔ ua C (Fin n)
      (compose_equiv C (FgautoStallingsVertex S dec gens) (Fin n) (fgauto_cosets_vertices_equiv S dec gens tot)
        (fgauto_stallings_vertex_count_equiv S dec gens)) in
    let h : IsFinite C ≔ mere (Σ Nat (m ↦ Id Type C (Fin m))) (n, p) in
    (h, cardinality_from_path C h n p)

{` Powers of a letter. `}
def fgauto_power (S : Type) (x : SignedLetter S) (n : Nat) : SignedWord S
  ≔ match n [ zero. ↦ nil. | suc. k ↦ cons. x (fgauto_power S x k) ]

def fgauto_power_snoc (S : Type) (x : SignedLetter S) (n : Nat)
  : Id (SignedWord S) (fgauto_power S x (suc. n)) (append (SignedLetter S) (fgauto_power S x n) (cons. x nil.))
  ≔ match n [
  | zero. ↦ refl (cons. x nil. : SignedWord S)
  | suc. k ↦ cons. (refl x) (fgauto_power_snoc S x k) ]

def fgauto_power_inverse (S : Type) (x : SignedLetter S) (n : Nat)
  : Id (SignedWord S) (word_inverse S (fgauto_power S x n)) (fgauto_power S (letter_complement S x) n)
  ≔ match n [
  | zero. ↦ refl (nil. : SignedWord S)
  | suc. k ↦ fgauto_wtrans S
      (append (SignedLetter S) (word_inverse S (fgauto_power S x k)) (cons. (letter_complement S x) nil.))
      (append (SignedLetter S) (fgauto_power S (letter_complement S x) k) (cons. (letter_complement S x) nil.))
      (fgauto_power S (letter_complement S x) (suc. k))
      (refl ((z ↦ append (SignedLetter S) z (cons. (letter_complement S x) nil.)) : SignedWord S → SignedWord S)
        (fgauto_power_inverse S x k))
      (fgauto_wsym S (fgauto_power S (letter_complement S x) (suc. k))
        (append (SignedLetter S) (fgauto_power S (letter_complement S x) k) (cons. (letter_complement S x) nil.))
        (fgauto_power_snoc S (letter_complement S x) k)) ]

def fgauto_power_reduced (S : Type) (x : SignedLetter S) (n : Nat) : IsReducedWord S (fgauto_power S x n)
  ≔ match n [
  | zero. ↦ star.
  | suc. k ↦ (match k [ zero. ↦ star. | suc. j ↦ e ↦ letter_complement_distinct S x (inverse (SignedLetter S) x (letter_complement S x) e) ],
      fgauto_power_reduced S x k) ]

{` x^i x-bar^j reduces to x^(i-j) or x-bar^(j-i). `}
def fgauto_power_diff (S : Type) (x : SignedLetter S) (i j : Nat) : SignedWord S
  ≔ match i, j [
  | zero., j ↦ fgauto_power S (letter_complement S x) j
  | suc. i', zero. ↦ fgauto_power S x (suc. i')
  | suc. i', suc. j' ↦ fgauto_power_diff S x i' j' ]

def fgauto_power_diff_reduction (S : Type) (dec : DecidableEquality S) (x : SignedLetter S) (i j : Nat)
  : Id (SignedWord S)
      (word_reduction S dec (append (SignedLetter S) (fgauto_power S x i) (fgauto_power S (letter_complement S x) j)))
      (fgauto_power_diff S x i j)
  ≔ let xb ≔ letter_complement S x in
    match i, j [
    | zero., j ↦ word_reduction_of_reduced S dec (fgauto_power S xb j) (fgauto_power_reduced S xb j)
    | suc. i', zero. ↦ fgauto_wtrans S
        (word_reduction S dec (append (SignedLetter S) (fgauto_power S x (suc. i')) nil.))
        (word_reduction S dec (fgauto_power S x (suc. i'))) (fgauto_power S x (suc. i'))
        (refl (word_reduction S dec) (append_nil (SignedLetter S) (fgauto_power S x (suc. i'))))
        (word_reduction_of_reduced S dec (fgauto_power S x (suc. i')) (fgauto_power_reduced S x (suc. i')))
    | suc. i', suc. j' ↦
      calc
        word_reduction S dec (append (SignedLetter S) (fgauto_power S x (suc. i')) (fgauto_power S xb (suc. j')))
        = word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) (fgauto_power S x i') (cons. x nil.))
            (fgauto_power S xb (suc. j')))
          by refl ((z ↦ word_reduction S dec (append (SignedLetter S) z (fgauto_power S xb (suc. j')))) : SignedWord S → SignedWord S)
               (fgauto_power_snoc S x i')
        = word_reduction S dec (append (SignedLetter S) (fgauto_power S x i')
            (cons. x (cons. xb (fgauto_power S xb j'))))
          by fgauto_red_assoc S dec (fgauto_power S x i') (cons. x nil.) (fgauto_power S xb (suc. j'))
        = word_reduction S dec (append (SignedLetter S) (fgauto_power S x i') (fgauto_power S xb j'))
          by fgauto_red_congr_right S dec (fgauto_power S x i') (cons. x (cons. xb (fgauto_power S xb j')))
               (fgauto_power S xb j') (word_reduction_cancel_pair S dec x (fgauto_power S xb j'))
        = fgauto_power_diff S x i' j'
          by fgauto_power_diff_reduction S dec x i' j' ∎ ]

{` For i /= j the difference is a nonempty power of x or of x-bar. `}
def FgautoNonemptyPower (S : Type) (x : SignedLetter S) (w : SignedWord S) : Type
  ≔ Sum (Σ Nat (m ↦ Id (SignedWord S) w (fgauto_power S x (suc. m))))
      (Σ Nat (m ↦ Id (SignedWord S) w (fgauto_power S (letter_complement S x) (suc. m))))

def fgauto_power_diff_nonempty (S : Type) (x : SignedLetter S) (i j : Nat) (n : Not (Id Nat i j))
  : FgautoNonemptyPower S x (fgauto_power_diff S x i j)
  ≔ match i, j [
  | zero., zero. ↦ match n (refl (zero. : Nat)) []
  | zero., suc. j' ↦ inr. (j', refl (fgauto_power S (letter_complement S x) (suc. j')))
  | suc. i', zero. ↦ inl. (i', refl (fgauto_power S x (suc. i')))
  | suc. i', suc. j' ↦ fgauto_power_diff_nonempty S x i' j' (e ↦ n (suc. e)) ]

{` A loop at p reading a nonempty power of x or x-bar forces an x-edge at p
   (symmetric graphs). `}
def fgauto_power_loop_step (S V : Type) (E : List (FgautoEdge S V)) (hs : FgautoSymmetric S V E) (p : V)
  (x : SignedLetter S) (w : SignedWord S) (k : FgautoNonemptyPower S x w) (r : FgautoRun S V E p w p)
  : Σ V (q ↦ FgautoStep S V E p x q)
  ≔ match k [
  | inl. a ↦
    let r' ≔ fgauto_run_word S V E p w (fgauto_power S x (suc. (a .fst))) p (a .snd) r in
    (r' .fst, r' .snd .fst)
  | inr. a ↦
    let xb ≔ letter_complement S x in
    let r1 ≔ fgauto_run_word S V E p w (fgauto_power S xb (suc. (a .fst))) p (a .snd) r in
    let r2 ≔ fgauto_run_inverse S V E hs p (fgauto_power S xb (suc. (a .fst))) p r1 in
    let r3 ≔ fgauto_run_word S V E p (word_inverse S (fgauto_power S xb (suc. (a .fst))))
      (fgauto_power S x (suc. (a .fst))) p
      (fgauto_wtrans S (word_inverse S (fgauto_power S xb (suc. (a .fst))))
        (fgauto_power S (letter_complement S xb) (suc. (a .fst))) (fgauto_power S x (suc. (a .fst)))
        (fgauto_power_inverse S xb (suc. (a .fst)))
        (refl ((y ↦ fgauto_power S y (suc. (a .fst))) : SignedLetter S → SignedWord S) (letter_complement_involutive S x)))
      r2 in
    (r3 .fst, r3 .snd .fst) ]

{` If H t x^i = H t x^j with i /= j and t leads from the base to p, then p
   has an x-edge. `}
def fgauto_coset_collision_edge (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (p : SignedWord S) (t : SignedWord S)
  (rt : FgautoRun S (SignedWord S) (fgauto_stallings_edges S dec gens) (fgauto_stallings_base S dec gens) t p)
  (x : SignedLetter S) (i j : Nat) (n : Not (Id Nat i j))
  (h : FgautoSameCoset S dec gens (append (SignedLetter S) t (fgauto_power S x i)) (append (SignedLetter S) t (fgauto_power S x j)))
  : Σ (SignedWord S) (q ↦ FgautoStep S (SignedWord S) (fgauto_stallings_edges S dec gens) p x q)
  ≔ let E ≔ fgauto_stallings_edges S dec gens in
    let b ≔ fgauto_stallings_base S dec gens in
    let hd ≔ fgauto_stallings_deterministic S dec gens in
    let hs ≔ fgauto_stallings_symmetric S dec gens in
    let xi ≔ fgauto_power S x i in
    let xbj ≔ fgauto_power S (letter_complement S x) j in
    let it ≔ word_inverse S t in
    let M ≔ append (SignedLetter S) (append (SignedLetter S) t xi) (word_inverse S (append (SignedLetter S) t (fgauto_power S x j))) in
    let rM ≔ fgauto_delta_sound S (SignedWord S) dec (signed_word_decidable_equality S dec) E b (word_reduction S dec M) b
      (fgauto_member_accepted S dec gens (word_reduction S dec M) (word_reduction_reduced S dec M)
        (fgauto_in_subgroup_red S dec gens M (word_reduction S dec M)
          (fgauto_wsym S (word_reduction S dec (word_reduction S dec M)) (word_reduction S dec M)
            (word_reduction_idempotent S dec M)) h)) in
    let W ≔ append (SignedLetter S) it (append (SignedLetter S) (word_reduction S dec M) t) in
    let rW ≔ fgauto_run_append S (SignedWord S) E p it b (append (SignedLetter S) (word_reduction S dec M) t) p
      (fgauto_run_inverse S (SignedWord S) E hs b t p rt)
      (fgauto_run_append S (SignedWord S) E b (word_reduction S dec M) b t p rM rt) in
    let eq : Id (SignedWord S) (word_reduction S dec W) (fgauto_power_diff S x i j)
      ≔ calc
          word_reduction S dec W
          = word_reduction S dec (append (SignedLetter S) it (append (SignedLetter S) M t))
            by fgauto_red_congr_right S dec it (append (SignedLetter S) (word_reduction S dec M) t)
                 (append (SignedLetter S) M t)
                 (fgauto_wsym S (word_reduction S dec (append (SignedLetter S) M t))
                   (word_reduction S dec (append (SignedLetter S) (word_reduction S dec M) t))
                   (word_reduction_append_left S dec M t))
          = word_reduction S dec (append (SignedLetter S) it
              (append (SignedLetter S) (append (SignedLetter S) t xi)
                (append (SignedLetter S) (append (SignedLetter S) xbj it) t)))
            by refl ((z ↦ word_reduction S dec (append (SignedLetter S) it z)) : SignedWord S → SignedWord S)
                 (fgauto_wtrans S (append (SignedLetter S) M t)
                   (append (SignedLetter S) (append (SignedLetter S) t xi)
                     (append (SignedLetter S) (word_inverse S (append (SignedLetter S) t (fgauto_power S x j))) t))
                   (append (SignedLetter S) (append (SignedLetter S) t xi)
                     (append (SignedLetter S) (append (SignedLetter S) xbj it) t))
                   (append_assoc (SignedLetter S) (append (SignedLetter S) t xi)
                     (word_inverse S (append (SignedLetter S) t (fgauto_power S x j))) t)
                   (refl ((z ↦ append (SignedLetter S) (append (SignedLetter S) t xi) (append (SignedLetter S) z t))
                       : SignedWord S → SignedWord S)
                     (fgauto_wtrans S (word_inverse S (append (SignedLetter S) t (fgauto_power S x j)))
                       (append (SignedLetter S) (word_inverse S (fgauto_power S x j)) it)
                       (append (SignedLetter S) xbj it)
                       (fgauto_word_inverse_append S t (fgauto_power S x j))
                       (refl ((z ↦ append (SignedLetter S) z it) : SignedWord S → SignedWord S)
                         (fgauto_power_inverse S x j)))))
          = word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) it t)
              (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t))))
            by refl (word_reduction S dec)
                 (fgauto_wtrans S
                   (append (SignedLetter S) it (append (SignedLetter S) (append (SignedLetter S) t xi)
                     (append (SignedLetter S) (append (SignedLetter S) xbj it) t)))
                   (append (SignedLetter S) it (append (SignedLetter S) t
                     (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t)))))
                   (append (SignedLetter S) (append (SignedLetter S) it t)
                     (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t))))
                   (refl ((z ↦ append (SignedLetter S) it z) : SignedWord S → SignedWord S)
                     (fgauto_wtrans S
                       (append (SignedLetter S) (append (SignedLetter S) t xi) (append (SignedLetter S) (append (SignedLetter S) xbj it) t))
                       (append (SignedLetter S) t (append (SignedLetter S) xi (append (SignedLetter S) (append (SignedLetter S) xbj it) t)))
                       (append (SignedLetter S) t (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t))))
                       (append_assoc (SignedLetter S) t xi (append (SignedLetter S) (append (SignedLetter S) xbj it) t))
                       (refl ((z ↦ append (SignedLetter S) t (append (SignedLetter S) xi z)) : SignedWord S → SignedWord S)
                         (append_assoc (SignedLetter S) xbj it t))))
                   (fgauto_wsym S
                     (append (SignedLetter S) (append (SignedLetter S) it t)
                       (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t))))
                     (append (SignedLetter S) it (append (SignedLetter S) t
                       (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t)))))
                     (append_assoc (SignedLetter S) it t
                       (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t))))))
          = word_reduction S dec (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t)))
            by fgauto_red_drop_left S dec (append (SignedLetter S) it t)
                 (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t)))
                 (fgauto_red_inverse_left S dec t)
          = word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) xi xbj) (append (SignedLetter S) it t))
            by fgauto_wsym S
                 (word_reduction S dec (append (SignedLetter S) (append (SignedLetter S) xi xbj) (append (SignedLetter S) it t)))
                 (word_reduction S dec (append (SignedLetter S) xi (append (SignedLetter S) xbj (append (SignedLetter S) it t))))
                 (fgauto_red_assoc S dec xi xbj (append (SignedLetter S) it t))
          = word_reduction S dec (append (SignedLetter S) xi xbj)
            by fgauto_red_drop_right S dec (append (SignedLetter S) xi xbj) (append (SignedLetter S) it t)
                 (fgauto_red_inverse_left S dec t)
          = fgauto_power_diff S x i j
            by fgauto_power_diff_reduction S dec x i j ∎ in
    fgauto_power_loop_step S (SignedWord S) E hs p x (fgauto_power_diff S x i j) (fgauto_power_diff_nonempty S x i j n)
      (fgauto_run_word S (SignedWord S) E p (word_reduction S dec W) (fgauto_power_diff S x i j) p eq
        (fgauto_run_reduction S (SignedWord S) dec E hs hd p W p rW))

{` fggroups.tex:844, "=>": finite index forces totality. `}
def fgauto_finite_index_no_missing_edge (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (hf : FgautoFiniteIndex S dec gens) (p : SignedWord S)
  (mp : FgautoMem (SignedWord S) p (fgauto_stallings_vertices S dec gens)) (x : SignedLetter S)
  (no : Not (Σ (SignedWord S) (q ↦ FgautoStep S (SignedWord S) (fgauto_stallings_edges S dec gens) p x q))) : Empty
  ≔ let C ≔ FgautoRightCosets S dec gens in
    let R ≔ fgauto_coset_relation S dec gens in
    let tr ≔ fgauto_stallings_vertex_reachable S dec gens p mp in
    let t ≔ tr .fst in
    let psi : Nat → C ≔ k ↦ fgauto_right_coset S dec gens (append (SignedLetter S) t (fgauto_power S x k)) in
    mere_rec (Σ Nat (N ↦ Id Type C (Fin N))) Empty empty_prop
      (z ↦
        let N ≔ z .fst in
        let e ≔ id_to_equiv C (Fin N) (z .snd) in
        let f : Fin (suc. N) → Fin N ≔ i ↦ e .map (psi (fin_index (suc. N) i)) in
        let col ≔ fin_pigeonhole N f in
        let il ≔ fin_index (suc. N) (col .left) in
        let ir ≔ fin_index (suc. N) (col .right) in
        no (fgauto_coset_collision_edge S dec gens p t (tr .snd) x il ir
          (q ↦ col .distinct (fin_index_injective (suc. N) (col .left) (col .right) q))
          (quotient_effective (SignedWord S) R (append (SignedLetter S) t (fgauto_power S x il))
            (append (SignedLetter S) t (fgauto_power S x ir)) .map
            (equivalence_injective C (Fin N) e (psi il) (psi ir) (col .same))))) hf

def fgauto_total_of_lookup (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (hf : FgautoFiniteIndex S dec gens) (p : SignedWord S)
  (mp : FgautoMem (SignedWord S) p (fgauto_stallings_vertices S dec gens)) (x : SignedLetter S)
  (o : Sum Unit (SignedWord S))
  (e : Id (Sum Unit (SignedWord S))
         (fgauto_lookup S (SignedWord S) dec (signed_word_decidable_equality S dec) (fgauto_stallings_edges S dec gens) p x) o)
  : Σ (SignedWord S) (q ↦ FgautoStep S (SignedWord S) (fgauto_stallings_edges S dec gens) p x q)
  ≔ let E ≔ fgauto_stallings_edges S dec gens in
    let dV ≔ signed_word_decidable_equality S dec in
    match o [
    | inr. q ↦ (q, fgauto_lookup_sound S (SignedWord S) dec dV E p x q e)
    | inl. u ↦ match fgauto_finite_index_no_missing_edge S dec gens hf p mp x
        (k ↦
          let c ≔ fgauto_lookup_complete S (SignedWord S) dec dV E p x (k .fst) (k .snd) in
          sum_encode Unit (SignedWord S) (inl. u) (inr. (c .fst))
            (concat (Sum Unit (SignedWord S)) (inl. u) (fgauto_lookup S (SignedWord S) dec dV E p x) (inr. (c .fst))
              (inverse (Sum Unit (SignedWord S)) (fgauto_lookup S (SignedWord S) dec dV E p x) (inl. u) e) (c .snd))) [] ]

def fgauto_finite_index_total (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (hf : FgautoFiniteIndex S dec gens) : FgautoStallingsTotal S dec gens
  ≔ p mp x ↦ fgauto_total_of_lookup S dec gens hf p mp x
      (fgauto_lookup S (SignedWord S) dec (signed_word_decidable_equality S dec) (fgauto_stallings_edges S dec gens) p x)
      (refl (fgauto_lookup S (SignedWord S) dec (signed_word_decidable_equality S dec) (fgauto_stallings_edges S dec gens) p x))

{` fggroups.tex:844 assembled. `}
def fgauto_finite_index_iff_total (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  : Product (FgautoFiniteIndex S dec gens → FgautoStallingsTotal S dec gens)
      (FgautoStallingsTotal S dec gens → FgautoFiniteIndex S dec gens)
  ≔ (fgauto_finite_index_total S dec gens, tot ↦ fgauto_total_finite_index S dec gens tot .fst)

def fgauto_index_vertex_count (S : Type) (dec : DecidableEquality S) (gens : List (SignedWord S))
  (h : FgautoFiniteIndex S dec gens)
  : Id Nat (fgauto_index S dec gens h) (fgauto_stallings_vertex_count S dec gens)
  ≔ let z ≔ fgauto_total_finite_index S dec gens (fgauto_finite_index_total S dec gens h) in
    concat Nat (fgauto_index S dec gens h) (fgauto_index S dec gens (z .fst)) (fgauto_stallings_vertex_count S dec gens)
      (refl (fgauto_index S dec gens) (mere_isprop (Σ Nat (n ↦ Id Type (FgautoRightCosets S dec gens) (Fin n))) h (z .fst)))
      (z .snd)
