export "1161-fgauto-recognizable-subgroups"

{` Chapter 11, automata part 13: finitely generated subgroups of a group G
   as rational subsets (the easy half of Anisimov–Seifert, fggroups.tex:956),
   and the direction "recognisable => regular preimage" of the theorem at
   fggroups.tex:891.

   The subgroup generated by a finite list gs of elements of G
   (FgautoGenerated) consists of the products of lists of elements of gs and
   their inverses; it is the least subgroup containing gs
   (fgauto_generated_subgroup, fgauto_generated_least).  A subgroup H is
   finitely generated if H = <gs> for some finite gs.  Then
   H = (gs ∪ gs^-1)* is rational (fgauto_finitely_generated_rational).

   891 "=>": if X ⊆ G is recognized by a finite right action of G, the
   automaton with states Fin n and edges q -x-> q . alpha~(x) recognizes
   alpha~^-1(X) (fgauto_recognizable_preimage_regular). `}

def fgauto_sym_gens (G : AbstractGroup) (gs : List (G .carrier)) : List (G .carrier)
  ≔ append (G .carrier) gs (fgauto_list_map (G .carrier) (G .carrier) (G .inv) gs)

def FgautoGenerated (G : AbstractGroup) (gs : List (G .carrier)) (g : G .carrier) : Type
  ≔ Mere (Σ (List (G .carrier)) (l ↦ Product (FgautoAllIn (G .carrier) (x ↦ Mere (FgautoMem (G .carrier) x (fgauto_sym_gens G gs))) l)
       (Id (G .carrier) g (fgauto_list_product (fgauto_group_monoid G) l))))

def fgauto_generated_subset (G : AbstractGroup) (gs : List (G .carrier)) : Subtypes (G .carrier)
  ≔ g ↦ (FgautoGenerated G gs g, mere_isprop (Σ (List (G .carrier)) (l ↦
       Product (FgautoAllIn (G .carrier) (x ↦ Mere (FgautoMem (G .carrier) x (fgauto_sym_gens G gs))) l)
         (Id (G .carrier) g (fgauto_list_product (fgauto_group_monoid G) l)))))

def FgautoFinitelyGeneratedSubgroup (G : AbstractGroup) (H : G .carrier → Type) : Type
  ≔ Mere (Σ (List (G .carrier)) (gs ↦ (g : G .carrier) → FgautoIff (H g) (FgautoGenerated G gs g)))

{` Products of lists. `}
def fgauto_list_product_append (G : AbstractGroup) (l m : List (G .carrier))
  : Id (G .carrier) (fgauto_list_product (fgauto_group_monoid G) (append (G .carrier) l m))
      (G .mul (fgauto_list_product (fgauto_group_monoid G) l) (fgauto_list_product (fgauto_group_monoid G) m))
  ≔ let P ≔ fgauto_list_product (fgauto_group_monoid G) in
    match l [
    | nil. ↦ inverse (G .carrier) (G .mul (G .unit) (P m)) (P m) (G .laws .unit_left (P m))
    | cons. x t ↦ concat (G .carrier) (G .mul x (P (append (G .carrier) t m))) (G .mul x (G .mul (P t) (P m)))
        (G .mul (G .mul x (P t)) (P m))
        (refl (G .mul x) (fgauto_list_product_append G t m)) (G .laws .assoc x (P t) (P m)) ]

def fgauto_allin_append (A : Type) (P : A → Type) (l m : List A) (hl : FgautoAllIn A P l) (hm : FgautoAllIn A P m)
  : FgautoAllIn A P (append A l m)
  ≔ match l [ nil. ↦ hm | cons. x t ↦ (hl .fst, fgauto_allin_append A P t m (hl .snd) hm) ]

{` The inverse of a product: reverse and invert. `}
def fgauto_inverse_list (G : AbstractGroup) (l : List (G .carrier)) : List (G .carrier)
  ≔ match l [ nil. ↦ nil. | cons. x t ↦ append (G .carrier) (fgauto_inverse_list G t) (cons. (G .inv x) nil.) ]

def fgauto_inverse_list_product (G : AbstractGroup) (l : List (G .carrier))
  : Id (G .carrier) (fgauto_list_product (fgauto_group_monoid G) (fgauto_inverse_list G l))
      (G .inv (fgauto_list_product (fgauto_group_monoid G) l))
  ≔ let P ≔ fgauto_list_product (fgauto_group_monoid G) in
    let C ≔ G .carrier in
    match l [
    | nil. ↦ inverse C (G .inv (G .unit)) (G .unit) (ag_inv_unit G)
    | cons. x t ↦
      calc
        P (append C (fgauto_inverse_list G t) (cons. (G .inv x) nil.))
        = G .mul (P (fgauto_inverse_list G t)) (G .mul (G .inv x) (G .unit))
          by fgauto_list_product_append G (fgauto_inverse_list G t) (cons. (G .inv x) nil.)
        = G .mul (G .inv (P t)) (G .inv x)
          by refl ((u v ↦ G .mul u v) : C → C → C) (fgauto_inverse_list_product G t) (G .laws .unit_right (G .inv x))
        = G .inv (G .mul x (P t))
          by inverse C (G .inv (G .mul x (P t))) (G .mul (G .inv (P t)) (G .inv x)) (ag_inv_mul G x (P t)) ∎ ]

def fgauto_inv_mem_back (G : AbstractGroup) (gs : List (G .carrier)) (x : G .carrier)
  (k : FgautoMem (G .carrier) x (fgauto_list_map (G .carrier) (G .carrier) (G .inv) gs)) : FgautoMem (G .carrier) (G .inv x) gs
  ≔ match gs [
  | nil. ↦ match k []
  | cons. y t ↦ match k [
    | inl. e ↦ inl. (concat (G .carrier) (G .inv x) (G .inv (G .inv y)) y (refl (G .inv) e) (ag_inv_inv G y))
    | inr. k' ↦ inr. (fgauto_inv_mem_back G t x k') ] ]

def fgauto_sym_gens_inv (G : AbstractGroup) (gs : List (G .carrier)) (x : G .carrier)
  (m : FgautoMem (G .carrier) x (fgauto_sym_gens G gs)) : FgautoMem (G .carrier) (G .inv x) (fgauto_sym_gens G gs)
  ≔ let C ≔ G .carrier in
    let ig ≔ fgauto_list_map C C (G .inv) gs in
    match fgauto_mem_append_split C x gs ig m [
    | inl. k ↦ fgauto_mem_append_right C (G .inv x) gs ig (fgauto_mem_map C C (G .inv) x gs k)
    | inr. k ↦ fgauto_mem_append_left C (G .inv x) gs ig (fgauto_inv_mem_back G gs x k) ]

def fgauto_inverse_list_allin (G : AbstractGroup) (gs : List (G .carrier)) (l : List (G .carrier))
  (h : FgautoAllIn (G .carrier) (x ↦ Mere (FgautoMem (G .carrier) x (fgauto_sym_gens G gs))) l)
  : FgautoAllIn (G .carrier) (x ↦ Mere (FgautoMem (G .carrier) x (fgauto_sym_gens G gs))) (fgauto_inverse_list G l)
  ≔ let C ≔ G .carrier in
    let Q ≔ (x : C) ↦ Mere (FgautoMem C x (fgauto_sym_gens G gs)) in
    match l [
    | nil. ↦ star.
    | cons. x t ↦ fgauto_allin_append C Q (fgauto_inverse_list G t) (cons. (G .inv x) nil.)
        (fgauto_inverse_list_allin G gs t (h .snd))
        (mere_rec (FgautoMem C x (fgauto_sym_gens G gs)) (Q (G .inv x)) (mere_isprop (FgautoMem C (G .inv x) (fgauto_sym_gens G gs)))
           (m ↦ mere (FgautoMem C (G .inv x) (fgauto_sym_gens G gs)) (fgauto_sym_gens_inv G gs x m)) (h .fst), star.) ]

{` <gs> is a subgroup containing gs, and the least one. `}
def fgauto_generated_subgroup (G : AbstractGroup) (gs : List (G .carrier))
  : FgautoAbstractSubgroup G (fgauto_generated_subset G gs)
  ≔ let C ≔ G .carrier in
    let Q ≔ (x : C) ↦ Mere (FgautoMem C x (fgauto_sym_gens G gs)) in
    let P ≔ fgauto_list_product (fgauto_group_monoid G) in
    let T ≔ (g : C) ↦ Σ (List C) (l ↦ Product (FgautoAllIn C Q l) (Id C g (P l))) in
    (mere (T (G .unit)) (nil., (star., refl (G .unit))),
     (g h mg mh ↦ mere_rec (T g) (FgautoGenerated G gs (G .mul g h)) (mere_isprop (T (G .mul g h)))
        (a ↦ mere_rec (T h) (FgautoGenerated G gs (G .mul g h)) (mere_isprop (T (G .mul g h)))
          (b ↦ mere (T (G .mul g h)) (append C (a .fst) (b .fst),
            (fgauto_allin_append C Q (a .fst) (b .fst) (a .snd .fst) (b .snd .fst),
             concat C (G .mul g h) (G .mul (P (a .fst)) (P (b .fst))) (P (append C (a .fst) (b .fst)))
               (refl ((u v ↦ G .mul u v) : C → C → C) (a .snd .snd) (b .snd .snd))
               (inverse C (P (append C (a .fst) (b .fst))) (G .mul (P (a .fst)) (P (b .fst)))
                 (fgauto_list_product_append G (a .fst) (b .fst)))))) mh) mg,
      g mg ↦ mere_rec (T g) (FgautoGenerated G gs (G .inv g)) (mere_isprop (T (G .inv g)))
        (a ↦ mere (T (G .inv g)) (fgauto_inverse_list G (a .fst),
          (fgauto_inverse_list_allin G gs (a .fst) (a .snd .fst),
           concat C (G .inv g) (G .inv (P (a .fst))) (P (fgauto_inverse_list G (a .fst)))
             (refl (G .inv) (a .snd .snd))
             (inverse C (P (fgauto_inverse_list G (a .fst))) (G .inv (P (a .fst))) (fgauto_inverse_list_product G (a .fst)))))) mg))

def fgauto_generated_contains (G : AbstractGroup) (gs : List (G .carrier)) (g : G .carrier)
  (m : FgautoMem (G .carrier) g gs) : FgautoGenerated G gs g
  ≔ mere (Σ (List (G .carrier)) (l ↦ Product (FgautoAllIn (G .carrier) (x ↦ Mere (FgautoMem (G .carrier) x (fgauto_sym_gens G gs))) l)
       (Id (G .carrier) g (fgauto_list_product (fgauto_group_monoid G) l))))
      (cons. g nil.,
       ((mere (FgautoMem (G .carrier) g (fgauto_sym_gens G gs))
          (fgauto_mem_append_left (G .carrier) g gs (fgauto_list_map (G .carrier) (G .carrier) (G .inv) gs) m), star.),
        inverse (G .carrier) (G .mul g (G .unit)) g (G .laws .unit_right g)))

def fgauto_generated_least_prod (G : AbstractGroup) (gs : List (G .carrier)) (K : Subtypes (G .carrier))
  (hK : FgautoAbstractSubgroup G K)
  (inK : (x : G .carrier) → FgautoMem (G .carrier) x (fgauto_sym_gens G gs) → K x .fst)
  (l : List (G .carrier)) (h : FgautoAllIn (G .carrier) (x ↦ Mere (FgautoMem (G .carrier) x (fgauto_sym_gens G gs))) l)
  : K (fgauto_list_product (fgauto_group_monoid G) l) .fst
  ≔ match l [
  | nil. ↦ hK .fst
  | cons. x t ↦ hK .snd .fst x (fgauto_list_product (fgauto_group_monoid G) t)
      (mere_rec (FgautoMem (G .carrier) x (fgauto_sym_gens G gs)) (K x .fst) (K x .snd) (inK x) (h .fst))
      (fgauto_generated_least_prod G gs K hK inK t (h .snd)) ]

def fgauto_generated_least (G : AbstractGroup) (gs : List (G .carrier)) (K : Subtypes (G .carrier))
  (hK : FgautoAbstractSubgroup G K) (hg : (g : G .carrier) → FgautoMem (G .carrier) g gs → K g .fst)
  (g : G .carrier) (m : FgautoGenerated G gs g) : K g .fst
  ≔ let C ≔ G .carrier in
    let Q ≔ (x : C) ↦ Mere (FgautoMem C x (fgauto_sym_gens G gs)) in
    let P ≔ fgauto_list_product (fgauto_group_monoid G) in
    let inK : (x : C) → FgautoMem C x (fgauto_sym_gens G gs) → K x .fst
      ≔ x mx ↦ match fgauto_mem_append_split C x gs (fgauto_list_map C C (G .inv) gs) mx [
        | inl. k ↦ hg x k
        | inr. k ↦ fgauto_group_subset_transport G K (G .inv (G .inv x)) x (ag_inv_inv G x)
            (hK .snd .snd (G .inv x) (hg (G .inv x) (fgauto_inv_mem_back G gs x k))) ] in
    let prod : (l : List C) → FgautoAllIn C Q l → K (P l) .fst
      ≔ fgauto_generated_least_prod G gs K hK inK in
    mere_rec (Σ (List C) (l ↦ Product (FgautoAllIn C Q l) (Id C g (P l)))) (K g .fst) (K g .snd)
      (z ↦ fgauto_group_subset_transport G K (P (z .fst)) g (inverse C g (P (z .fst)) (z .snd .snd))
        (prod (z .fst) (z .snd .fst))) m

{` fggroups.tex:956, "<=": a finitely generated subgroup is rational. `}
def fgauto_finitely_generated_rational (G : AbstractGroup) (H : G .carrier → Type)
  (h : FgautoFinitelyGeneratedSubgroup G H) : FgautoRational (fgauto_group_monoid G) H
  ≔ let M ≔ fgauto_group_monoid G in
    mere_rec (Σ (List (G .carrier)) (gs ↦ (g : G .carrier) → FgautoIff (H g) (FgautoGenerated G gs g)))
      (FgautoRational M H)
      (mere_isprop (Σ (FgautoRatExpr (G .carrier)) (r ↦ (m : G .carrier) → FgautoIff (H m) (fgauto_rat_mem M r m))))
      (z ↦ mere (Σ (FgautoRatExpr (G .carrier)) (r ↦ (m : G .carrier) → FgautoIff (H m) (fgauto_rat_mem M r m)))
        (rat_star. (rat_fin. (fgauto_sym_gens G (z .fst))), z .snd)) h

{` 891 "=>".  Filtering a list by a Boolean test. `}
def fgauto_filter_pick (A : Type) (p : A → Bool) (a : A) (b : Bool) (rest : List A) : List A
  ≔ match b [ true. ↦ cons. a rest | false. ↦ rest ]

def fgauto_list_filter (A : Type) (p : A → Bool) (l : List A) : List A
  ≔ match l [ nil. ↦ nil. | cons. a t ↦ fgauto_filter_pick A p a (p a) (fgauto_list_filter A p t) ]

def fgauto_filter_pick_intro (A : Type) (p : A → Bool) (a b : A) (pb : Bool) (l' rest : List A)
  (ih : FgautoMem A a l' → Id Bool (p a) true. → FgautoMem A a rest) (m : FgautoMem A a (cons. b l'))
  (t : Id Bool (p a) true.) (e : Id Bool (p b) pb) : FgautoMem A a (fgauto_filter_pick A p b pb rest)
  ≔ match pb [
  | true. ↦ match m [ inl. q ↦ inl. q | inr. m' ↦ inr. (ih m' t) ]
  | false. ↦ match m [
    | inl. q ↦ match bool_encode true. false.
        (concat Bool true. (p a) false. (inverse Bool (p a) true. t) (concat Bool (p a) (p b) false. (refl p q) e)) []
    | inr. m' ↦ ih m' t ] ]

def fgauto_filter_mem_intro (A : Type) (p : A → Bool) (a : A) (l : List A) (m : FgautoMem A a l) (t : Id Bool (p a) true.)
  : FgautoMem A a (fgauto_list_filter A p l)
  ≔ match l [
  | nil. ↦ match m []
  | cons. b l' ↦ fgauto_filter_pick_intro A p a b (p b) l' (fgauto_list_filter A p l')
      (fgauto_filter_mem_intro A p a l') m t (refl (p b)) ]

def fgauto_filter_pick_elim (A : Type) (p : A → Bool) (a b : A) (pb : Bool) (rest : List A)
  (ih : FgautoMem A a rest → Id Bool (p a) true.) (e : Id Bool (p b) pb) (m : FgautoMem A a (fgauto_filter_pick A p b pb rest))
  : Id Bool (p a) true.
  ≔ match pb [
  | true. ↦ match m [ inl. q ↦ concat Bool (p a) (p b) true. (refl p q) e | inr. m' ↦ ih m' ]
  | false. ↦ ih m ]

def fgauto_filter_mem_elim (A : Type) (p : A → Bool) (a : A) (l : List A) (m : FgautoMem A a (fgauto_list_filter A p l))
  : Id Bool (p a) true.
  ≔ match l [
  | nil. ↦ match m []
  | cons. b l' ↦ fgauto_filter_pick_elim A p a b (p b) (fgauto_list_filter A p l') (fgauto_filter_mem_elim A p a l')
      (refl (p b)) m ]

{` The automaton of a finite action. `}
def fgauto_action_edges_at (S : Type) (G : AbstractGroup) (a : S → G .carrier) (A : FgautoFiniteAction (fgauto_group_monoid G))
  (L : List (SignedLetter S)) (q : Fin (A .asize)) : List (FgautoEdge S (Fin (A .asize)))
  ≔ fgauto_list_map (SignedLetter S) (FgautoEdge S (Fin (A .asize))) (x ↦ (q, x, A .aact q (fgauto_matched_letter S G a x))) L

def fgauto_action_edges (S : Type) (G : AbstractGroup) (a : S → G .carrier) (A : FgautoFiniteAction (fgauto_group_monoid G))
  (L : List (SignedLetter S)) : List (FgautoEdge S (Fin (A .asize)))
  ≔ fgauto_list_bind (Fin (A .asize)) (FgautoEdge S (Fin (A .asize))) (fgauto_fin_list (A .asize)) (fgauto_action_edges_at S G a A L)

def fgauto_action_edges_at_functional (S : Type) (G : AbstractGroup) (a : S → G .carrier)
  (A : FgautoFiniteAction (fgauto_group_monoid G)) (L : List (SignedLetter S)) (f : Fin (A .asize))
  (p : Fin (A .asize)) (x : SignedLetter S) (q : Fin (A .asize))
  (s : FgautoStep S (Fin (A .asize)) (fgauto_action_edges_at S G a A L f) p x q)
  : Id (Fin (A .asize)) q (A .aact p (fgauto_matched_letter S G a x))
  ≔ match L [
  | nil. ↦ match s []
  | cons. y L' ↦ match s [
    | inl. t ↦ concat (Fin (A .asize)) q (A .aact f (fgauto_matched_letter S G a y)) (A .aact p (fgauto_matched_letter S G a x))
        (t .snd .snd)
        (refl ((u v ↦ A .aact u (fgauto_matched_letter S G a v)) : Fin (A .asize) → SignedLetter S → Fin (A .asize))
          (inverse (Fin (A .asize)) p f (t .fst)) (inverse (SignedLetter S) x y (t .snd .fst)))
    | inr. s' ↦ fgauto_action_edges_at_functional S G a A L' f p x q s' ] ]

def fgauto_action_run_value (S : Type) (G : AbstractGroup) (a : S → G .carrier) (A : FgautoFiniteAction (fgauto_group_monoid G))
  (L : List (SignedLetter S)) (g : Fin (A .asize)) (w : SignedWord S) (f : Fin (A .asize))
  (r : FgautoRun S (Fin (A .asize)) (fgauto_action_edges S G a A L) g w f)
  : Id (Fin (A .asize)) f (A .aact g (fgauto_matched_hom S G a w))
  ≔ let N ≔ A .asize in
    match w [
    | nil. ↦ concat (Fin N) f g (A .aact g (G .unit)) (inverse (Fin N) g f r) (inverse (Fin N) (A .aact g (G .unit)) g (A .aunit g))
    | cons. x w' ↦
      let ev ≔ fgauto_bind_edges_functional S (Fin N) (p y ↦ A .aact p (fgauto_matched_letter S G a y)) (fgauto_fin_list N)
          (fgauto_action_edges_at S G a A L) (fgauto_action_edges_at_functional S G a A L) g x (r .fst) (r .snd .fst) in
      concat (Fin N) f (A .aact (r .fst) (fgauto_matched_hom S G a w')) (A .aact g (fgauto_matched_hom S G a (cons. x w')))
        (fgauto_action_run_value S G a A L (r .fst) w' f (r .snd .snd))
        (concat (Fin N) (A .aact (r .fst) (fgauto_matched_hom S G a w'))
          (A .aact (A .aact g (fgauto_matched_letter S G a x)) (fgauto_matched_hom S G a w'))
          (A .aact g (fgauto_matched_hom S G a (cons. x w')))
          (refl ((y ↦ A .aact y (fgauto_matched_hom S G a w')) : Fin N → Fin N) ev)
          (inverse (Fin N) (A .aact g (fgauto_matched_hom S G a (cons. x w')))
            (A .aact (A .aact g (fgauto_matched_letter S G a x)) (fgauto_matched_hom S G a w'))
            (A .amul g (fgauto_matched_letter S G a x) (fgauto_matched_hom S G a w')))) ]

def fgauto_action_run_exists (S : Type) (G : AbstractGroup) (a : S → G .carrier) (A : FgautoFiniteAction (fgauto_group_monoid G))
  (L : List (SignedLetter S)) (cL : (x : SignedLetter S) → FgautoMem (SignedLetter S) x L) (g : Fin (A .asize)) (w : SignedWord S)
  : FgautoRun S (Fin (A .asize)) (fgauto_action_edges S G a A L) g w (A .aact g (fgauto_matched_hom S G a w))
  ≔ let N ≔ A .asize in
    match w [
    | nil. ↦ inverse (Fin N) (A .aact g (G .unit)) g (A .aunit g)
    | cons. x w' ↦
      let st ≔ A .aact g (fgauto_matched_letter S G a x) in
      (st,
       (fgauto_mem_edge_step S (Fin N) (fgauto_action_edges S G a A L) (g, x, st)
          (fgauto_mem_bind (Fin N) (FgautoEdge S (Fin N)) (fgauto_fin_list N) (fgauto_action_edges_at S G a A L) g (g, x, st)
            (fgauto_fin_list_complete N g)
            (fgauto_mem_map (SignedLetter S) (FgautoEdge S (Fin N)) (y ↦ (g, y, A .aact g (fgauto_matched_letter S G a y))) x L (cL x))),
        fgauto_run_end S (Fin N) (fgauto_action_edges S G a A L) st w' (A .aact st (fgauto_matched_hom S G a w'))
          (A .aact g (fgauto_matched_hom S G a (cons. x w')))
          (inverse (Fin N) (A .aact g (fgauto_matched_hom S G a (cons. x w'))) (A .aact st (fgauto_matched_hom S G a w'))
            (A .amul g (fgauto_matched_letter S G a x) (fgauto_matched_hom S G a w')))
          (fgauto_action_run_exists S G a A L cL st w'))) ]

def fgauto_action_nfa (S : Type) (G : AbstractGroup) (a : S → G .carrier) (A : FgautoFiniteAction (fgauto_group_monoid G))
  (L : List (SignedLetter S)) (q0 : Fin (A .asize)) (F : Fin (A .asize) → Bool) : FgautoNFA S
  ≔ (Fin (A .asize), fin_decidable_equality (A .asize), fgauto_action_edges S G a A L, q0,
     fgauto_list_filter (Fin (A .asize)) F (fgauto_fin_list (A .asize)))

def fgauto_action_nfa_language (S : Type) (G : AbstractGroup) (a : S → G .carrier) (A : FgautoFiniteAction (fgauto_group_monoid G))
  (L : List (SignedLetter S)) (cL : (x : SignedLetter S) → FgautoMem (SignedLetter S) x L) (q0 : Fin (A .asize))
  (F : Fin (A .asize) → Bool) (w : SignedWord S)
  : FgautoIff (Id Bool (F (A .aact q0 (fgauto_matched_hom S G a w))) true.) (FgautoNFAAccepts S (fgauto_action_nfa S G a A L q0 F) w)
  ≔ let N ≔ A .asize in
    let fin ≔ fgauto_list_filter (Fin N) F (fgauto_fin_list N) in
    let T ≔ Σ (Fin N) (f ↦ Product (FgautoMem (Fin N) f fin) (FgautoRun S (Fin N) (fgauto_action_edges S G a A L) q0 w f)) in
    (t ↦ mere T (A .aact q0 (fgauto_matched_hom S G a w),
       (fgauto_filter_mem_intro (Fin N) F (A .aact q0 (fgauto_matched_hom S G a w)) (fgauto_fin_list N)
          (fgauto_fin_list_complete N (A .aact q0 (fgauto_matched_hom S G a w))) t,
        fgauto_action_run_exists S G a A L cL q0 w)),
     h ↦ mere_rec T (Id Bool (F (A .aact q0 (fgauto_matched_hom S G a w))) true.)
       (bool_set (F (A .aact q0 (fgauto_matched_hom S G a w))) true.)
       (z ↦ transport (Fin N) (q ↦ Id Bool (F q) true.) (z .fst) (A .aact q0 (fgauto_matched_hom S G a w))
         (fgauto_action_run_value S G a A L q0 w (z .fst) (z .snd .snd))
         (fgauto_filter_mem_elim (Fin N) F (z .fst) (fgauto_fin_list N) (z .snd .fst))) h)

{` fggroups.tex:891, "=>": a subset of G recognized by a finite G-action has
   a regular preimage under the matched homomorphism (S finite). `}
def fgauto_recognizable_preimage_regular (S : Type) (hS : IsFinite S) (G : AbstractGroup) (a : S → G .carrier)
  (X : G .carrier → Type) (hX : FgautoRecognizable (fgauto_group_monoid G) X) : FgautoRegular S (FgautoPreimage S G a X)
  ≔ let M ≔ fgauto_group_monoid G in
    let goal ≔ FgautoRegular S (FgautoPreimage S G a X) in
    let hg ≔ mere_isprop (Σ (FgautoNFA S) (B ↦ (w : SignedWord S) → FgautoIff (FgautoPreimage S G a X w) (FgautoNFAAccepts S B w))) in
    mere_rec (Σ Nat (m ↦ Id Type S (Fin m))) goal hg
      (sm ↦
        let en ≔ fgauto_finite_enumeration S (sm .fst) (id_to_equiv S (Fin (sm .fst)) (sm .snd)) in
        let L ≔ fgauto_signed_letters S (en .fst) in
        let cL ≔ fgauto_signed_letters_complete S (en .fst) (en .snd) in
        mere_rec (Σ (FgautoFiniteAction M) (A ↦ Σ (Fin (A .asize)) (q0 ↦ Σ (Fin (A .asize) → Bool) (F ↦ FgautoRecognizes M A q0 F X))))
          goal hg
          (z ↦
            let A ≔ z .fst in
            let q0 ≔ z .snd .fst in
            let F ≔ z .snd .snd .fst in
            let hr ≔ z .snd .snd .snd in
            mere (Σ (FgautoNFA S) (B ↦ (w : SignedWord S) → FgautoIff (FgautoPreimage S G a X w) (FgautoNFAAccepts S B w)))
              (fgauto_action_nfa S G a A L q0 F,
               w ↦ (x ↦ fgauto_action_nfa_language S G a A L cL q0 F w .fst (hr (fgauto_matched_hom S G a w) .fst x),
                    y ↦ hr (fgauto_matched_hom S G a w) .snd (fgauto_action_nfa_language S G a A L cL q0 F w .snd y)))) hX) hS
