export "1169-fgauto-subset-simulation"

{` Chapter 11, automata part 21: the theorem at fggroups.tex:891 (marked
   "[?]" in the book; it holds): for a group G generated by a : S → G (S
   finite, matched homomorphism alpha~ surjective), a subset X ⊆ G is
   recognizable by a finite G-action iff alpha~^-1(X) ⊆ S~* is regular.
   "=>" is module 1162; "<=" here.

   Let B be a finite automaton for alpha~^-1(X).  Put g ~ g' iff
   X(g h) <=> X(g' h) for all h (the right syntactic congruence of X); G acts
   on G/~ by right multiplication, X is the preimage of the classes of
   elements of X, and G/~ is finite: for g = alpha~(u) the class of g is
   determined by the set of states reachable by u (subset simulation,
   module 1169), finitely many of which occur, and ~ is decidable by a
   search through the pairs of such sets. `}

def fgauto_matched_hom_append (S : Type) (G : AbstractGroup) (a : S → G .carrier) (u v : SignedWord S)
  : Id (G .carrier) (fgauto_matched_hom S G a (append (SignedLetter S) u v))
      (G .mul (fgauto_matched_hom S G a u) (fgauto_matched_hom S G a v))
  ≔ match u [
  | nil. ↦ inverse (G .carrier) (G .mul (G .unit) (fgauto_matched_hom S G a v)) (fgauto_matched_hom S G a v)
      (G .laws .unit_left (fgauto_matched_hom S G a v))
  | cons. x t ↦ concat (G .carrier)
      (G .mul (fgauto_matched_letter S G a x) (fgauto_matched_hom S G a (append (SignedLetter S) t v)))
      (G .mul (fgauto_matched_letter S G a x) (G .mul (fgauto_matched_hom S G a t) (fgauto_matched_hom S G a v)))
      (G .mul (G .mul (fgauto_matched_letter S G a x) (fgauto_matched_hom S G a t)) (fgauto_matched_hom S G a v))
      (refl (G .mul (fgauto_matched_letter S G a x)) (fgauto_matched_hom_append S G a t v))
      (G .laws .assoc (fgauto_matched_letter S G a x) (fgauto_matched_hom S G a t) (fgauto_matched_hom S G a v)) ]

def fgauto_iff_prop (A B : Type) (hA : isProp A) (hB : isProp B) : isProp (FgautoIff A B)
  ≔ product_prop (A → B) (B → A) (pi_prop A (_ ↦ B) (_ ↦ hB)) (pi_prop B (_ ↦ A) (_ ↦ hA))

def fgauto_bool_of_iff (b c : Bool) (h : FgautoIff (Id Bool b true.) (Id Bool c true.)) : Id Bool b c
  ≔ match b, c [
  | true., true. ↦ refl (true. : Bool)
  | false., false. ↦ refl (false. : Bool)
  | true., false. ↦ inverse Bool false. true. (h .fst (refl (true. : Bool)))
  | false., true. ↦ h .snd (refl (true. : Bool)) ]

def fgauto_decision_bool_iff (A B : Type) (dA : Decidable A) (dB : Decidable B) (f : A → B) (g : B → A)
  : Id Bool (fgauto_decision_bool A dA) (fgauto_decision_bool B dB)
  ≔ match dA [
  | inl. a ↦ match dB [ inl. _ ↦ refl (true. : Bool) | inr. n ↦ match n (f a) [] ]
  | inr. n ↦ match dB [ inl. b ↦ match n (g b) [] | inr. _ ↦ refl (false. : Bool) ] ]

{` Quotients: proposition-valued induction. `}
def fgauto_quotient_ind_prop (A : Type) (R : EquivalenceRelation A) (P : Quotient A R → Type) (hP : (z : Quotient A R) → isProp (P z))
  (h : (a : A) → P (quotient_class A R a)) (z : Quotient A R) : P z
  ≔ mere_rec (BookFiber A (Quotient A R) (quotient_class A R) z) (P z) (hP z)
      (y ↦ transport (Quotient A R) P (quotient_class A R (y .fst)) z (inverse (Quotient A R) z (quotient_class A R (y .fst)) (y .snd)) (h (y .fst)))
      (quotient_surjective A R z)

{` A finite set with a right action recognizes the preimages of decidable
   subsets. `}
def fgauto_finite_gset_recognizable (M : FgautoMonoid) (Y : Type) (hY : IsFinite Y) (act : Y → M .mcarrier → Y)
  (hu : (y : Y) → Id Y (act y (M .munit)) y) (hm : (y : Y) (m m' : M .mcarrier) → Id Y (act y (M .mmul m m')) (act (act y m) m'))
  (y0 : Y) (FY : Y → Bool) (X : M .mcarrier → Type) (hX : (m : M .mcarrier) → FgautoIff (X m) (Id Bool (FY (act y0 m)) true.))
  : FgautoRecognizable M X
  ≔ mere_rec (Σ Nat (N ↦ Id Type Y (Fin N))) (FgautoRecognizable M X)
      (mere_isprop (Σ (FgautoFiniteAction M) (A ↦ Σ (Fin (A .asize)) (q0 ↦ Σ (Fin (A .asize) → Bool) (F ↦ FgautoRecognizes M A q0 F X)))))
      (z ↦
        let N ≔ z .fst in
        let e ≔ id_to_equiv Y (Fin N) (z .snd) in
        let ei ≔ equiv_inverse_map Y (Fin N) e in
        let act' : Fin N → M .mcarrier → Fin N ≔ q m ↦ e .map (act (ei q) m) in
        let A : FgautoFiniteAction M
          ≔ (N, act',
             q ↦ concat (Fin N) (act' q (M .munit)) (e .map (ei q)) q (refl (e .map) (hu (ei q))) (equiv_counit Y (Fin N) e q),
             q m m' ↦ concat (Fin N) (act' q (M .mmul m m')) (e .map (act (act (ei q) m) m')) (act' (act' q m) m')
               (refl (e .map) (hm (ei q) m m'))
               (refl ((y ↦ e .map (act y m')) : Y → Fin N) (equiv_unit Y (Fin N) e (act (ei q) m)))) in
        let q0 ≔ e .map y0 in
        let F : Fin N → Bool ≔ q ↦ FY (ei q) in
        let pth : (m : M .mcarrier) → Id Bool (F (act' q0 m)) (FY (act y0 m))
          ≔ m ↦ concat Bool (F (act' q0 m)) (FY (act (ei q0) m)) (FY (act y0 m))
              (refl FY (inverse Y (act (ei q0) m) (ei (e .map (act (ei q0) m))) (equiv_unit Y (Fin N) e (act (ei q0) m))))
              (refl ((y ↦ FY (act y m)) : Y → Bool) (inverse Y y0 (ei q0) (equiv_unit Y (Fin N) e y0))) in
        mere (Σ (FgautoFiniteAction M) (A0 ↦ Σ (Fin (A0 .asize)) (q00 ↦ Σ (Fin (A0 .asize) → Bool) (F0 ↦ FgautoRecognizes M A0 q00 F0 X))))
          (A, (q0, (F, m ↦
            (x ↦ concat Bool (F (act' q0 m)) (FY (act y0 m)) true. (pth m) (hX m .fst x),
             t ↦ hX m .snd (concat Bool (FY (act y0 m)) (F (act' q0 m)) true. (inverse Bool (F (act' q0 m)) (FY (act y0 m)) (pth m)) t))))))
      hY

{` Deciding "for all elements of a list". `}
def fgauto_list_all_decide (A : Type) (P : A → Type) (dP : (a : A) → Decidable (P a)) (l : List A)
  : Sum ((a : A) → FgautoMem A a l → P a) (Σ A (a ↦ Product (FgautoMem A a l) (Not (P a))))
  ≔ match l [
  | nil. ↦ inl. (a m ↦ match m [])
  | cons. b t ↦ match dP b [
    | inr. n ↦ inr. (b, (inl. (refl b), n))
    | inl. pb ↦ match fgauto_list_all_decide A P dP t [
      | inr. y ↦ inr. (y .fst, (inr. (y .snd .fst), y .snd .snd))
      | inl. f ↦ inl. (a m ↦ match m [ inl. e ↦ transport A P b a (inverse A a b e) pb | inr. m' ↦ f a m' ]) ] ] ]

{` The pair graph. `}
def fgauto_pair_step (S : Type) (dec : DecidableEquality S) (B : FgautoNFA S)
  (pq : Product (Fin (fgauto_nfa_k S B) → Bool) (Fin (fgauto_nfa_k S B) → Bool)) (x : SignedLetter S)
  : Product (Fin (fgauto_nfa_k S B) → Bool) (Fin (fgauto_nfa_k S B) → Bool)
  ≔ (fgauto_nfa_delta S dec B (pq .fst) x, fgauto_nfa_delta S dec B (pq .snd) x)

def fgauto_pair_iterate (S : Type) (dec : DecidableEquality S) (B : FgautoNFA S) (P P' : Fin (fgauto_nfa_k S B) → Bool) (w : SignedWord S)
  : Id (Product (Fin (fgauto_nfa_k S B) → Bool) (Fin (fgauto_nfa_k S B) → Bool))
      (fgauto_fun_iterate S (Product (Fin (fgauto_nfa_k S B) → Bool) (Fin (fgauto_nfa_k S B) → Bool)) (fgauto_pair_step S dec B) (P, P') w)
      (fgauto_nfa_sim S dec B P w, fgauto_nfa_sim S dec B P' w)
  ≔ match w [
  | nil. ↦ refl ((P, P') : Product (Fin (fgauto_nfa_k S B) → Bool) (Fin (fgauto_nfa_k S B) → Bool))
  | cons. x w' ↦ fgauto_pair_iterate S dec B (fgauto_nfa_delta S dec B P x) (fgauto_nfa_delta S dec B P' x) w' ]

{` The setting of 891 "<=". `}
def FgautoSyntacticRight (G : AbstractGroup) (X : Subtypes (G .carrier)) (g g' : G .carrier) : Type
  ≔ (h : G .carrier) → FgautoIff (X (G .mul g h) .fst) (X (G .mul g' h) .fst)

def fgauto_syntactic_relation (G : AbstractGroup) (X : Subtypes (G .carrier)) : EquivalenceRelation (G .carrier)
  ≔ (g g' ↦ (FgautoSyntacticRight G X g g',
       pi_prop (G .carrier) (h ↦ FgautoIff (X (G .mul g h) .fst) (X (G .mul g' h) .fst))
         (h ↦ fgauto_iff_prop (X (G .mul g h) .fst) (X (G .mul g' h) .fst) (X (G .mul g h) .snd) (X (G .mul g' h) .snd))),
     g h ↦ (x ↦ x, x ↦ x),
     g g' r h ↦ (r h .snd, r h .fst),
     g g' g'' r1 r2 h ↦ (x ↦ r2 h .fst (r1 h .fst x), x ↦ r1 h .snd (r2 h .snd x)))

def fgauto_syntactic_mul (G : AbstractGroup) (X : Subtypes (G .carrier)) (g g' k : G .carrier)
  (r : FgautoSyntacticRight G X g g') : FgautoSyntacticRight G X (G .mul g k) (G .mul g' k)
  ≔ h ↦
    let C ≔ G .carrier in
    let t1 ≔ (x : X (G .mul g (G .mul k h)) .fst) ↦ transport C (y ↦ X y .fst) (G .mul g (G .mul k h)) (G .mul (G .mul g k) h) (G .laws .assoc g k h) x in
    let t2 ≔ (x : X (G .mul g' (G .mul k h)) .fst) ↦ transport C (y ↦ X y .fst) (G .mul g' (G .mul k h)) (G .mul (G .mul g' k) h) (G .laws .assoc g' k h) x in
    let s1 ≔ (x : X (G .mul (G .mul g k) h) .fst) ↦ transport C (y ↦ X y .fst) (G .mul (G .mul g k) h) (G .mul g (G .mul k h))
      (inverse C (G .mul g (G .mul k h)) (G .mul (G .mul g k) h) (G .laws .assoc g k h)) x in
    let s2 ≔ (x : X (G .mul (G .mul g' k) h) .fst) ↦ transport C (y ↦ X y .fst) (G .mul (G .mul g' k) h) (G .mul g' (G .mul k h))
      (inverse C (G .mul g' (G .mul k h)) (G .mul (G .mul g' k) h) (G .laws .assoc g' k h)) x in
    (x ↦ t2 (r (G .mul k h) .fst (s1 x)), x ↦ t1 (r (G .mul k h) .snd (s2 x)))

def FgautoSyntacticClasses (G : AbstractGroup) (X : Subtypes (G .carrier)) : Type
  ≔ Quotient (G .carrier) (fgauto_syntactic_relation G X)

def fgauto_syntactic_act (G : AbstractGroup) (X : Subtypes (G .carrier)) (z : FgautoSyntacticClasses G X) (k : G .carrier)
  : FgautoSyntacticClasses G X
  ≔ let R ≔ fgauto_syntactic_relation G X in
    quotient_rec (G .carrier) (FgautoSyntacticClasses G X) R (quotient_set (G .carrier) R) (g ↦ quotient_class (G .carrier) R (G .mul g k))
      (g g' r ↦ quotient_encode (G .carrier) R (G .mul g k) (G .mul g' k) (fgauto_syntactic_mul G X g g' k r)) z

{` Words: membership of products in X through the automaton. `}
def fgauto_891_word_iff (S : Type) (dec : DecidableEquality S) (G : AbstractGroup) (a : S → G .carrier) (X : Subtypes (G .carrier))
  (B : FgautoNFA S) (hB : (w : SignedWord S) → FgautoIff (X (fgauto_matched_hom S G a w) .fst) (FgautoNFAAccepts S B w))
  (u v : SignedWord S)
  : FgautoIff (X (G .mul (fgauto_matched_hom S G a u) (fgauto_matched_hom S G a v)) .fst)
      (Id Bool (fgauto_nfa_meets S B (fgauto_nfa_sim S dec B (fgauto_nfa_sim S dec B (fgauto_nfa_init_vec S B) u) v)) true.)
  ≔ let C ≔ G .carrier in
    let I ≔ fgauto_nfa_init_vec S B in
    let ep ≔ fgauto_matched_hom_append S G a u v in
    let es ≔ fgauto_fun_iterate_append S (Fin (fgauto_nfa_k S B) → Bool) (fgauto_nfa_delta S dec B) I u v in
    let acc ≔ fgauto_nfa_accepts_sim S dec B (append (SignedLetter S) u v) in
    (x ↦ transport (Fin (fgauto_nfa_k S B) → Bool) (P ↦ Id Bool (fgauto_nfa_meets S B P) true.)
       (fgauto_nfa_sim S dec B I (append (SignedLetter S) u v)) (fgauto_nfa_sim S dec B (fgauto_nfa_sim S dec B I u) v) es
       (acc .fst (hB (append (SignedLetter S) u v) .fst
         (transport C (y ↦ X y .fst) (G .mul (fgauto_matched_hom S G a u) (fgauto_matched_hom S G a v))
           (fgauto_matched_hom S G a (append (SignedLetter S) u v))
           (inverse C (fgauto_matched_hom S G a (append (SignedLetter S) u v)) (G .mul (fgauto_matched_hom S G a u) (fgauto_matched_hom S G a v)) ep) x))),
     t ↦ transport C (y ↦ X y .fst) (fgauto_matched_hom S G a (append (SignedLetter S) u v))
       (G .mul (fgauto_matched_hom S G a u) (fgauto_matched_hom S G a v)) ep
       (hB (append (SignedLetter S) u v) .snd
         (acc .snd (transport (Fin (fgauto_nfa_k S B) → Bool) (P ↦ Id Bool (fgauto_nfa_meets S B P) true.)
           (fgauto_nfa_sim S dec B (fgauto_nfa_sim S dec B I u) v) (fgauto_nfa_sim S dec B I (append (SignedLetter S) u v))
           (inverse (Fin (fgauto_nfa_k S B) → Bool) (fgauto_nfa_sim S dec B I (append (SignedLetter S) u v))
             (fgauto_nfa_sim S dec B (fgauto_nfa_sim S dec B I u) v) es) t))))

{` Equal simulation sets give equivalent elements. `}
def fgauto_891_same_sim (S : Type) (dec : DecidableEquality S) (G : AbstractGroup) (a : S → G .carrier) (gen : FgautoGeneratesGroup S G a)
  (X : Subtypes (G .carrier)) (B : FgautoNFA S)
  (hB : (w : SignedWord S) → FgautoIff (X (fgauto_matched_hom S G a w) .fst) (FgautoNFAAccepts S B w))
  (u u' : SignedWord S)
  (h : (v : SignedWord S) → Id Bool (fgauto_nfa_meets S B (fgauto_nfa_sim S dec B (fgauto_nfa_sim S dec B (fgauto_nfa_init_vec S B) u) v))
          (fgauto_nfa_meets S B (fgauto_nfa_sim S dec B (fgauto_nfa_sim S dec B (fgauto_nfa_init_vec S B) u') v)))
  : FgautoSyntacticRight G X (fgauto_matched_hom S G a u) (fgauto_matched_hom S G a u')
  ≔ k ↦
    let C ≔ G .carrier in
    let x ≔ fgauto_matched_hom S G a u in
    let y ≔ fgauto_matched_hom S G a u' in
    mere_rec (Σ (SignedWord S) (v ↦ Id C (fgauto_matched_hom S G a v) k)) (FgautoIff (X (G .mul x k) .fst) (X (G .mul y k) .fst))
      (fgauto_iff_prop (X (G .mul x k) .fst) (X (G .mul y k) .fst) (X (G .mul x k) .snd) (X (G .mul y k) .snd))
      (vz ↦
        let v ≔ vz .fst in
        let tr ≔ (g : C) (p : X (G .mul g (fgauto_matched_hom S G a v)) .fst) ↦
          transport C (z ↦ X (G .mul g z) .fst) (fgauto_matched_hom S G a v) k (vz .snd) p in
        let rt ≔ (g : C) (p : X (G .mul g k) .fst) ↦
          transport C (z ↦ X (G .mul g z) .fst) k (fgauto_matched_hom S G a v) (inverse C (fgauto_matched_hom S G a v) k (vz .snd)) p in
        let iu ≔ fgauto_891_word_iff S dec G a X B hB u v in
        let iu' ≔ fgauto_891_word_iff S dec G a X B hB u' v in
        let mu ≔ fgauto_nfa_meets S B (fgauto_nfa_sim S dec B (fgauto_nfa_sim S dec B (fgauto_nfa_init_vec S B) u) v) in
        let mu' ≔ fgauto_nfa_meets S B (fgauto_nfa_sim S dec B (fgauto_nfa_sim S dec B (fgauto_nfa_init_vec S B) u') v) in
        (p ↦ tr y (iu' .snd (concat Bool mu' mu true. (inverse Bool mu mu' (h v)) (iu .fst (rt x p)))),
         p ↦ tr x (iu .snd (concat Bool mu mu' true. (h v) (iu' .fst (rt y p))))))
      (gen k)
